'use strict';

function latestBy(items, timestamp) {
  return [...items].sort((left, right) => Date.parse(timestamp(right) || 0) - Date.parse(timestamp(left) || 0))[0] || null;
}

function jinxApproved(reviews, login, headSha) {
  if (!login || !headSha) return false;
  const latest = latestBy(
    reviews.filter(review => review.user?.login?.toLowerCase() === login.toLowerCase() && review.submitted_at),
    review => review.submitted_at,
  );
  if (!latest || latest.state !== 'COMMENTED' || latest.commit_id !== headSha) return false;
  return /^\s*(?:Jinx verdict:\s*)?No blockers(?: remain| found)?\s*\.?\s*$/im.test(latest.body || '');
}

function claudeApproved(comments, headSha, mainSha) {
  const latest = latestBy(
    comments.filter(comment => comment.user?.login === 'claude[bot]' && comment.user?.type === 'Bot'),
    comment => comment.created_at,
  );
  if (!latest || !headSha || !mainSha) return false;
  const lines = (latest.body || '').split(/\r?\n/).map(line => line.trim()).filter(Boolean);
  while (lines.length && /^(?:---\s*)?_?\*?Generated by Claude Code\*?_?$/i.test(lines.at(-1))) lines.pop();
  while (lines.length && /^---+$/.test(lines.at(-1))) lines.pop();
  return lines.includes(`PR head SHA reviewed: ${headSha}`) &&
    lines.includes(`Main SHA reviewed against: ${mainSha}`) &&
    lines.at(-1) === 'Claude verdict: OK to merge';
}

function isImportantFinding(body) {
  return (body || '').split(/\r?\n/).some(line => {
    const normalized = line
      .replace(/^\s*(?:(?:>\s*)|(?:[-*+]\s+)|(?:\d+[.)]\s+))+/, '')
      .replace(/^[*_`]+/, '')
      .replace(/^\d+[.)]\s+/, '')
      .replace(/^[*_`]+/, '');
    return /^Important(?:[*_`]+)?\s*:/i.test(normalized);
  });
}

function hasUnresolvedImportant(threads) {
  return threads.some(thread => !thread.isResolved && thread.comments.some(isImportantFinding));
}

function hasProtectedAutoMergeChange(paths) {
  return paths.some(path => path.startsWith('.github/workflows/') ||
    path === '.github/scripts/review-gate.cjs' ||
    path === 'tests/allowed_skips.json' ||
    path === 'tests/test_frozen_contract.mjs' ||
    path === 'tests/test_review_gate.mjs' ||
    path === 'tools/run-suites.mjs');
}

function latestCiSucceeded(runs, pullNumber, headSha) {
  const latest = latestBy(
    runs.filter(run => run.event === 'pull_request' &&
      (run.pull_requests || []).some(link => link.number === pullNumber && link.head?.sha === headSha)),
    run => run.created_at,
  );
  return Boolean(latest && latest.head_sha === headSha && latest.conclusion === 'success');
}

module.exports = {
  claudeApproved,
  hasProtectedAutoMergeChange,
  hasUnresolvedImportant,
  isImportantFinding,
  jinxApproved,
  latestCiSucceeded,
};
