'use strict';

const crypto = require('node:crypto');

function latestBy(items, timestamp) {
  return [...items].sort((left, right) => Date.parse(timestamp(right) || 0) - Date.parse(timestamp(left) || 0))[0] || null;
}

function jinxApproved(reviews, login, headSha) {
  if (!login || !headSha) return false;
  const latest = latestBy(
    reviews.filter(review => review.user?.login?.toLowerCase() === login.toLowerCase() && review.submitted_at),
    review => review.submitted_at,
  );
  if (!latest || latest.state !== 'COMMENTED' || latest.commit_id !== headSha) return false;
  return (latest.body || '').split(/\r?\n/).some(line => {
    const normalized = line.replace(/[*_`]/g, '').trim();
    return /^(?:Jinx verdict:\s*)?No blockers(?: remain| found)?\s*\.?$/i.test(normalized);
  });
}

function isIndependentReviewer(login, authorLogin) {
  return Boolean(login && authorLogin && login.toLowerCase() !== authorLogin.toLowerCase());
}

function descriptionSha256(pull) {
  return crypto.createHash('sha256')
    .update(JSON.stringify([pull?.title || '', pull?.body || '']), 'utf8')
    .digest('hex');
}

function claudeApproved(comments, headSha, mainSha, descriptionSha) {
  const latest = latestBy(
    comments.filter(comment => comment.user?.login === 'claude[bot]' && comment.user?.type === 'Bot'),
    comment => comment.created_at,
  );
  if (!latest || !headSha || !mainSha) return false;
  const lines = (latest.body || '').split(/\r?\n/).map(line => line.trim()).filter(Boolean);
  while (lines.length && /^(?:---\s*)?_?\*?Generated by Claude Code\*?_?$/i.test(lines.at(-1))) lines.pop();
  while (lines.length && /^---+$/.test(lines.at(-1))) lines.pop();
  return lines.includes(`PR head SHA reviewed: ${headSha}`) &&
    lines.includes(`Main SHA reviewed against: ${mainSha}`) &&
    lines.includes(`PR description SHA-256 reviewed: ${descriptionSha}`) &&
    lines.at(-1) === 'Claude verdict: OK to merge';
}

function isImportantFinding(body) {
  const text = typeof body === 'string' ? body : body?.body || '';
  if (/\bP1(?:\s+Badge)?\b/i.test(text.slice(0, 500))) return true;
  return text.split(/\r?\n/).some(line => {
    const normalized = line
      .replace(/^\s*(?:(?:>\s*)|(?:[-*+]\s+)|(?:\d+[.)]\s+))+/, '')
      .replace(/^[*_`]+/, '')
      .replace(/^\d+[.)]\s+/, '')
      .replace(/^[*_`]+/, '');
    return /^Important(?:[*_`]+)?\s*:/i.test(normalized);
  });
}

function isEligiblePullRequest(pull, mainSha, behindBy) {
  return Boolean(pull && pull.state === 'open' && !pull.draft && pull.base?.ref === 'main' &&
    pull.mergeable === true && mainSha && pull.base?.sha === mainSha && behindBy === 0);
}

function hasUnresolvedImportant(threads) {
  return threads.some(thread => !thread.isResolved && thread.comments.some(isImportantFinding));
}

function hasProtectedAutoMergeChange(files) {
  return files.some(file => [file.filename, file.previous_filename].filter(Boolean).some(path =>
    path.startsWith('.github/workflows/') ||
    path === '.github/scripts/review-gate.cjs' ||
    path === 'tests/allowed_skips.json' ||
    path === 'tests/test_frozen_contract.mjs' ||
    path === 'tests/test_review_gate.mjs' ||
    path === 'tools/run-suites.mjs'));
}

function changedFilesComplete(files, expectedCount) {
  return Number.isInteger(expectedCount) && files.length === expectedCount;
}

function latestCiSucceeded(runs, pullNumber, headSha) {
  const latest = latestBy(
    runs.filter(run => run.event === 'pull_request' &&
      (run.pull_requests || []).some(link => link.number === pullNumber && link.head?.sha === headSha)),
    run => run.created_at,
  );
  return Boolean(latest && latest.head_sha === headSha && latest.conclusion === 'success');
}

module.exports = {
  claudeApproved,
  changedFilesComplete,
  descriptionSha256,
  hasProtectedAutoMergeChange,
  hasUnresolvedImportant,
  isIndependentReviewer,
  isImportantFinding,
  isEligiblePullRequest,
  jinxApproved,
  latestCiSucceeded,
};
