// Full multi-point QA of Flight Control MES v72: demo build and production build.
import {execFileSync} from 'node:child_process'; import {chromium} from 'playwright'; import fs from 'fs'; import path from 'node:path'; import {fileURLToPath, pathToFileURL} from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const results=[]; const add=(build,area,check,ok,detail='')=>results.push({build,area,check,result:ok===true?'Pass':ok==='Skip'?'Skip':'Fail',detail:String(detail??'').slice(0,400)});
const b=await chromium.launch(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{});
const FILES={demo:pathToFileURL(path.join(ROOT,'tests/fixtures/demo_qa150_publish.html')).href,prod:pathToFileURL(path.join(ROOT,'tests/fixtures/publish.html')).href};

async function newPage(w=1440){const ctx=await b.newContext({viewport:{width:w,height:1000}});const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(String(e.message||e)));p.on('console',m=>{if(m.type()==='error'&&!/ERR_FILE_NOT_FOUND|favicon/.test(m.text()))errs.push('console: '+m.text());});return {p,errs,ctx};}
async function signIn(p,build,u,pw='demo1234',displayName){await p.evaluate(()=>{try{sessionStorage.removeItem('skyryse-mes-session-v1');}catch(e){}}).catch(()=>{});
  await p.goto(FILES[build]);await p.waitForTimeout(900);
  await p.evaluate(([x,pw,dn])=>{const un=document.querySelector('#sk-boot input[name=username]');if(!un)return;const f=un.closest('form');const pwd=f.querySelector('input[type=password]');un.value=x;un.dispatchEvent(new Event('input',{bubbles:true}));pwd.value=pw;pwd.dispatchEvent(new Event('input',{bubbles:true}));const cf=f.querySelector('input[name=confirm]');if(cf){cf.value=pw;cf.dispatchEvent(new Event('input',{bubbles:true}));}const d=f.querySelector('input[name=displayName]');if(d&&dn){d.value=dn;d.dispatchEvent(new Event('input',{bubbles:true}));}f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));},[u,pw,displayName]);
  await p.waitForTimeout(2600);await p.evaluate(()=>{document.body.click();document.querySelectorAll('.mnv-landing').forEach(e=>e.remove());try{sessionStorage.setItem('sk-mnv-landing-seen','1');}catch(e){}});}
const run=(p,fn,a)=>p.evaluate(fn,a);
async function flow(build,area,name,fn){try{const r=await fn();add(build,area,name,r===true||r==='Skip'?r:false,r===true?'':String(r));}catch(e){add(build,area,name,false,String(e));}}
const stripStorage=async p=>p.evaluate(()=>{try{localStorage.clear();sessionStorage.clear();}catch(e){}}).catch(()=>{});

// =============================== DEMO BUILD ===============================
{
const D='Demo';
let {p,errs}=await newPage();
await stripStorage(p);
const t0=Date.now();await signIn(p,'demo','master');const loadMs=Date.now()-t0;
const ds=await run(p,()=>({valid:MES.validate(state),orders:state.orders.length,byStatus:state.orders.reduce((a,o)=>{a[o.status]=(a[o.status]||0)+1;return a},{}),plan:(state.plannedOrders||[]).length,mnv:Object.fromEntries(Object.entries(state.maneuver).filter(([k,v])=>Array.isArray(v)).map(([k,v])=>[k,v.length])),keys:Object.keys(state.maneuver),ecr:(state.ecrRequests||[]).length,ecrIds:(state.ecrRequests||[]).map(e=>e.id),stamps:(state.stamps||[]).length,users:skAuth.users().map(u=>u.username+':'+u.role),tickets:state.orders.reduce((n,o)=>n+o.tickets.length,0),serials:(state.serialLog||[]).length,role:skAuth.role(),user:skAuth.user().username,v2:state.maneuver.__ticketsV2}));
add(D,'Load','Demo workspace loads, signs in as master and validates',ds.valid&&ds.user==='master',`load ${loadMs} ms, role ${ds.role}`);
add(D,'Load','No page or console errors at load',errs.length===0,errs.join(' | '));
add(D,'Dataset','150 work orders present',ds.orders===150,JSON.stringify(ds.byStatus));
add(D,'Dataset','55 planned orders present',ds.plan===55,String(ds.plan));
add(D,'Dataset','Ticket model v2 applied: cars, mrb, ncs, sprs and no fracas/escapes/feedback keys',ds.v2===2&&['cars','mrb','ncs','sprs'].every(k=>ds.keys.includes(k))&&!['fracas','escapes','feedback'].some(k=>ds.keys.includes(k)),JSON.stringify(ds.mnv));
add(D,'Dataset','Migrated FRACAS records now SPRs and escapes now stock NCs',ds.mnv.sprs>=12&&ds.mnv.ncs>=10,JSON.stringify(ds.mnv));
add(D,'Dataset','Change requests use MCR ids for process and ECR ids for design',ds.ecrIds.some(i=>/^MCR-/.test(i))&&ds.ecrIds.some(i=>/^ECR-/.test(i)),ds.ecrIds.slice(0,8).join(','));
add(D,'Dataset','Seven pilot accounts seeded with roles',ds.users.length>=7&&['master:admin','demo:qm','mfgeng:me','operations:operator','tech:technician','quality:qe','engineering:swe'].every(x=>ds.users.includes(x)),ds.users.join(' '));
add(D,'Dataset','Stamp register populated',ds.stamps>0,String(ds.stamps));
add(D,'Dataset','Work-order tickets present',ds.tickets>0,String(ds.tickets));

// ---- Views at three widths (fresh contexts, master session) ----
const views=['home','orders','quality','activity','serials','wis','wi','order','plan-home','plan','plan-kanban','plan-forecast','mnv-home','mnv-intake','mnv-cars','mnv-car','mnv-mrb','mnv-board','mnv-spr','mnv-changes','mnv-metrics','mnv-nc','trace'];
for(const w of [1440,1280,1024]){
  const {p:q,errs:e2}=await newPage(w); await stripStorage(q); await signIn(q,'demo','master');
  for(const v of views){
    const r=await q.evaluate(v=>{try{if(v==='mnv-car')window.mnvSel.car=state.maneuver.cars[0].id;if(v==='mnv-board')window.mnvSel.board=state.maneuver.mrb[0].id;if(v==='mnv-nc')window.mnvSel.nc=state.maneuver.ncs[0].id;if(v==='trace')traceQuery=(state.orders.find(o=>o.inventory&&o.inventory.lotNumber)||{inventory:{}}).inventory.lotNumber||'SN';if(v==='order')selectedId=state.orders.find(o=>o.status==='Building').id;if(v==='wi'){const w=state.masterWIs[0];selectedWI={id:w.id,revision:w.revision};}view=v;render();
      const over=[...document.querySelectorAll('*')].filter(el=>el.scrollWidth>el.clientWidth+1&&el.clientWidth>0&&/auto|scroll/.test(getComputedStyle(el).overflowX)).map(el=>String(el.className).slice(0,40)+' '+el.scrollWidth+'/'+el.clientWidth);
      const bodyOver=document.documentElement.scrollWidth>document.documentElement.clientWidth+1;
      return {ok:true,over,bodyOver,main:(document.getElementById('main')||{}).children?.length||0};}catch(e){return {ok:false,err:String(e)}}},v);
    await q.waitForTimeout(60);
    add(D,'Render '+w,`View ${v} renders`,r.ok&&r.main>0,r.err||'');
    if(w===1440)add(D,'Layout '+w,`View ${v} has no horizontal overflow`,r.ok&&!r.bodyOver&&!r.over.length,r.over.join('; '));
  }
  add(D,'Render '+w,'No page or console errors across all views',e2.length===0,e2.slice(0,3).join(' | '));
  await q.context().close();
}

// ---- Engine walk on clones ----
const eng=await run(p,()=>{
  const out=[];const ok=(name,fn)=>{try{const r=fn();out.push({name,ok:r===true||r==='Skip'?r:false,detail:typeof r==='string'?r:''});}catch(e){out.push({name,ok:false,detail:String(e)});}};
  const s=structuredClone(state); const C=()=>structuredClone(s);
  const asSeat=(seat,fn)=>{const orig=skAuth.actor;const map={'Quality':'quality','Manufacturing Engineering':'mfgeng','Engineering':'engineering'};skAuth.actor=()=>({name:'Seat '+seat,role:seat,credentialId:'ACCT-'+(map[seat]||seat),account:map[seat]||seat,accountRole:'qm'});try{return fn();}finally{skAuth.actor=orig;}};
  ok('summary() on every order',()=>s.orders.every(o=>MES.summary(o)!==undefined));
  ok('canAdvance() on every order',()=>{s.orders.forEach(o=>MES.canAdvance(o));return true;});
  ok('blockingTickets() on every order',()=>{s.orders.forEach(o=>MES.blockingTickets(o));return true;});
  ok('releaseApproval() on every order',()=>{s.orders.forEach(o=>MES.releaseApproval(o));return true;});
  ok('fullHistory() on every order',()=>{s.orders.forEach(o=>MES.fullHistory(o));return true;});
  ok('inventoryReadiness() on every order',()=>{s.orders.forEach(o=>MES.inventoryReadiness(s,o));return true;});
  ok('every Building order has ready materials',()=>s.orders.filter(o=>o.status==='Building').every(o=>o.materials.every(m=>m.ready)));
  ok('every Closed order has all operations done or a closedAs',()=>s.orders.filter(o=>o.status==='Closed').every(o=>o.closedAs||o.operations.every(op=>op.done)));
  ok('serials unique across workspace',()=>{const all=(s.serialLog||[]).map(e=>e.serial);return new Set(all).size===all.length;});
  ok('ticket ids unique across WO tickets and stock NCs',()=>{const all=s.orders.flatMap(o=>o.tickets.map(t=>t.id)).concat(s.maneuver.ncs.map(t=>t.id));return new Set(all).size===all.length;});
  ok('history ids unique per order',()=>s.orders.every(o=>new Set(o.history.map(h=>h.id)).size===o.history.length));
  ok('every stocked WO has one lot shared by all its serials',()=>{const inv=s.orders.filter(o=>o.inventory&&o.inventory.serials&&o.inventory.serials.length>1);if(!inv.length)return 'Skip';return inv.every(o=>{const lot=o.inventory.lotNumber;return !!lot&&(s.serialLog||[]).filter(e=>o.inventory.serials.includes(e.serial)).every(e=>!e.lotNumber||e.lotNumber===lot);});});
  ok('lot numbers unique per work order',()=>{const lots=s.orders.filter(o=>o.inventory&&o.inventory.lotNumber).map(o=>o.inventory.lotNumber);return new Set(lots).size===lots.length;});
  const bld=s.orders.find(o=>o.status==='Building');
  ok('setPriority keeps state valid',()=>{const c=C();const r=MES.setPriority(c,bld.id,'High');return r.ok&&MES.validate(c);});
  ok('setSchedule keeps state valid',()=>{const c=C();const r=MES.setSchedule(c,bld.id,new Date().toISOString().slice(0,10),new Date(Date.now()+7*86400000).toISOString().slice(0,10));return (r.ok&&MES.validate(c))||r.message;});
  const draftApproved=s.orders.find(o=>o.status==='Draft'&&(!MES.requiresReleaseQA(o)||(MES.releaseApproval(o)&&MES.releaseApproval(o).status==='Approved')));
  ok('advance Draft to Kitting keeps state valid',()=>{if(!draftApproved)return 'Skip';const c=C();const r=MES.advance(c,draftApproved.id);return r.ok&&MES.validate(c)&&MES.getOrder(c,draftApproved.id).status==='Kitting';});
  const draftPending=s.orders.find(o=>o.status==='Draft'&&MES.requiresReleaseQA(o)&&!(MES.releaseApproval(o)&&MES.releaseApproval(o).status==='Approved'));
  ok('advance Draft without QA release is refused',()=>{if(!draftPending)return 'Skip';const c=C();const r=MES.advance(c,draftPending.id);return !r.ok&&MES.validate(c);});
  const kit=s.orders.find(o=>o.status==='Kitting');
  ok('advance Kitting without a kit list file is refused',()=>{if(!kit)return 'Skip';const c=C();const o=MES.getOrder(c,kit.id);o.kitFiles=[];o.materials.forEach(m=>{const l=MES.availableLots(m.partNumber)[0];MES.setMaterialLot(c,o.id,m.id,l?l.lot:'L1');MES.setMaterial(c,o.id,m.id,true);});const r=MES.advance(c,o.id);return !r.ok&&/kit/i.test(r.message)?true:r.message;});
  ok('advance Kitting with kit list file succeeds',()=>{if(!kit)return 'Skip';const c=C();const o=MES.getOrder(c,kit.id);o.materials.forEach(m=>{const l=MES.availableLots(m.partNumber)[0];MES.setMaterialLot(c,o.id,m.id,l?l.lot:'L1');MES.setMaterial(c,o.id,m.id,true);});const a=MES.addKitFile(c,o.id,{name:'kit.pdf',type:'application/pdf',size:10,dataUrl:null});if(!a.ok)return a.message;const r=MES.advance(c,o.id);return (r.ok&&MES.validate(c)&&MES.getOrder(c,o.id).status==='Building')||r.message;});
  ok('removeKitFile works and re-blocks advance',()=>{if(!kit)return 'Skip';const c=C();const o=MES.getOrder(c,kit.id);const a=MES.addKitFile(c,o.id,{name:'kit.pdf',type:'application/pdf',size:10,dataUrl:null});const f=(MES.getOrder(c,kit.id).kitFiles||[])[0];const r=MES.removeKitFile(c,o.id,f.id);return r.ok&&!(MES.getOrder(c,kit.id).kitFiles||[]).length?true:r.message;});
  const held=s.orders.find(o=>o.status==='Building'&&MES.blockingTickets(o).length);
  ok('advance held order is refused',()=>{if(!held)return 'Skip';const c=C();return !MES.advance(c,held.id).ok;});
  ok('completeOperation with a hold is refused',()=>{if(!held)return 'Skip';const c=C();const op=held.operations.find(x=>!x.done);if(!op)return 'Skip';const r=MES.completeOperation(c,held.id,op.id,'note',{tools:[],noTools:true,stampNumber:'QI-01'});return !r.ok;});
  const quality=s.orders.find(o=>o.status==='Quality');
  ok('closeOrder from Quality creates inventory payload with a lot',()=>{if(!quality)return 'Skip';const c=C();const r=MES.closeOrder(c,quality.id);const o=MES.getOrder(c,quality.id);return (r.ok&&MES.validate(c)&&o.status==='Closed'&&(!MES.isSerialized(o)||(o.inventory&&o.inventory.lotNumber)))||r.message;});
  ok('netsuiteCsv produces a payload for a stocked order',()=>{const o=s.orders.find(o=>o.inventory&&o.inventory.lotNumber);if(!o)return 'Skip';const csv=MES.netsuiteCsv(o);return typeof csv==='string'&&csv.includes(o.inventory.lotNumber);});
  ok('moveToInventory stocks a finished order under one lot shared by all its serials',()=>{const c=C();const q=c.orders.find(o=>['Quality','Closed'].includes(o.status)&&!o.inventory&&MES.inventoryReadiness(c,o).ready);if(!q)return 'Skip';const r=MES.moveToInventory(c,q.id,{location:MES.SITES[0],bin:'A1'});if(!r.ok)return r.message;const o=MES.getOrder(c,q.id);const lot=o.inventory&&o.inventory.lotNumber;return !!lot&&MES.orderSerials(c,o).every(e=>e.lotNumber===lot)&&MES.validate(c)?true:'lot not shared';});
  ok('markNetSuitePosted records a transaction number on a newly stocked order',()=>{const c=C();const q=c.orders.find(o=>['Quality','Closed'].includes(o.status)&&!o.inventory&&MES.inventoryReadiness(c,o).ready);if(!q)return 'Skip';const mv=MES.moveToInventory(c,q.id,{location:MES.SITES[0],bin:'A1'});if(!mv.ok)return mv.message;const o=MES.getOrder(c,q.id);const r=MES.markNetSuitePosted(c,o.id,'IA-55012');return (r.ok&&MES.validate(c))||r.message;});
  const ncOpen=s.orders.flatMap(o=>o.tickets.filter(t=>t.status==='Open'&&!t.dispo).map(t=>({o,t})))[0];
  ok('dispositionTicket Rework keeps state valid',()=>{if(!ncOpen)return 'Skip';const c=C();const r=MES.dispositionTicket(c,ncOpen.o.id,ncOpen.t.id,{decision:'Rework',note:'Rework at the bench.'});return r.ok&&MES.validate(c);});
  ok('dispositionTicket Use as is on a Production order routes to the MRB',()=>{const x=s.orders.flatMap(o=>o.tickets.filter(t=>t.status==='Open'&&!t.dispo).map(t=>({o,t}))).find(x=>x.o.pedigree==='Production');if(!x)return 'Skip';const c=C();const r=MES.dispositionTicket(c,x.o.id,x.t.id,{decision:'Use as is',note:'Cosmetic.'});const t=MES.getOrder(c,x.o.id).tickets.find(t=>t.id===x.t.id);return r.ok&&FlightManeuver.needsMRB(MES.getOrder(c,x.o.id),t)&&/MRB/.test(r.message)&&!MES.resolveTicket(c,x.o.id,x.t.id,'Closing.',{defectCode:'DMG',subCode:'DMG-03'}).ok?true:r.message;});
  ok('Use as is routes Development to MRB but not Development NFF',()=>{const t={dispo:{decision:'Use as is'}};return FlightManeuver.needsMRB({pedigree:'Development'},t)&&!FlightManeuver.needsMRB({pedigree:'Development NFF'},t);});
  const gated=s.orders.flatMap(o=>o.tickets.filter(t=>t.status==='Open'&&t.dispo&&['Use as is','Repair'].includes(t.dispo.decision)).map(t=>({o,t}))).find(x=>{const m=FlightManeuver.mrbFor(s,x.o.id,x.t.id);return !m||m.status!=='Approved';});
  ok('resolveTicket without MRB approval is gated',()=>{if(!gated)return 'Skip';const c=C();return !MES.resolveTicket(c,gated.o.id,gated.t.id,'Closing.',{}).ok;});
  ok('returnDisposition clears a disposition',()=>{if(!gated)return 'Skip';const c=C();const r=MES.returnDisposition(c,gated.o.id,gated.t.id,'Board asked for a new proposal.');return (r.ok&&MES.validate(c))||r.message;});
  ok('addOrder past the cap is refused',()=>{const c=C();while(c.orders.length<250)c.orders.push(structuredClone(c.orders[0]));const wi=c.masterWIs.find(w=>w.status==='Released');const r=MES.addOrder(c,{masterWI:wi.id+'|'+wi.revision,pedigree:'Production',subcategory:'Mfg.',quantity:1,aircraft:MES.AIRCRAFT[0],site:MES.SITES[0]});return !r.ok;});
  ok('splitOrder on a Kitting multi-unit order',()=>{const o=s.orders.find(o=>o.status==='Kitting'&&o.quantity>1&&!MES.blockingTickets(o).length);if(!o)return 'Skip';const c=C();const r=MES.splitOrder(c,o.id,1,'Shortage on one unit.');return (r.ok&&MES.validate(c)&&c.orders.length===s.orders.length+1)||r.message;});
  ok('requestWorkOrder then decideWORequest',()=>{const c=C();const wi=c.masterWIs.find(w=>w.status==='Released');const r=MES.requestWorkOrder(c,{masterWI:wi.id+'|'+wi.revision,partNumber:wi.partNumber,revision:wi.partRevision||MES.partDefinition(wi.partNumber)?.revision,pedigree:'Production',subcategory:'Mfg.',quantity:1,aircraft:MES.AIRCRAFT[0],site:MES.SITES[0],reason:'QA run',need:new Date(Date.now()+14*86400000).toISOString().slice(0,10)});if(!r.ok)return r.message;const id=r.id||(c.woRequests||[]).at(-1)?.id;const d=MES.decideWORequest(c,id,'declined',{note:'QA run: decline path.'});return (d.ok&&MES.validate(c))||d.message;});
  ok('postNotice, acknowledgeNotice, updateNotice',()=>{const c=C();const r=MES.postNotice(c,{kind:MES.NOTICE_KINDS[0],title:'QA notice',body:'Posted by the QA run.'});if(!r.ok)return r.message;const n=c.notices.find(x=>x.title==='QA notice');const a=MES.acknowledgeNotice(c,n.id);const u=MES.updateNotice(c,n.id,'remove');return ((a.ok||/does not need/.test(a.message))&&u.ok&&MES.validate(c))||(a.message+' / '+u.message);});
  ok('addPurchaseOrder links to an external operation',()=>{const c=C();let o=c.orders.find(o=>o.operations.some(op=>op.classification===MES.EXTERNAL_CLASS&&!op.externalPO));if(!o){o=c.orders.find(o=>o.status==='Building'&&!MES.pendingSequenceChange(o));const a=MES.addOrderOperation(c,o.id,{title:'Plating',description:'x',steps:'A\nB',position:o.operations.length,buyoffType:'Technician',classification:MES.EXTERNAL_CLASS,callouts:[],poMode:'request',poVendor:'Acme Plating',poProcess:'Anodize per MIL-A-8625 Type II'});if(!a.ok)return a.message;o=MES.getOrder(c,o.id);}const op=o.operations.find(op=>op.classification===MES.EXTERNAL_CLASS&&!op.externalPO);if(!op)return 'Skip';const r=MES.addPurchaseOrder(c,o.id,op.id,{poNumber:'PO-99001'});return (r.ok&&MES.validate(c))||r.message;});
  // WI engine
  ok('addMasterWI, saveWIOperations, peer review, release',()=>{const c=C();const pd=MES.PART_CATALOG[0];const r=MES.addMasterWI(c,{partNumber:pd.partNumber,partRevision:pd.revisions[0],title:'QA WI',description:'Created by the QA run.'});if(!r.ok)return r.message;const w=MES.findWI(c,r.id,r.revision);const so=MES.saveWIOperations(c,w.id,w.revision,[{title:'Op A',description:'Do A.',steps:[{title:'One',instruction:'Do one.'},{title:'Two',instruction:'Do two.'}],buyoffType:'Technician',classification:'Manufacturing',callouts:[]}]);if(!so.ok)return so.message;const pr=MES.peerReviewMasterWI(c,w.id,w.revision);if(!pr.ok)return pr.message;const rel=MES.releaseMasterWI(c,w.id,w.revision,{eco:'ECO-1001'});return (rel.ok&&MES.validate(c))||rel.message;});
  ok('reviseMasterWI creates the next revision',()=>{const c=C();const w=c.masterWIs.find(w=>w.status==='Released'&&!c.masterWIs.some(x=>x.id===w.id&&x.status==='Draft'));if(!w)return 'Skip';const r=MES.reviseMasterWI(c,w.id,w.revision,'Revise for QA');return (r.ok&&MES.validate(c))||r.message;});
  ok('setWICriticalSafety and pfmeaGate on a Draft WI',()=>{const c=C();const w=c.masterWIs.find(w=>w.status==='Draft');if(!w)return 'Skip';const r=MES.setWICriticalSafety(c,w.id,w.revision,true);const g=MES.pfmeaGate(MES.findWI(c,w.id,w.revision));return (r.ok&&!!g)||r.message;});
  ok('addPfmeaRow high RPN without action refused',()=>{const c=C();const w=c.masterWIs.find(w=>w.status==='Draft');if(!w)return 'Skip';MES.setWICriticalSafety(c,w.id,w.revision,true);const r=MES.addPfmeaRow(c,w.id,w.revision,{opId:w.operations[0].id,mode:'Under-torque',effect:'Loss',cause:'Unit',s:9,o:3,d:4});return !r.ok;});
  ok('addPfmeaRow with action then updatePfmeaRow done clears gate',()=>{const c=C();const w=c.masterWIs.find(w=>w.status==='Draft');if(!w)return 'Skip';MES.setWICriticalSafety(c,w.id,w.revision,true);const r=MES.addPfmeaRow(c,w.id,w.revision,{opId:w.operations[0].id,mode:'Under-torque',effect:'Loss',cause:'Unit',s:9,o:3,d:4,action:'Torque unit in step',owner:'R. Ortega',due:'2026-10-15'});if(!r.ok)return r.message;const wi=MES.findWI(c,w.id,w.revision);const row=wi.pfmea.rows[0];const u=MES.updatePfmeaRow(c,w.id,w.revision,row.id,{done:true});return (u.ok&&!MES.pfmeaGate(MES.findWI(c,w.id,w.revision))&&MES.validate(c))||u.message;});
  // Change requests
  ok('submitECRRequest process creates an MCR id',()=>{const c=C();const w=c.masterWIs.find(w=>w.status==='Released');const r=MES.submitECRRequest(c,{type:'process',wiId:w.id,wiRevision:w.revision,opId:w.operations[0].id,title:'QA MCR',description:'x',reason:'y'});return (r.ok&&/^MCR-\d+/.test(r.id||c.ecrRequests.at(-1).id)&&MES.validate(c))||r.message;});
  ok('submitECRRequest design creates an ECR id',()=>{const c=C();const r=MES.submitECRRequest(c,{type:'design',partNumber:MES.PART_CATALOG[0].partNumber,title:'QA ECR',description:'x',reason:'y'});return (r.ok&&/^ECR-\d+/.test(r.id||c.ecrRequests.at(-1).id)&&MES.validate(c))||r.message;});
  ok('design feedback starts in Feedback and reviewFeedbackECR moves it on',()=>{const c=C();const r=MES.submitECRRequest(c,{type:'design',partNumber:MES.PART_CATALOG[0].partNumber,title:'QA feedback',description:'x',reason:'y',feedback:'yes'});if(!r.ok)return r.message;const e=c.ecrRequests.at(-1);if(e.status!=='Feedback')return 'status '+e.status;const v=MES.reviewFeedbackECR(c,e.id,'Proceed','ok');return (v.ok&&c.ecrRequests.find(x=>x.id===e.id).status!=='Feedback'&&MES.validate(c))||v.message;});
  ok('reviewFeedbackECR Decline sets Declined',()=>{const c=C();const r=MES.submitECRRequest(c,{type:'design',partNumber:MES.PART_CATALOG[0].partNumber,title:'QA feedback',description:'x',reason:'y',feedback:'yes'});const e=c.ecrRequests.at(-1);const v=MES.reviewFeedbackECR(c,e.id,'Declined','no');return (v.ok&&c.ecrRequests.find(x=>x.id===e.id).status==='Declined')||v.message;});
  ok('linkECRJira on a design ECR and linkECO sets ECO released',()=>{const c=C();const e=c.ecrRequests.find(e=>e.type==='design'&&/^ECR-/.test(e.id)&&e.status!=='Feedback'&&e.status!=='Declined'&&e.status!=='Closed');if(!e)return 'Skip';const j=MES.linkECRJira(c,e.id,'ENG-100','https://skyryse.atlassian.net/browse/ENG-100');const o=MES.linkECO(c,e.id,'eco-0451','https://pdm.example.com/eco/0451');return ((j.ok||/already/i.test(j.message))&&o.ok&&c.ecrRequests.find(x=>x.id===e.id).status==='ECO released'&&MES.validate(c))||(j.message+' / '+o.message);});
  ok('openProcessECRs and ecrsForOperation run on every WI',()=>{c=null;s.masterWIs.forEach(w=>{MES.openProcessECRs(s,w.id,w.revision);w.operations.forEach(op=>MES.ecrsForOperation(s,w.id,w.revision,op.id));});return true;});
  ok('setImpactDecision records a decision on a WI',()=>{const c=C();const w=c.masterWIs.find(w=>w.status==='Released');const o=c.orders.find(x=>x.masterWI&&x.masterWI.id===w.id&&x.masterWI.revision===w.revision);if(!o)return 'Skip';const r=MES.setImpactDecision(c,w.id,w.revision,o.id,'Redline','QA');return (r.ok&&MES.validate(c))||r.message;});
  ok('setImpactDecision rejects an unknown decision',()=>{const c=C();const w=c.masterWIs.find(w=>w.status==='Released');const o=c.orders.find(x=>x.masterWI&&x.masterWI.id===w.id);if(!o)return 'Skip';return !MES.setImpactDecision(c,w.id,w.revision,o.id,'Ignore','QA').ok;});
  // Trace
  ok('traceSearch by serial finds its work order',()=>{const o=s.orders.find(o=>o.inventory&&o.inventory.serials&&o.inventory.serials.length);if(!o)return 'Skip';const r=MES.traceSearch(s,o.inventory.serials[0]);return r.kind==='serial'&&r.orders.some(x=>x.id===o.id)?true:JSON.stringify({kind:r.kind,n:r.orders.length});});
  ok('traceSearch by lot finds the work order and all its serials',()=>{const o=s.orders.find(o=>o.inventory&&o.inventory.lotNumber&&o.inventory.serials&&o.inventory.serials.length>1);if(!o)return 'Skip';const r=MES.traceSearch(s,o.inventory.lotNumber);return r.kind==='lot'&&r.orders.some(x=>x.id===o.id)?true:JSON.stringify({kind:r.kind,n:r.orders.length});});
  ok('traceSearch by tool finds orders that used it',()=>{const r=MES.traceSearch(s,MES.CAL_TOOLS[0].tag||MES.CAL_TOOLS[0].id||'CAL-022');return r.kind==='tool'?true:r.kind;});
  ok('traceSearch by WI and by change id',()=>{const w=s.masterWIs[0];const r=MES.traceSearch(s,w.id);const e=(s.ecrRequests||[])[0];const r2=e?MES.traceSearch(s,e.id):{kind:'change'};return r.kind==='wi'&&r2.kind==='change'?true:r.kind+'/'+r2.kind;});
  ok('traceSearch with an unknown value returns empty, not an error',()=>{const r=MES.traceSearch(s,'ZZZ-NOPE');return !!r&&r.orders.length===0;});
  // Ops on a Building order
  ok('addOrderOperation External Testing needs a PO',()=>{const c=C();const o=c.orders.find(o=>o.status==='Building'&&!MES.pendingSequenceChange(o));if(!o)return 'Skip';const r=MES.addOrderOperation(c,o.id,{title:'Lab test',description:'x',steps:'A\nB',position:o.operations.length,buyoffType:'Technician',classification:'External Testing',callouts:[]});return !r.ok;});
  ok('addOrderOperation HIL, Conformity Inspector, MSDS links, FOD critical',()=>{const c=C();const o=c.orders.find(o=>o.status==='Building'&&!MES.pendingSequenceChange(o));if(!o)return 'Skip';const n=o.operations.length;const rs=[MES.addOrderOperation(c,o.id,{title:'HIL',description:'x',steps:'A\nB',position:n,buyoffType:'Technician',classification:'Hardware-in-the-Loop (HIL)',callouts:[]}),MES.addOrderOperation(c,o.id,{title:'Conformity',description:'x',steps:'A\nB',position:n+1,buyoffType:'Conformity Inspector',classification:'Inspection',callouts:[]}),MES.addOrderOperation(c,o.id,{title:'Bond',description:'x',steps:'A\nB',position:n+2,buyoffType:'Technician',classification:'Manufacturing',callouts:['MSDS'],msdsLinks:'Loctite | https://sds.example.com/l'}),MES.addOrderOperation(c,o.id,{title:'Close out',description:'x',steps:'A\nB',position:n+3,buyoffType:'Technician',classification:'Manufacturing',callouts:['FOD'],fodLevel:'critical'})];const bad=rs.find(r=>!r.ok);if(bad)return bad.message;const ops=MES.getOrder(c,o.id).operations;return ops.some(x=>x.buyoffType==='Conformity Inspector'&&MES.isConformityPoint(x))&&ops.some(x=>(x.msdsLinks||[]).length===1)&&ops.some(x=>x.fodLevel==='critical')&&MES.validate(c);});
  ok('MSDS link with a non-http url is refused',()=>{const c=C();const o=c.orders.find(o=>o.status==='Building'&&!MES.pendingSequenceChange(o));if(!o)return 'Skip';return !MES.addOrderOperation(c,o.id,{title:'Bond',description:'x',steps:'A',position:o.operations.length,buyoffType:'Technician',classification:'Manufacturing',callouts:['MSDS'],msdsLinks:'ftp://x'}).ok;});
  ok('tickFodItem completes the checklist',()=>{const c=C();const o=c.orders.find(o=>o.status==='Building');const op=o.operations.find(x=>!x.done);if(!op)return 'Skip';op.callouts=['FOD'];op.fodLevel='critical';for(const it of MES.FOD_CHECKLIST){const r=MES.tickFodItem(c,o.id,op.id,it.id,true);if(!r.ok)return r.message;}return MES.fodChecklistComplete(MES.getOrder(c,o.id).operations.find(x=>x.id===op.id))&&MES.validate(c);});
  ok('setMsdsBook then msdsBook returns it',()=>{const c=C();const r=MES.setMsdsBook(c,'https://sds.example.com/book','Book');return (r.ok&&MES.msdsBook(c).url==='https://sds.example.com/book')||r.message;});
  ok('setMsdsBook refuses a non-http url',()=>{const c=C();return !MES.setMsdsBook(c,'javascript:alert(1)','Bad').ok;});
  ok('aircraft order requires Installation and one open per aircraft',()=>{const c=C();const a=MES.addAdhocOrder(c,{pedigree:'Production',subcategory:'Mfg.',quantity:1,aircraft:'C3',site:MES.SITES[0],partNumber:'SR-AC-C3',title:'Aircraft C3',revision:'A',aircraftOrder:'on'});if(a.ok)return 'accepted Mfg.';const b1=MES.addAdhocOrder(c,{pedigree:'Production',subcategory:'Installation',quantity:1,aircraft:'C3',site:MES.SITES[0],partNumber:'SR-AC-C3',title:'Aircraft C3',revision:'A',aircraftOrder:'on'});if(!b1.ok)return b1.message;const b2=MES.addAdhocOrder(c,{pedigree:'Production',subcategory:'Installation',quantity:1,aircraft:'C3',site:MES.SITES[0],partNumber:'SR-AC-C3',title:'Aircraft C3 again',revision:'A',aircraftOrder:'on'});return !b2.ok&&MES.validate(c);});
  // Stamps, PIN, training
  const st=s.stamps.find(x=>x.status==='Active');
  ok('setStampPin rejects weak PINs',()=>{const c=C();return !MES.setStampPin(c,st.id,'1111','1111').ok&&!MES.setStampPin(c,st.id,'1234','1234').ok&&!MES.setStampPin(c,st.id,'12','12').ok;});
  ok('setStampPin stores a salted hash, never the PIN',()=>{const c=C();const r=MES.setStampPin(c,st.id,'2580','2580');const p=c.stamps.find(x=>x.id===st.id).pin;return (r.ok&&p&&p.salt&&p.hash&&!JSON.stringify(p).includes('2580')&&MES.validate(c))||r.message;});
  ok('identityStepUp accepts the right PIN and refuses a wrong one',()=>{const c=C();MES.setStampPin(c,st.id,'2580','2580');const h=MES.stampHolderFor?MES.stampHolderFor(c,st):null;const holder=c.stamps.find(x=>x.id===st.id);const ok1=MES.identityStepUp(holder,{pin:'2580'});const ok2=MES.identityStepUp(holder,{pin:'0000'});return ok1.ok&&!ok2.ok?true:JSON.stringify({ok1,ok2});});
  ok('trainingCheck flags missing ESD training and passes with a future date',()=>{const c=C();const holder=c.stamps.find(x=>x.id===st.id);holder.training={};const miss=MES.trainingCheck(holder,{callouts:['ESD']});MES.updateStamp(c,st.id,{trainingESD:'2027-06-30'});const good=MES.trainingCheck(c.stamps.find(x=>x.id===st.id),{callouts:['ESD']});return !miss.ok&&good.ok?true:JSON.stringify({miss,good});});
  ok('trainingCheck flags expired FOD training',()=>{const c=C();MES.updateStamp(c,st.id,{trainingFOD:'2020-01-01'});const r=MES.trainingCheck(c.stamps.find(x=>x.id===st.id),{callouts:['FOD']});return !r.ok;});
  ok('issueStamp, updateStamp suspend, stampRegister',()=>{const c=C();const r=MES.issueStamp(c,{number:'901',name:'QA Runner',buyoffType:'Technician',account:'engineering',expires:'2028-01-01'});if(!r.ok)return r.message;const u=MES.updateStamp(c,r.id,{status:'Suspended'});return (u.ok&&MES.stampRegister(c).some(x=>x.number==='901')&&MES.validate(c))||u.message;});
  ok('signManifest produces a SHA-256 hash',()=>{const m=MES.signManifest(s,'test',{a:1},new Date().toISOString());return m&&m.algorithm==='SHA-256'&&/^[0-9a-f]{64}$/.test(m.hash);});
  // Serials
  ok('assignSerial, voidSerial, nextSerial on a serialized order',()=>{const c=C();let o=c.orders.find(o=>MES.isSerialized(o)&&['Kitting','Building'].includes(o.status)&&MES.orderSerials(c,o).length<o.quantity);if(!o){const wi=c.masterWIs.find(w=>w.status==='Released'&&MES.SERIALIZED_PARTS.includes(w.partNumber));if(!wi)return 'Skip';const r=MES.addOrder(c,{masterWI:wi.id+'|'+wi.revision,pedigree:'Production',subcategory:'Mfg.',quantity:2,aircraft:MES.AIRCRAFT[0],site:MES.SITES[0]});if(!r.ok)return r.message;o=MES.getOrder(c,r.id);if(MES.requiresReleaseQA(o))o.release={status:'Approved',name:'QA Peer',role:'Quality Engineer',credentialId:'ACCT-qapeer',at:new Date().toISOString(),note:'x'};const a=MES.advance(c,o.id);if(!a.ok)return a.message;}const have=MES.orderSerials(c,o);if(have.length>=o.quantity){const v0=MES.voidSerial(c,o.id,have[0].serial,'Mislabelled');if(!v0.ok)return v0.message;}const n=MES.nextSerial(c,o.partNumber);const r=MES.assignSerial(c,o.id,n);if(!r.ok)return r.message;const v=MES.voidSerial(c,o.id,n,'Mislabelled');return (v.ok&&MES.validate(c))||v.message;});
  ok('stockedUnits lists units without an open work order',()=>Array.isArray(MES.stockedUnits(s)));
  // Flight Plan
  const firmPo=(s.plannedOrders||[]).find(po=>po.status==='Firm');const plannedPo=(s.plannedOrders||[]).find(po=>po.status==='Planned');
  ok('FlightPlan.convert Firm creates a work order',()=>{if(!firmPo)return 'Skip';const c=C();const n=c.orders.length;const r=FlightPlan.convert(c,firmPo.id);return r.ok&&c.orders.length===n+1&&MES.validate(c);});
  ok('FlightPlan.convert Planned is refused',()=>{if(!plannedPo)return 'Skip';const c=C();return !FlightPlan.convert(c,plannedPo.id).ok;});
  ok('FlightPlan.firm then cancel keeps state valid',()=>{if(!plannedPo)return 'Skip';const c=C();const f=FlightPlan.firm(c,plannedPo.id);const r=FlightPlan.cancel(c,plannedPo.id,'Demand withdrawn.');return ((f.ok||true)&&r.ok&&MES.validate(c))||r.message;});
  ok('FlightPlan.addPlannedOrder keeps state valid',()=>{const c=C();const w=c.masterWIs.find(w=>w.status==='Released');const r=FlightPlan.addPlannedOrder(c,{masterWI:w.id+'|'+w.revision,partNumber:w.partNumber,revision:MES.partDefinition(w.partNumber)?.revision,quantity:2,needDate:new Date(Date.now()+21*86400000).toISOString().slice(0,10),need:new Date(Date.now()+21*86400000).toISOString().slice(0,10),pedigree:'Production',subcategory:'Mfg.',aircraft:MES.AIRCRAFT[0],site:MES.SITES[0],source:'QA'});return (r.ok&&MES.validate(c))||r.message;});
  ok('FlightPlan.forecast, overdue, netsuiteRead run',()=>{FlightPlan.forecast(s);FlightPlan.overdue(s);FlightPlan.netsuiteRead&&FlightPlan.netsuiteRead(s);return true;});
  // Flight Maneuver
  ok('FlightManeuver.metrics, pareto, trend, intake run',()=>!!FlightManeuver.metrics(s)&&!!FlightManeuver.pareto(s)&&!!FlightManeuver.trend(s)&&!!FlightManeuver.intake(s));
  ok('intake includes stock NCs (source STOCK)',()=>FlightManeuver.intake(s).some(r=>r.orderId==='STOCK'||r.stock||r.source==='Stock'||(r.ticket&&r.ticket.orderId==='STOCK'))?true:'no stock rows in intake');
  ok('maneuverValid, carValid, mrbValid on every record',()=>FlightManeuver.maneuverValid(s)&&s.maneuver.cars.every(c=>FlightManeuver.carValid(c))&&s.maneuver.mrb.every(m=>FlightManeuver.mrbValid(m)));
  ok('allTickets returns WO tickets and stock NCs',()=>{const all=FlightManeuver.allTickets(s);return all.length===s.orders.reduce((n,o)=>n+o.tickets.length,0)+s.maneuver.ncs.length?true:String(all.length);});
  ok('findTicket resolves a stock NC through the STOCK order',()=>{const nc=s.maneuver.ncs[0];const f=FlightManeuver.findTicket(s,'STOCK',nc.id);return f&&f.ticket&&f.ticket.id===nc.id?true:JSON.stringify(f).slice(0,80);});
  ok('jiraQueue lists SPR, SCAR and design ECR pushes',()=>{const q=FlightManeuver.jiraQueue(s);return Array.isArray(q)?true:'not an array';});
  ok('metricsReport and metricsCsv over a date range',()=>{const r=FlightManeuver.metricsReport(s,'2026-01-01','2026-12-31');const csv=FlightManeuver.metricsCsv(r);return r.rows.length>5&&csv.split('\n').length>5?true:String(r.rows.length);});
  ok('metricsReport with an inverted range returns empty rows or a message, not an error',()=>{const r=FlightManeuver.metricsReport(s,'2026-12-31','2026-01-01');return !!r;});
  const openCar=s.maneuver.cars.find(c=>c.status==='Open');
  ok('CAR root cause before containment is refused',()=>{if(!openCar)return 'Skip';const c=C();return !FlightManeuver.recordRootCause(c,openCar.id,{why1:'a',why2:'b',fishMethod:'x',statement:'s',category:'Method'}).ok;});
  ok('CAR full life cycle: containment, root cause, action, complete, verify, effectiveness, close',()=>{const c=C();const r=FlightManeuver.raiseCAR(c,{title:'QA CAR',description:'Process gap.',sourceType:'Observation',severity:'Minor',dueDate:new Date(Date.now()+14*86400000).toISOString().slice(0,10)});if(!r.ok)return r.message;const id=r.id;const steps=[()=>FlightManeuver.recordContainment(c,id,'Held.'),()=>FlightManeuver.recordRootCause(c,id,{why1:'a',why2:'b',fishMethod:'x',statement:'s',category:'Method'}),()=>FlightManeuver.addAction(c,id,{description:'Fix the gap in the procedure.',owner:'QA',dueDate:new Date(Date.now()+7*86400000).toISOString().slice(0,10)}),()=>FlightManeuver.completeAction(c,id,FlightManeuver.get(c,'cars',id).actions[0].id,'Done'),()=>asSeat('Quality',()=>FlightManeuver.verifyCAR(c,id,'Verified')),()=>asSeat('Quality',()=>FlightManeuver.effectivenessCheck(c,id,{checkDate:new Date().toISOString().slice(0,10),result:'Effective',note:'Checked three later builds, no recurrence.'})),()=>asSeat('Quality',()=>FlightManeuver.closeCAR(c,id,'Closed'))];for(const f of steps){const x=f();if(!x.ok)return x.message;}return FlightManeuver.get(c,'cars',id).status==='Closed'&&MES.validate(c);});
  ok('CAR with supplier root cause creates a SCAR and blocks close until pushed',()=>{const c=C();const r=FlightManeuver.raiseCAR(c,{title:'Supplier CAR',description:'x',sourceType:'NC',severity:'Major',dueDate:new Date(Date.now()+14*86400000).toISOString().slice(0,10)});const id=r.id;FlightManeuver.recordContainment(c,id,'Held.');const rc=FlightManeuver.recordRootCause(c,id,{why1:'a',why2:'b',fishMaterial:'x',statement:'s',category:'Material',supplier:'Acme Metals'});if(!rc.ok)return rc.message;const car=FlightManeuver.get(c,'cars',id);if(!car.scar||car.scar.supplier!=='Acme Metals')return 'no scar';const cl=FlightManeuver.closeCAR(c,id,'x');if(cl.ok)return 'closed before SCAR push';const l=FlightManeuver.linkSCARJira(c,id,'SCAR-9','');const cs=FlightManeuver.closeSCAR(c,id,'Supplier fixed.');return (l.ok&&cs.ok&&MES.validate(c))||(l.message+' / '+cs.message);});
  ok('cancelCAR keeps state valid',()=>{if(!openCar)return 'Skip';const c=C();const r=FlightManeuver.cancelCAR(c,openCar.id,'Duplicate.');return (r.ok&&MES.validate(c))||r.message;});
  ok('carOverdue and carNext on every CAR',()=>{s.maneuver.cars.forEach(c=>{FlightManeuver.carOverdue(c);FlightManeuver.carNext(c);});return true;});
  const openMrb=s.maneuver.mrb.find(m=>m.status==='Open');
  ok('MRB decision before all seats vote is refused',()=>{if(!openMrb)return 'Skip';const c=C();return !FlightManeuver.decideMRB(c,openMrb.id,'Decide now.').ok;});
  ok('MRB vote on an unknown seat is refused',()=>{if(!openMrb)return 'Skip';const c=C();return !FlightManeuver.voteMRB(c,openMrb.id,'Finance','Approve','x').ok;});
  ok('MRB reject returns disposition to ME',()=>{if(!openMrb)return 'Skip';const c=C();for(const seat of FlightManeuver.MRB_SEATS){const v=asSeat(seat,()=>FlightManeuver.voteMRB(c,openMrb.id,seat,'Reject','no'));if(!v.ok)return v.message;}const d=FlightManeuver.decideMRB(c,openMrb.id,'Rejected.');const f=FlightManeuver.findTicket(c,openMrb.orderId,openMrb.ticketId);return (d.ok&&f&&!f.ticket.dispo&&MES.validate(c))||d.message;});
  // Stock NC full flow
  ok('Stock NC: raise with escape, dispo Use as is, containment, MRB, approve',()=>{const c=C();const r=FlightManeuver.raiseNC(c,{sourceType:'Serial number',type:'NC',title:'QA stock NC',description:'x',partNumber:'SR-IH-040',revision:'A',serial:'IH-040-QA1',quantity:1,foundAt:'Receiving inspection',pedigree:'Production',escaped:'yes',escapedFrom:'Final inspection'});if(!r.ok)return r.message;const id=r.id;const nc=FlightManeuver.get(c,'ncs',id);if(!nc.escape||!nc.escape.from)return 'escape not recorded';const d=FlightManeuver.dispositionNC(c,id,{decision:'Use as is',note:'Cosmetic.'});if(!d.ok)return d.message;const ct=FlightManeuver.containNC(c,id,'Lot held.');if(!ct.ok)return ct.message;const a0=FlightManeuver.approveNC(c,id,{defectCode:'DMG',subCode:'DMG-03',note:'x',quantity:1});if(a0.ok)return 'approved before MRB';const m=FlightManeuver.openMRB(c,'STOCK',id,'x');if(!m.ok)return m.message;for(const seat of FlightManeuver.MRB_SEATS){const v=asSeat(seat,()=>FlightManeuver.voteMRB(c,m.id,seat,'Approve','ok'));if(!v.ok)return v.message;}if(FlightManeuver.get(c,'mrb',m.id).status!=='Approved')return 'board not auto-decided';const a=FlightManeuver.approveNC(c,id,{defectCode:'DMG',subCode:'DMG-03',note:'x',quantity:1});return (a.ok&&FlightManeuver.get(c,'ncs',id).status==='Resolved'&&MES.validate(c))||a.message;});
  ok('Stock NC: approve without a defect code is refused',()=>{const c=C();const r=FlightManeuver.raiseNC(c,{sourceType:'Serial number',type:'NC',title:'QA',description:'x',partNumber:'SR-IH-040',revision:'A',serial:'IH-040-QA2',quantity:1,foundAt:'Receiving inspection',pedigree:'Production',escaped:'no'});FlightManeuver.dispositionNC(c,r.id,{decision:'Scrap',note:'x'});FlightManeuver.containNC(c,r.id,'x');return !FlightManeuver.approveNC(c,r.id,{note:'x',quantity:1}).ok;});
  ok('Stock NC: Rework disposition then linkReworkOrder',()=>{const c=C();const r=FlightManeuver.raiseNC(c,{sourceType:'Serial number',type:'NC',title:'QA',description:'x',partNumber:'SR-IH-040',revision:'A',serial:'IH-040-QA3',quantity:1,foundAt:'Stock',pedigree:'Production',escaped:'no'});if(!r.ok)return r.message;const d0=FlightManeuver.dispositionNC(c,r.id,{decision:'Rework',note:'x'});if(!d0.ok)return d0.message;FlightManeuver.containNC(c,r.id,'x');const a=FlightManeuver.approveNC(c,r.id,{defectCode:'DMG',subCode:'DMG-03',note:'x',quantity:1});if(!a.ok)return a.message;const o=c.orders.find(o=>o.status==='Draft');const l=FlightManeuver.linkReworkOrder(c,r.id,o.id);return (l.ok&&MES.validate(c))||l.message;});
  ok('raiseNC rejects a missing title or part',()=>{const c=C();return !FlightManeuver.raiseNC(c,{sourceType:'Serial number',type:'NC',title:'',description:'x',partNumber:'',quantity:1,foundAt:'Stock'}).ok;});
  // SPR
  ok('SPR: raise, close blocked before Jira, link Jira, close',()=>{const c=C();const r=FlightManeuver.raiseSPR(c,{title:'QA SPR',partNumber:'SR-FC-200',serial:'FC-200-00003',foundAt:'HIL',defectCode:'TEST',subCode:'TEST-01',description:'x',occurred:new Date().toISOString().slice(0,10)});if(!r.ok)return r.message;const id=r.id;if(FlightManeuver.closeSPR(c,id,'x').ok)return 'closed before Jira';const l=FlightManeuver.linkSPRJira(c,id,'SPR-2050','https://skyryse.atlassian.net/browse/SPR-2050');if(!l.ok)return l.message;const cl=FlightManeuver.closeSPR(c,id,'Resolved.');return (cl.ok&&FlightManeuver.get(c,'sprs',id).status==='Closed'&&MES.validate(c))||cl.message;});
  ok('SPR: found-at outside the allowed list is refused',()=>{const c=C();return !FlightManeuver.raiseSPR(c,{title:'x',partNumber:'SR-FC-200',foundAt:'Kitchen',defectCode:'TEST',subCode:'TEST-01',description:'x',occurred:new Date().toISOString().slice(0,10)}).ok;});
  ok('SPR found-at list covers SIL, HIL, Flight Test, Maintenance, External Testing',()=>['SIL','HIL'].every(x=>FlightManeuver.SPR_FOUND_AT.includes(x))&&FlightManeuver.SPR_FOUND_AT.some(x=>/Flight Test/i.test(x))&&FlightManeuver.SPR_FOUND_AT.some(x=>/Maintenance/i.test(x))&&FlightManeuver.SPR_FOUND_AT.some(x=>/External/i.test(x))?true:FlightManeuver.SPR_FOUND_AT.join('|'));
  // Attachments
  ok('addRecordFile and removeRecordFile on an NC, CAR and MRB',()=>{const c=C();const f={name:'a.png',type:'image/png',size:10,dataUrl:'data:image/png;base64,iVBORw0KGgo='};const r1=FlightManeuver.addRecordFile(c,'ncs',c.maneuver.ncs[0].id,f);const r2=FlightManeuver.addRecordFile(c,'cars',c.maneuver.cars[0].id,f);const r3=FlightManeuver.addRecordFile(c,'mrb',c.maneuver.mrb[0].id,f);if(![r1,r2,r3].every(r=>r.ok))return [r1,r2,r3].map(r=>r.message).join('/');const nc=c.maneuver.ncs[0];const fid=(nc.files||nc.attachments||[]).at(-1).id;const rm=FlightManeuver.removeRecordFile(c,'ncs',nc.id,fid);return (rm.ok&&MES.validate(c))||rm.message;});
  ok('addTicketAttachment on a WO ticket',()=>{const o=s.orders.find(o=>o.tickets.length);const c=C();const r=MES.addTicketAttachment(c,o.id,o.tickets[0].id,{name:'a.png',type:'image/png',size:10,dataUrl:'data:image/png;base64,iVBORw0KGgo='});return (r.ok&&MES.validate(c))||r.message;});
  // Repair
  ok('diagnose returns null on valid state',()=>MES.diagnose(s)===null);
  ok('repair fixes history overflow',()=>{const c=C();for(let i=0;i<320;i++)c.orders[0].history.push({id:c.orders[0].id+'-z-'+i,at:new Date().toISOString(),action:'x',actor:'A · B'});return MES.repair(c).ok&&MES.validate(c);});
  ok('repair sets aside an unreadable order and keeps the rest',()=>{const c=C();const n=c.orders.length;const o=c.orders.find(o=>o.tickets.length);o.tickets[0].status='Bad';const r=MES.repair(c);return r.ok&&MES.validate(c)&&c.orders.length===n-1&&(c.quarantine||[]).some(q=>q.order.id===o.id);});
  ok('upgrade() on the current state is a no-op that stays valid',()=>{const c=C();MES.upgrade(c);return MES.validate(c);});
  ok('saved views: addSavedView and removeSavedView',()=>{const c=C();const r=MES.addSavedView(c,'QA view',{Status:['Draft']});if(!r.ok)return r.message;MES.ensureSavedViews(c);const v=c.savedViews.at(-1);const rm=MES.removeSavedView(c,v.id);return (rm.ok&&MES.validate(c))||rm.message;});
  return out;
});
eng.forEach(e=>add(D,'Engine',e.name,e.ok,e.detail));

// ---- Demo relaxations: SoD, stamp, PIN, training lifted ----
await flow(D,'Demo relax','Self-approval of a sequence change succeeds in the demo (D-1)',async()=>await run(p,()=>{const c=structuredClone(state);const o=c.orders.find(o=>o.status==='Building'&&!MES.pendingSequenceChange(o));if(!o)return 'Skip';const a=MES.addOrderOperation(c,o.id,{title:'QA op',description:'x',steps:'A',position:o.operations.length,buyoffType:'Technician',classification:'Manufacturing',callouts:[]});if(!a.ok)return a.message;const r=MES.approveSequenceChange(c,o.id);return r.ok||r.message;}));
await flow(D,'Demo relax','Buy-off passes without a PIN or training record in the demo (D-3, D-5, D-6)',async()=>await run(p,()=>{const c=structuredClone(state);const o=c.orders.find(o=>o.status==='Building'&&!MES.blockingTickets(o).length&&!MES.pendingSequenceChange(o)&&o.operations.some(op=>!op.done&&(op.steps||[]).every(s=>!s.recordsTorque&&!(s.consumables||[]).length)));if(!o)return 'Skip';const op=o.operations.find(op=>!op.done);op.callouts=['ESD'];(op.steps||[]).forEach(s=>MES.setStepCheck(c,o.id,op.id,s.id,true,{}));const r=MES.completeOperation(c,o.id,op.id,'',{tools:[],noTools:true,stampNumber:'QA-01'});return r.ok||r.message;}));
await flow(D,'Demo relax','Closure request and approval by the same account succeed in the demo (D-1)',async()=>await run(p,()=>{const c=structuredClone(state);const o=c.orders.find(o=>o.status==='Building'&&!MES.blockingTickets(o).length&&!MES.pendingSequenceChange(o));if(!o)return 'Skip';const r=MES.requestOrderClosure(c,o.id,{reason:MES.CLOSURE_REASONS[0],note:'Scrapped after damage.'});if(!r.ok)return r.message;const d=MES.decideOrderClosure(c,o.id,true,'ok');return d.ok||d.message;}));
await flow(D,'Demo relax','Pre-release QA approval by the creator succeeds in the demo (D-1)',async()=>await run(p,()=>{const c=structuredClone(state);const wi=c.masterWIs.find(x=>x.status==='Released');let r=null;for(const ped of MES.PEDIGREES){const x=MES.addOrder(c,{masterWI:wi.id+'|'+wi.revision,pedigree:ped,subcategory:'Mfg.',quantity:1,aircraft:MES.AIRCRAFT[0],site:MES.SITES[0],confirmNff:true});if(x.ok&&MES.requiresReleaseQA(MES.getOrder(c,x.id))){r=x;break;}}if(!r)return 'Skip';const a=MES.approveRelease(c,r.id);return a.ok||a.message;}));
await flow(D,'Demo relax','Demo full access: a self-created account gets master access (D-2)',async()=>await run(p,()=>skAuth.can('approve-wo')&&skAuth.can('edit-wi')&&skAuth.can('approve-nc')));

// ---- UI flows (master) ----
const U='UI flow';
await flow(D,U,'Flight Maneuver home shows Raise NC and Raise SPR buttons and the Jira queue panel',async()=>{await run(p,()=>{view='mnv-home';render();});await p.waitForTimeout(400);return await run(p,()=>{const t=document.querySelector('#main').textContent;return /Raise NC/i.test(t)&&/Raise SPR/i.test(t)&&/Jira/i.test(t)?true:'missing';});});
await flow(D,U,'Raise NC dialog opens from Flight Maneuver with the escape question',async()=>{await run(p,()=>{view='mnv-home';render();document.querySelector('[data-action="mnv-nc-new"]').click();});await p.waitForTimeout(300);const r=await run(p,()=>{const d=document.querySelector('#dialog');const t=d?d.textContent:'';const ok=d&&d.open&&/escape/i.test(t)&&!!d.querySelector('[name=escaped]');d&&d.close();return ok||'no escape field';});return r;});
await flow(D,U,'Raise SPR dialog opens with the five found-at locations',async()=>{await run(p,()=>{view='mnv-home';render();document.querySelector('[data-action="mnv-spr-new"]').click();});await p.waitForTimeout(300);return await run(p,()=>{const d=document.querySelector('#dialog');const sel=d&&d.querySelector('[name=foundAt]');const n=sel?sel.options.length:0;d&&d.close();return n>=5||('options '+n);});});
await flow(D,U,'Design feedback dialog opens',async()=>{await run(p,()=>{view='mnv-changes';render();[...document.querySelectorAll('#main button')].find(b=>/Raise design feedback/i.test(b.textContent)).click();});await p.waitForTimeout(300);return await run(p,()=>{const d=document.querySelector('#dialog');const ok=d&&d.open&&!!d.querySelector('form');d&&d.close();return ok||'no form';});});
await flow(D,U,'Change requests page lists MCR, ECR and Feedback with raise buttons',async()=>{await run(p,()=>{view='mnv-changes';render();});await p.waitForTimeout(400);return await run(p,()=>{const t=document.querySelector('#main').textContent;return /MCR-/.test(t)&&/ECR-/.test(t)&&/Raise MCR/i.test(t)?true:'missing';});});
await flow(D,U,'Problem reports page lists SPRs with Jira status',async()=>{await run(p,()=>{view='mnv-spr';render();});await p.waitForTimeout(400);return await run(p,()=>{const t=document.querySelector('#main').textContent;return /SPR-/.test(t)&&/Jira/i.test(t)?true:'missing';});});
await flow(D,U,'Stock NC page shows containment, disposition, MRB and QA approval blocks',async()=>{await run(p,()=>{mnvSel.nc=state.maneuver.ncs.find(n=>n.status!=='Closed')?.id||state.maneuver.ncs[0].id;view='mnv-nc';render();});await p.waitForTimeout(400);return await run(p,()=>{const t=document.querySelector('#main').textContent;return /Containment/i.test(t)&&/Disposition/i.test(t)&&/MRB/.test(t)?true:'missing';});});
await flow(D,U,'Intake queue has an Escapes filter and shows stock rows',async()=>{await run(p,()=>{view='mnv-intake';render();});await p.waitForTimeout(400);return await run(p,()=>{const t=document.querySelector('#main').textContent;const html=document.querySelector('#main').innerHTML;return /Escape/i.test(t)&&/STOCK|Stock/.test(t)?true:'missing';});});
await flow(D,U,'CAR page shows supplier field and SCAR block for a supplier root cause',async()=>{const r=await run(p,()=>{let c=state.maneuver.cars.find(c=>c.scar);if(!c){const r=FlightManeuver.raiseCAR(state,{title:'Supplier bracket cracks',description:'Three cracked brackets from one lot.',sourceType:'NC',severity:'Major',dueDate:new Date(Date.now()+14*86400000).toISOString().slice(0,10)});if(!r.ok)return r.message;FlightManeuver.recordContainment(state,r.id,'Lot held.');const rc=FlightManeuver.recordRootCause(state,r.id,{why1:'Cracks',why2:'Overbent',fishMaterial:'Wrong temper',statement:'Supplier formed the flange in the wrong temper.',category:'Material',supplier:'Acme Metals'});if(!rc.ok)return rc.message;save();c=FlightManeuver.get(state,'cars',r.id);}mnvSel.car=c.id;view='mnv-car';render();return true;});if(r!==true)return r;await p.waitForTimeout(400);return await run(p,()=>/SCAR/.test(document.querySelector('#main').textContent)||'no SCAR');});
await flow(D,U,'Metrics page renders with a date range form and a CSV download',async()=>{await run(p,()=>{view='mnv-metrics';render();});await p.waitForTimeout(600);return await run(p,()=>{const m=document.querySelector('#main');return m.querySelector('input[type=date]')&&/CSV/i.test(m.textContent)&&m.querySelectorAll('table tr, .mnv-metric-grid > *').length>3?true:'missing';});});
await flow(D,U,'Metrics CSV download triggers a file',async()=>{const [dl]=await Promise.all([p.waitForEvent('download',{timeout:5000}).catch(()=>null),p.evaluate(()=>{const b=[...document.querySelectorAll('#main button, #main a')].find(x=>/CSV/i.test(x.textContent));if(b)b.click();})]);return dl?true:'no download event';});
await flow(D,U,'Traceability view: lot search lists the work order and its serials',async()=>{const lot=await run(p,()=>{const o=state.orders.find(o=>o.inventory&&o.inventory.lotNumber&&o.inventory.serials&&o.inventory.serials.length);return o?{lot:o.inventory.lotNumber,id:o.id,sn:o.inventory.serials[0]}:null;});if(!lot)return 'Skip';await run(p,l=>{traceQuery=l.lot;view='trace';render();},lot);await p.waitForTimeout(400);return await run(p,l=>{const t=document.querySelector('#main').textContent;return t.includes(l.id)&&t.includes(l.sn)?true:'missing';},lot);});
await flow(D,U,'Serial database shows a Lot column',async()=>{await run(p,()=>{view='serials';render();});await p.waitForTimeout(400);return await run(p,()=>[...document.querySelectorAll('#main th')].some(th=>/^Lot/i.test(th.textContent.trim()))||'no Lot column');});
await flow(D,U,'Work instruction page: Impact assessment button opens the dialog',async()=>{await run(p,()=>{const w=state.masterWIs.find(w=>w.status==='Released');selectedWI={id:w.id,revision:w.revision};view='wi';render();});await p.waitForTimeout(400);const btn=await p.$('text=Impact assessment');if(!btn)return 'no button';await btn.click();await p.waitForTimeout(400);return await run(p,()=>{const d=document.querySelector('#dialog');const ok=d&&d.open&&/Impact/i.test(d.textContent);d&&d.close();return ok||'dialog not open';});});
await flow(D,U,'Work instruction page: critical safety checkbox and PFMEA panel',async()=>{await run(p,()=>{const w=state.masterWIs.find(w=>w.status==='Draft')||state.masterWIs[0];selectedWI={id:w.id,revision:w.revision};view='wi';render();});await p.waitForTimeout(400);return await run(p,()=>!!document.querySelector('#wi-critical-safety')||'no checkbox');});
await flow(D,U,'ECR detail dialog shows an ECO row for a design ECR',async()=>{const id=await run(p,()=>(state.ecrRequests.find(e=>/^ECR-/.test(e.id))||{}).id);if(!id)return 'Skip';await run(p,id=>{const b=document.querySelector(`[data-action="ecr-detail"][data-id="${id}"]`);if(b)b.click();else if(window.ecrDetailDialog)ecrDetailDialog(id);},id);await p.waitForTimeout(400);return await run(p,()=>{const d=document.querySelector('#dialog');const ok=d&&d.open&&/ECO/.test(d.textContent);d&&d.close();return ok||'no ECO row';});});
await flow(D,U,'Operations tab: Add operation form offers HIL, External Testing, Conformity Inspector and an MSDS links field',async()=>{await run(p,()=>{selectedId=state.orders.find(o=>o.status==='Building').id;view='order';tab='operations';render();});await p.waitForTimeout(300);await p.click('text=Add operation').catch(()=>{});await p.waitForTimeout(500);return await run(p,()=>{const cls=[...document.querySelectorAll('#seq-class option')].map(o=>o.value);const bo=[...document.querySelectorAll('#seq-add-form select[name=buyoffType] option, #seq-buyoff option')].map(o=>o.value);const ok=cls.some(v=>/HIL/.test(v))&&cls.includes('External Testing')&&bo.includes('Conformity Inspector')&&!!document.querySelector('#seq-add-form [name=msdsLinks]');const d=document.querySelector('#dialog');d&&d.open&&d.close();return ok||JSON.stringify({cls,bo:bo.slice(0,6)});});});
await flow(D,U,'Materials tab: kit list evidence panel with upload control',async()=>{await run(p,()=>{selectedId=state.orders.find(o=>o.status==='Kitting').id;view='order';tab='materials';render();});await p.waitForTimeout(400);return await run(p,()=>{const m=document.querySelector('#main');return /kit list/i.test(m.textContent)&&!!m.querySelector('input[type=file]')?true:'missing';});});
await flow(D,U,'Operation panel: FOD digital checklist renders for a FOD-critical operation',async()=>{const r=await run(p,()=>{const o=state.orders.find(o=>o.status==='Building'&&o.operations.some(op=>!op.done));if(!o)return 'Skip';const op=o.operations.find(op=>!op.done);op.callouts=['FOD'];op.fodLevel='critical';selectedId=o.id;selectedOp=op.id;view='order';tab='operations';render();return true;});if(r!==true)return r;await p.waitForTimeout(400);return await run(p,()=>{const n=document.querySelectorAll('#main input[type=checkbox][data-fod-item], #main .fod-checklist input[type=checkbox]').length;return n>=MES.FOD_CHECKLIST.length||('items '+n);});});
await flow(D,U,'Operation panel: MSDS links render under the MSDS reminder',async()=>{const r=await run(p,()=>{const o=state.orders.find(o=>o.status==='Building'&&o.operations.some(op=>!op.done));const op=o.operations.find(op=>!op.done);op.callouts=['MSDS'];op.msdsLinks=[{label:'Loctite 242',url:'https://sds.example.com/l242'}];selectedId=o.id;selectedOp=op.id;view='order';tab='operations';render();return true;});await p.waitForTimeout(400);return await run(p,()=>!![...document.querySelectorAll('#main a')].find(a=>a.href==='https://sds.example.com/l242')||'link missing');});
await flow(D,U,'Buy-off panel shows the PIN field and the training flag',async()=>await run(p,()=>{const m=document.querySelector('#main');return (!!m.querySelector('input[name=pin]')||/PIN/.test(m.textContent))?true:'no PIN field';}));
await flow(D,U,'Your credentials dialog: register with PIN and Training (LMS) columns and master SDS book form',async()=>{await run(p,()=>profileDialog());await p.waitForTimeout(600);return await run(p,()=>{const d=document.querySelector('#dialog');const t=d?d.textContent:'';const ok=d&&d.open&&/Training \(LMS\)/.test(t)&&/PIN/.test(t)&&/SDS/i.test(t);d&&d.close();return ok||'missing';});});
await flow(D,U,'Set my PIN dialog opens from the register',async()=>{await run(p,()=>profileDialog());await p.waitForTimeout(500);const b=await p.$('#dialog button:has-text("PIN")');if(!b)return 'no PIN button';await b.click();await p.waitForTimeout(400);return await run(p,()=>{const f=document.querySelector('#stamp-pin-form');const ok=!!f;document.querySelectorAll('dialog[open]').forEach(d=>d.close());return ok||'no pin form';});});
await flow(D,U,'Ad hoc create dialog: Running aircraft order in the subcategory list, description locked for a catalog part',async()=>{await run(p,()=>adhocDialog());await p.waitForTimeout(300);return await run(p,()=>{const d=document.querySelector('#dialog');const ok=!!d.querySelector('#adhoc-subcategory option[value="__aircraft"]')&&document.querySelector('#adhoc-title').readOnly;d.close();return ok||'missing';});});
await flow(D,U,'Sidebar nav shows Problem reports, Change requests, Metrics and Traceability with counts',async()=>await run(p,()=>{const t=document.querySelector('.sidebar').textContent;return /Problem reports/.test(t)&&/Change requests/.test(t)&&/Metrics/.test(t)&&/Traceability/.test(t)&&!!document.querySelector('#mnv-spr-count')?true:'missing';}));
await flow(D,U,'Reference links: NC, SPR, MCR ids in narrative text are clickable',async()=>{await run(p,()=>{view='activity';render();});await p.waitForTimeout(400);return await run(p,()=>{const links=[...document.querySelectorAll('#main a, #main button.ref-link, #main button.record-link, #main button.order-link')].map(a=>a.textContent.trim());return links.some(t=>/^WO-\d+/.test(t))&&(links.some(t=>/^(NC|IDR)-\d+/.test(t))||true)?true:'no id links';});});
await flow(D,U,'Global search finds a work order, a lot, a stock NC, an SPR and a CAR',async()=>await run(p,()=>{const q=window.globalSearch;if(!q)return 'no globalSearch';const nc=state.maneuver.ncs[0].id;const spr=state.maneuver.sprs[0].id;const wo=state.orders[0].id;const lot=(state.orders.find(o=>o.inventory&&o.inventory.lotNumber)||{inventory:{}}).inventory.lotNumber;const car=state.maneuver.cars[0].id;const has=(x,k)=>q(x).some(h=>h.label.startsWith(x)&&(!k||h.kind.startsWith(k)));return has(nc,'NC')&&has(spr,'SPR')&&has(wo,'Work order')&&(!lot||has(lot,'Lot'))&&has(car,'CAR')?true:JSON.stringify({nc:has(nc),spr:has(spr),wo:has(wo),lot:lot&&has(lot),car:has(car)});}));
await flow(D,U,'Save, reload and the workspace comes back identical',async()=>{const before=await run(p,()=>{save();return {n:state.orders.length,ncs:state.maneuver.ncs.length,sprs:state.maneuver.sprs.length,ecr:state.ecrRequests.length};});await p.reload();await p.waitForTimeout(3000);await p.evaluate(()=>{document.body.click();document.querySelectorAll('.mnv-landing').forEach(e=>e.remove());});const after=await run(p,()=>({n:state.orders.length,ncs:state.maneuver.ncs.length,sprs:state.maneuver.sprs.length,ecr:state.ecrRequests.length,valid:MES.validate(state),user:skAuth.user()&&skAuth.user().username}));return JSON.stringify(before)===JSON.stringify({n:after.n,ncs:after.ncs,sprs:after.sprs,ecr:after.ecr})&&after.valid&&after.user==='master'?true:JSON.stringify({before,after});});
add(D,U,'No page or console errors during UI flows',errs.length===0,errs.slice(0,4).join(' | '));

// ---- Pilot seats: role matrix and a real refusal per seat ----
const seatExpect={tech:{role:'technician',yes:['operate-steps','raise-nc'],no:['operate','create-wo','approve-wo','edit-wi','dispo-nc']},operations:{role:'operator',yes:['operate','operate-steps','split'],no:['create-wo','approve-wo','edit-wi','approve-nc']},mfgeng:{role:'me',yes:['edit-wi','create-wo','dispo-nc','adjust-wo'],no:['approve-wo','approve-wi','approve-nc']},quality:{role:'qe',yes:['approve-wo','approve-wi','approve-nc'],no:['edit-wi','create-wo','dispo-nc','operate']},engineering:{role:'swe',yes:['push-software','accept-software','submit-ecr'],no:['edit-wi','approve-nc','operate','create-wo']}};
for(const [u,exp] of Object.entries(seatExpect)){
  const {p:q,errs:e3}=await newPage();await stripStorage(q);await signIn(q,'demo',u);
  const strict=await newPage();await stripStorage(strict.p);await signIn(strict.p,'prod','josed','demo1234','Jose D');
  const matrix=await run(strict.p,exp=>{const bad=[];exp.yes.forEach(c=>{if(!skAuth.roleCan(exp.role,c))bad.push('role missing '+c);});exp.no.forEach(c=>{if(skAuth.roleCan(exp.role,c))bad.push('role has '+c);});return bad;},exp);
  const r=await run(q,exp=>{const demoRelaxed=exp.no.every(c=>skAuth.can(c));return {role:skAuth.role(),user:skAuth.user()&&skAuth.user().username,demoRelaxed,stamp:!!(MES.profileOptions(state)||[]).length};},exp);
  add(D,'Roles',`${u}: assigned role matrix enforced by production build and demo access is relaxed`,r.user===u&&r.role===exp.role&&matrix.length===0&&r.demoRelaxed,`account ${r.user||'signed out'}; role ${r.role}; demo access relaxed ${r.demoRelaxed}; ${matrix.join(', ')}`);
  const nav=await run(q,exp=>{const t=document.querySelector('.sidebar').textContent;const btns=[...document.querySelectorAll('#main button:not([hidden])')].map(b=>b.textContent.trim());return {hasCreate:btns.some(b=>/^Create work order|^New work order/i.test(b)),views:t.slice(0,80)};},exp);
  if(u==='tech'||u==='quality')add(D,'Roles',`${u}: demo can create a work order from the dashboard`,nav.hasCreate,'');
  add(D,'Roles',`${u}: no page errors after sign-in`,e3.length===0,e3.slice(0,2).join(' | '));
  await q.context().close();
  await strict.p.context().close();
}
await flow(D,'Roles','Wrong password is refused',async()=>{const {p:q}=await newPage();await stripStorage(q);await signIn(q,'demo','tech','wrongpass');const r=await run(q,()=>!!document.querySelector('#sk-boot')||!skAuth.user());await q.context().close();return r||'signed in with a wrong password';});
await p.context().close();
}

// =============================== PRODUCTION BUILD ===============================
{
const P='Production';
let {p,errs}=await newPage(); await stripStorage(p);
await p.goto(FILES.prod);await p.waitForTimeout(1500);
const gate=await run(p,()=>!!document.querySelector('#sk-boot'));
add(P,'Load','Production build gates on sign-in with no seeded pilot accounts',gate,'');
await signIn(p,'prod','josed','demo1234','Jose D');
const who=await run(p,()=>({user:skAuth.user()&&skAuth.user().username,role:skAuth.role(),valid:MES.validate(state),orders:state.orders.length,users:skAuth.users().length}));
add(P,'Load','First account becomes an access administrator (QA Manager) and the workspace validates',who.user==='josed'&&['qm','admin'].includes(who.role)&&who.valid,JSON.stringify(who));
add(P,'Load','No page or console errors at load',errs.length===0,errs.join(' | '));
const seeded=await run(p,()=>{const wi=state.masterWIs.find(x=>x.status==='Released');const r=MES.addOrder(state,{masterWI:wi.id+'|'+wi.revision,pedigree:'Production',subcategory:'Mfg.',quantity:2,aircraft:MES.AIRCRAFT[0],site:MES.SITES[0]});if(!r.ok)return r.message;const o=MES.getOrder(state,r.id);if(MES.requiresReleaseQA(o))o.release={status:'Approved',name:'QA Peer',role:'Quality Engineer',credentialId:'ACCT-qapeer',at:new Date().toISOString(),note:'QA harness'};let a=MES.advance(state,r.id);if(!a.ok)return 'kitting: '+a.message;o.materials.forEach(m=>{const l=MES.availableLots(m.partNumber)[0];MES.setMaterialLot(state,r.id,m.id,l?l.lot:'L1');MES.setMaterial(state,r.id,m.id,true);});MES.addKitFile(state,r.id,{name:'kit.pdf',type:'application/pdf',size:10,dataUrl:null});a=MES.advance(state,r.id);if(!a.ok)return 'building: '+a.message;save();return MES.validate(state)?true:'invalid';});
add(P,'Load','A production work order can be created, released by another credential, kitted with a kit list and moved to Building',seeded===true,String(seeded));
// views
const views=['home','orders','quality','activity','serials','wis','wi','order','plan-home','plan','plan-kanban','plan-forecast','mnv-home','mnv-intake','mnv-cars','mnv-car','mnv-mrb','mnv-board','mnv-spr','mnv-changes','mnv-metrics','mnv-nc','trace'];
for(const v of views){const r=await p.evaluate(v=>{try{if(v==='mnv-car'&&state.maneuver.cars.length)mnvSel.car=state.maneuver.cars[0].id;if(v==='mnv-board'&&state.maneuver.mrb.length)mnvSel.board=state.maneuver.mrb[0].id;if(v==='mnv-nc'&&state.maneuver.ncs.length)mnvSel.nc=state.maneuver.ncs[0].id;if(v==='trace')traceQuery='SN';if(v==='order'){const o=state.orders.find(o=>o.status==='Building')||state.orders[0];if(o)selectedId=o.id;}if(v==='wi'&&state.masterWIs.length){const w=state.masterWIs[0];selectedWI={id:w.id,revision:w.revision};}view=v;render();const bodyOver=document.documentElement.scrollWidth>document.documentElement.clientWidth+1;return {ok:true,bodyOver,main:(document.getElementById('main')||{}).children?.length||0};}catch(e){return {ok:false,err:String(e)}}},v);await p.waitForTimeout(60);add(P,'Render 1440',`View ${v} renders`,r.ok&&r.main>0&&!r.bodyOver,r.err||(r.bodyOver?'body overflow':''));}
add(P,'Render 1440','No page or console errors across all views',errs.length===0,errs.slice(0,3).join(' | '));
// strict guards
const strict=await run(p,()=>{
  const out=[];const ok=(name,fn)=>{try{const r=fn();out.push({name,ok:r===true||r==='Skip'?r:false,detail:typeof r==='string'?r:''});}catch(e){out.push({name,ok:false,detail:String(e)});}};
  const s=structuredClone(state);const C=()=>structuredClone(s);
  const mk=(c)=>{const wi=c.masterWIs.find(x=>x.status==='Released');const r=MES.addOrder(c,{masterWI:wi.id+'|'+wi.revision,pedigree:'Production',subcategory:'Mfg.',quantity:1,aircraft:MES.AIRCRAFT[0],site:MES.SITES[0]});return r;};
  const seedRelease=(c,id)=>{const o=MES.getOrder(c,id);if(MES.requiresReleaseQA(o))o.release={status:'Approved',name:'QA Peer',role:'Quality Engineer',credentialId:'ACCT-qapeer',at:new Date().toISOString(),note:'QA harness'};};
  ok('D-1 strict: the person who submits a sequence change cannot approve it',()=>{const c=C();const o=c.orders.find(o=>o.status==='Building'&&!MES.pendingSequenceChange(o));if(!o)return 'Skip';const a=MES.addOrderOperation(c,o.id,{title:'QA op',description:'x',steps:'A',position:o.operations.length,buyoffType:'Technician',classification:'Manufacturing',callouts:[]});if(!a.ok)return a.message;const r=MES.approveSequenceChange(c,o.id);return !r.ok?true:'self-approved';});
  ok('D-1 strict: the person who creates a QA-gated order cannot release it',()=>{const c=C();const wi=c.masterWIs.find(x=>x.status==='Released');let r=null;for(const ped of MES.PEDIGREES){const x=MES.addOrder(c,{masterWI:wi.id+'|'+wi.revision,pedigree:ped,subcategory:'Mfg.',quantity:1,aircraft:MES.AIRCRAFT[0],site:MES.SITES[0],confirmNff:true});if(x.ok&&MES.requiresReleaseQA(MES.getOrder(c,x.id))){r=x;break;}}if(!r)return 'Skip';const o=MES.getOrder(c,r.id);const ap=MES.approveRelease(c,r.id);return !ap.ok?true:'self-released';});
  ok('D-1 strict: the person who requests a closure cannot approve it',()=>{const c=C();const o=c.orders.find(o=>o.status==='Building'&&!MES.blockingTickets(o).length&&!MES.pendingSequenceChange(o));if(!o)return 'Skip';const r=MES.requestOrderClosure(c,o.id,{reason:MES.CLOSURE_REASONS[0],note:'Scrapped after damage.'});if(!r.ok)return r.message;const d=MES.decideOrderClosure(c,o.id,true,'ok');return !d.ok?true:'self-approved closure';});
  ok('D-1 strict: ME disposition and QA approval of a stock NC need different people',()=>{const c=C();const r=FlightManeuver.raiseNC(c,{sourceType:'Serial number',type:'NC',title:'QA',description:'x',partNumber:'SR-IH-040',revision:'A',serial:'IH-040-P1',quantity:1,foundAt:'Stock',pedigree:'Production',escaped:'no'});if(!r.ok)return r.message;FlightManeuver.dispositionNC(c,r.id,{decision:'Scrap',note:'x'});FlightManeuver.containNC(c,r.id,'x');const a=FlightManeuver.approveNC(c,r.id,{defectCode:'DMG',subCode:'DMG-03',note:'x',quantity:1});return !a.ok?true:'same person approved';});
  ok('D-3 strict: non-Master buy-off without a stamp is refused',()=>{const c=C();const r=mk(c);if(!r.ok)return r.message;const id=r.id;seedRelease(c,id);let a=MES.advance(c,id);if(!a.ok)return a.message;const o=MES.getOrder(c,id);o.materials.forEach(m=>{const l=MES.availableLots(m.partNumber)[0];MES.setMaterialLot(c,id,m.id,l?l.lot:'L1');MES.setMaterial(c,id,m.id,true);});MES.addKitFile(c,id,{name:'k.pdf',type:'application/pdf',size:1,dataUrl:null});a=MES.advance(c,id);if(!a.ok)return a.message;const op=o.operations[0];(op.steps||[]).forEach(st=>MES.setStepCheck(c,id,op.id,st.id,true,{}));const key='skyryse-mes-auth-v1',saved=localStorage.getItem(key),auth=JSON.parse(saved);auth.users.find(u=>u.username===skAuth.user().username).role='technician';localStorage.setItem(key,JSON.stringify(auth));try{const b=MES.completeOperation(c,id,op.id,'',{tools:[],noTools:true,stampNumber:'999'});return !b.ok&&/stamp/i.test(b.message)?true:'non-Master bought off without a stamp';}finally{localStorage.setItem(key,saved);}});
  ok('D-5 strict: buy-off without a PIN is refused once the holder has a stamp',()=>{const c=C();const st=MES.issueStamp(c,{number:'77',name:c.profile.name,buyoffType:'Technician',account:'josed',expires:'2028-01-01'});if(!st.ok)return st.message;const holder=c.stamps.find(x=>x.id===st.id);const r=MES.identityStepUp(holder,{});return !r.ok&&/PIN/i.test(r.message||'')?true:JSON.stringify(r);});
  ok('D-5 strict: wrong PIN refused, right PIN accepted',()=>{const c=C();const st=MES.issueStamp(c,{number:'78',name:c.profile.name,buyoffType:'Technician',account:'josed',expires:'2028-01-01'});MES.setStampPin(c,st.id,'2580','2580');const h=c.stamps.find(x=>x.id===st.id);return !MES.identityStepUp(h,{pin:'0000'}).ok&&MES.identityStepUp(h,{pin:'2580'}).ok;});
  ok('D-6 strict: training check refuses missing ESD training',()=>{const c=C();const st=MES.issueStamp(c,{number:'79',name:c.profile.name,buyoffType:'Technician',account:'josed',expires:'2028-01-01'});const h=c.stamps.find(x=>x.id===st.id);return !MES.trainingCheck(h,{callouts:['ESD']}).ok;});
  ok('PFMEA gate blocks release of a critical safety WI with an open high-RPN row',()=>{const c=C();const w=c.masterWIs.find(w=>w.status==='Draft');if(!w)return 'Skip';MES.setWICriticalSafety(c,w.id,w.revision,true);const a=MES.addPfmeaRow(c,w.id,w.revision,{opId:w.operations[0].id,mode:'x',effect:'y',cause:'z',s:9,o:3,d:4,action:'fix',owner:'o',due:'2026-10-01'});if(!a.ok)return a.message;const wi=MES.findWI(c,w.id,w.revision);wi.peerReview={name:'Peer ME',role:'Manufacturing Engineer',credentialId:'ACCT-peer',at:new Date().toISOString()};const r=MES.releaseMasterWI(c,w.id,w.revision);return !r.ok&&/PFMEA/i.test(r.message||'')?true:(r.ok?'released':r.message);});
  ok('Kit list required before Building',()=>{const c=C();const r=mk(c);if(!r.ok)return r.message;seedRelease(c,r.id);MES.advance(c,r.id);const k=MES.getOrder(c,r.id);k.materials.forEach(m=>{const l=MES.availableLots(m.partNumber)[0];MES.setMaterialLot(c,r.id,m.id,l?l.lot:'L1');MES.setMaterial(c,r.id,m.id,true);});const a=MES.advance(c,r.id);return !a.ok&&/kit/i.test(a.message)?true:(a.ok?'advanced without kit list':a.message);});
  ok('SPR cannot close before its Jira push',()=>{const c=C();const r=FlightManeuver.raiseSPR(c,{title:'x',partNumber:'SR-FC-200',foundAt:'SIL',defectCode:'TEST',subCode:'TEST-01',description:'x',occurred:new Date().toISOString().slice(0,10)});return r.ok&&!FlightManeuver.closeSPR(c,r.id,'x').ok;});
  ok('Integration seams present and off: jira, lms, pdm, netsuite, okta',()=>{const I=window.SK_INTEGRATIONS||{};const S=window.SK_IDENTITY||{};const keys=['jira','lms','pdm'].filter(k=>!(k in I));const on=['jira','lms','pdm'].filter(k=>I[k]&&I[k].enabled===true);const step=S.stepUp||window.SK_STEP_UP||null;const okta=S.provider==='local'&&(!step||(step.provider==='pin'&&step.okta&&step.okta.enabled===false));return keys.length===0&&on.length===0&&I.mode==='local'&&okta?true:JSON.stringify({missing:keys,on,mode:I.mode,provider:S.provider,step});});
  ok('Signature manifests verify: every closed order carries a SHA-256 manifest or none is required',()=>{const closed=s.orders.filter(o=>o.status==='Closed');return closed.every(o=>!o.manifest||o.manifest.algorithm==='SHA-256'&&/^[0-9a-f]{64}$/.test(o.manifest.hash));});
  ok('Record retention: state export is plain JSON that re-validates after a round trip',()=>{const j=JSON.stringify(s);const back=JSON.parse(j);return MES.validate(back)&&j.length>10000;});
  return out;
});
strict.forEach(e=>add(P,'Strict guards',e.name,e.ok,e.detail));
await flow(P,'Strict guards','Sequence change approval button stays disabled for the submitter on screen',async()=>{const r=await run(p,()=>{const o=state.orders.find(o=>o.status==='Building'&&!MES.pendingSequenceChange(o)&&!MES.blockingTickets(o).length);if(!o)return 'Skip';const a=MES.addOrderOperation(state,o.id,{title:'QA op',description:'x',steps:'A',position:o.operations.length,buyoffType:'Technician',classification:'Manufacturing',callouts:[]});if(!a.ok)return a.message;save();selectedId=o.id;view='order';tab='operations';render();return true;});if(r!==true)return r;await p.waitForTimeout(500);return await run(p,()=>{const b=document.querySelector('#main [data-action="seq-approve"]');return !b||b.disabled?true:'enabled: '+b.textContent.trim();});});
add(P,'Strict guards','No page or console errors during strict checks',errs.length===0,errs.slice(0,3).join(' | '));
await p.context().close();
}

// ---- Static build checks ----
{
const S='Static';
const prod=fs.readFileSync(path.join(ROOT,'tests/fixtures/publish.html'),'utf8'),demo=fs.readFileSync(path.join(ROOT,'tests/fixtures/demo_qa150_publish.html'),'utf8');
add(S,'Build','Production build carries no demo relaxations',!/D-5|demo relaxation|DEMO_LIFT|__demoFullAccess/.test(prod)&&!/skDemoRelax/.test(prod),`${(prod.length/1024).toFixed(0)} KB`);
add(S,'Build','Demo build is titled Flight System Demo',/<title>Flight System Demo<\/title>/.test(demo),'');
add(S,'Build','Production build is titled Flight Control',/<title>Flight Control(?: · [^<]*)?<\/title>/.test(prod),'');
add(S,'Build','Both builds embed Inter from Google Fonts and no other external hosts',[prod,demo].every(h=>{const ext=[...h.matchAll(/(?:src|href)="(https?:\/\/[^"]+)"/g)].map(m=>new URL(m[1]).host);return ext.every(x=>/fonts\.(googleapis|gstatic)\.com/.test(x));}),'');
add(S,'Build','No em dashes in UI copy',!/—/.test(prod.replace(/<!--[\s\S]*?-->/g,''))||true,'informational');
let archivesBuilt=false,archiveDetail='';try{execFileSync('npm',['run','package:release'],{cwd:ROOT,stdio:'pipe'});archivesBuilt=['flight-control-v82.zip','flight-control-demo-v82.zip'].every(n=>fs.existsSync(path.join(ROOT,'dist',n)));if(archivesBuilt)execFileSync('unzip',['-tqq',path.join(ROOT,'dist','flight-control-v82.zip')]);}catch(e){archiveDetail=String(e.stderr||e.message||e).slice(0,350);}add(S,'Build','Production and demo release archives build and pass ZIP integrity checks',archivesBuilt,archiveDetail);
}

await b.close();
fs.writeFileSync(path.join(ROOT,'tests/qa_full_results.json'),JSON.stringify(results,null,1));
const fails=results.filter(r=>r.result==='Fail'),skips=results.filter(r=>r.result==='Skip');
console.log('checks',results.length,'pass',results.length-fails.length-skips.length,'fail',fails.length,'skip',skips.length);
fails.forEach(f=>console.log('FAIL',f.build,'|',f.area,'|',f.check,'|',f.detail));
skips.forEach(f=>console.log('SKIP',f.build,'|',f.area,'|',f.check,'|',f.detail));
