// verifyManifests recomputes every signature kind from the stored record, not only from the subject the manifest
// stored: the 8130-9 completion, the AQI signature and the DAR acceptance; the MRB board decision; the CAR closure;
// the stock NC disposition approval; the FAIR verification content; and the FAIR box 22 review, which the Skyryse QA approval now binds.
// An edit to any signed field after signing fails verification. Box 22 is also validated as a record.
import {chromium} from 'playwright';
const TESTS=decodeURI(new URL('.',import.meta.url).pathname);
const FIXTURES=process.env.FS_FIXTURES_DIR?process.env.FS_FIXTURES_DIR.replace(/\/?$/,'/'):TESTS+'fixtures/';
const b=await chromium.launch(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{});
const p=await (await b.newContext({viewport:{width:1440,height:1000}})).newPage();
const errs=[];p.on('pageerror',e=>errs.push(e.message));
const fails=[];const ok=(w,c,m='')=>{console.log((c?'  ok   ':'  FAIL ')+w+(c?'':' -> '+m));if(!c)fails.push(w);};
const run=(fn,a)=>p.evaluate(fn,a);
async function open(file,user){await p.evaluate(()=>{try{sessionStorage.removeItem('skyryse-mes-session-v1');}catch(e){}}).catch(()=>{});
  await p.goto('file://'+FIXTURES+file);await p.waitForTimeout(900);
  await run(u=>{const un=document.querySelector('#sk-boot input[name=username]');if(!un)return;const f=un.closest('form');const set=(el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));};set(un,u);set(f.querySelector('input[type=password]'),'demo1234');f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));},user);
  await p.waitForTimeout(2600);}
// Applies an edit to a copy of the workspace and returns what verifyManifests says about it.
const tamper=(edit)=>run(src=>{const s=structuredClone(state);(new Function('s',src))(s);const v=MES.verifyManifests(s);return {ok:v.ok,where:v.failures.map(f=>f.where)};},edit);
const expectFail=async(label,edit,where)=>{const r=await tamper(edit);ok(label,r.ok===false&&r.where.some(w=>w.includes(where)),JSON.stringify(r));};

await open('demo_publish.html','master');
let r=await run(()=>{const v=MES.verifyManifests(state);return {ok:v.ok,failures:v.failures};});
ok('the curated demo workspace verifies',r.ok===true,JSON.stringify(r.failures));
const conf=await run(()=>{const o=state.orders.find(o=>(o.conformity||[]).some(p=>p.form&&p.aqi&&p.darApproval));return o?{id:o.id,serial:o.conformity.find(p=>p.form&&p.aqi&&p.darApproval).serial}:null;});
ok('fixture: a conformed package with a signed 8130-9, AQI signature and DAR acceptance',!!conf,JSON.stringify(conf));
const confJson=await run(()=>JSON.stringify(state));
const pkg=`const p=s.orders.find(o=>o.id==='${conf.id}').conformity.find(p=>p.serial==='${conf.serial}');`;
await expectFail('editing the 8130-9 certification basis after signing fails',pkg+"p.form.basis='Edited after signing';",'8130-9');
await expectFail('editing the 8130-9 deviations after signing fails',pkg+"p.form.deviations='None, edited';",'8130-9');
await expectFail('marking the AQI signature self-signed after signing fails',pkg+"p.aqi.selfSigned=true;",'8130-9 AQI signature');
await expectFail('adding an override to the recorded 8130-9 preparer after signing fails',pkg+"p.form.prepared.by={...p.form.prepared.by,override:{kind:'Support Access override',reason:'Added later.'}};",'8130-9');
await expectFail('adding an override to the recorded AQI signer after signing fails',pkg+"p.aqi.by={...p.aqi.by,override:{kind:'Support Access override',reason:'Added later.'}};",'8130-9 AQI signature');
await expectFail('editing the DAR designation after signing fails',pkg+"p.darApproval.designation='DAR-0000';",'DAR acceptance');
await expectFail('editing the DAR date after signing fails',pkg+"p.darApproval.date='2020-01-01';",'DAR acceptance');
await expectFail('removing the 8130-9 signature manifest fails',pkg+"delete p.form.prepared.manifest;",'8130-9');
await expectFail('removing the AQI signature manifest fails',pkg+"delete p.aqi.manifest;",'8130-9 AQI signature');
await expectFail('removing the DAR acceptance manifest fails',pkg+"delete p.darApproval.manifest;",'DAR acceptance');
await expectFail('changing the recorded 8130-9 preparer away from the form signer fails',pkg+"p.form.prepared.by={...p.form.prepared.by,credentialId:'ACCT-other'};",'8130-9');
await expectFail('renaming the recorded 8130-9 preparer fails',pkg+"p.form.prepared.by={...p.form.prepared.by,name:'Someone Else'};",'8130-9');
await expectFail('renaming the recorded AQI signer fails',pkg+"p.aqi.by={...p.aqi.by,name:'Someone Else'};",'8130-9 AQI signature');
await expectFail('changing the recorded AQI signer away from the AQI signature fails',pkg+"p.aqi.by={...p.aqi.by,credentialId:'ACCT-other'};",'8130-9 AQI signature');
await expectFail('removing the completed 8130-9 from a conformed package fails rather than skipping its AQI and DAR checks',pkg+"p.form=null;",'8130-9');
// An 8130-9 and AQI signature signed by this build bind the recorded inspection stamp.
r=await run(([json,c])=>{const s=JSON.parse(json),o=s.orders.find(x=>x.id===c.id),p=o.conformity.find(x=>x.serial===c.serial);const stamp={number:'Q-101',type:'Quality'};const reSign=()=>{const pm=p.form.prepared;const pBy={...pm.manifest.signer,stamp};p.form.prepared={by:pBy,at:pm.at};p.form.prepared.manifest=MES.signManifest(s,pm.manifest.meaning,{order:o.id,...p.form,prepared:undefined,preparedStamp:stamp},pm.at);p.form.prepared.manifest.signer={...p.form.prepared.manifest.signer,name:pBy.name,credentialId:pBy.credentialId};p.form.prepared.by={...pBy,name:p.form.prepared.manifest.signer.name,credentialId:p.form.prepared.manifest.signer.credentialId};const am=p.aqi;const aBy={...am.manifest.signer,stamp};p.aqi={...am,by:aBy,manifest:MES.signManifest(s,am.manifest.meaning,{order:o.id,serial:p.serial,form:p.form.prepared.manifest.hash,stamp,...(am.selfSigned?{selfSigned:true}:{})},am.at)};p.aqi.by={...aBy,name:p.aqi.manifest.signer.name,credentialId:p.aqi.manifest.signer.credentialId};};reSign();const where=x=>MES.verifyManifests(x).failures.filter(f=>f.where.includes(`${o.id} ${p.serial} 8130-9`)&&!/DAR/.test(f.where)).map(f=>f.where);const before=where(s);const a=structuredClone(s);a.orders.find(x=>x.id===c.id).conformity.find(x=>x.serial===c.serial).form.prepared.by.stamp={number:'Q-999',type:'Quality'};const b=structuredClone(s);b.orders.find(x=>x.id===c.id).conformity.find(x=>x.serial===c.serial).aqi.by.stamp=null;return {before,prepared:where(a),aqi:where(b)};},[confJson,conf]);
ok('a current 8130-9 and AQI signature bind the recorded inspection stamp: changing the preparer stamp or removing the AQI stamp fails',r.before.length===0&&r.prepared.some(w=>/8130-9$/.test(w))&&r.aqi.some(w=>/AQI signature/.test(w)),JSON.stringify(r));
await expectFail('removing the AQI signature from a conformed package fails',pkg+"p.aqi=null;",'8130-9 AQI signature');
await expectFail('removing who recorded the DAR acceptance fails',pkg+"delete p.darApproval.by;",'DAR acceptance');
await expectFail('changing when the DAR acceptance was recorded fails',pkg+"p.darApproval.at='2026-01-01T00:00:00.000Z';",'DAR acceptance');
await expectFail('removing the DAR acceptance from a conformed package fails',pkg+"p.darApproval=null;",'DAR acceptance');
await expectFail('removing the AQI signature from a package marked AQI signed fails',pkg+"p.status='AQI signed';p.darApproval=null;p.aqi=null;",'8130-9 AQI signature');
await expectFail('removing the DAR acceptance from a closed package fails',pkg+"p.status='Closed';p.darApproval=null;",'DAR acceptance');

const mrb=await run(()=>{const m=(state.maneuver.mrb||[]).find(m=>m.decision&&m.decision.manifest);return m&&m.id;});
ok('fixture: a decided MRB board',!!mrb,String(mrb));
const board=`const m=s.maneuver.mrb.find(m=>m.id==='${mrb}');`;
await expectFail('editing the MRB decision rationale after signing fails',board+"m.decision.note='Edited after the decision.';",`${mrb} board decision`);
await expectFail('changing a recorded MRB vote after the decision fails',board+"m.votes[0].vote=m.votes[0].vote==='Approve'?'Reject':'Approve';",`${mrb} board decision`);
await expectFail('changing who voted a seat after the decision fails',board+"m.votes[0].by={...m.votes[0].by,credentialId:'ACCT-someone'};",`${mrb} board decision`);
await expectFail('changing the MRB serials after the decision fails',board+"m.serials=[...(m.serials||[]),'SN-EXTRA'];",`${mrb} board decision`);
await expectFail('changing who recorded the MRB decision fails',board+"m.decision.by={...m.decision.by,credentialId:'ACCT-other',name:'Someone Else'};",`${mrb} board decision`);
await expectFail('changing the recorded name on the MRB decision fails',board+"m.decision.by={...m.decision.by,name:'Someone Else'};",`${mrb} board decision`);
await expectFail('changing when the MRB decision was recorded fails',board+"m.decision.at='2026-01-01T00:00:00.000Z';",`${mrb} board decision`);
await expectFail('removing the MRB decision manifest fails',board+"delete m.decision.manifest;",`${mrb} board decision`);

const nc=await run(()=>{const t=(state.maneuver.ncs||[]).find(t=>t.resolution&&t.resolution.manifest);return t&&t.id;});
ok('fixture: a stock NC with an approved disposition',!!nc,String(nc));
const stock=`const t=s.maneuver.ncs.find(t=>t.id==='${nc}');`;
await expectFail('changing the stock NC disposition after approval fails',stock+"t.dispo.decision=t.dispo.decision==='Scrap'?'Use as is':'Scrap';",`${nc} disposition approval`);
await expectFail('changing the affected quantity after approval fails',stock+"t.affected.quantity=t.affected.quantity+1;",`${nc} disposition approval`);
await expectFail('changing the defect code after approval fails',stock+"t.affected.defectCode='ZZ';",`${nc} disposition approval`);
await expectFail('changing the approval note after approval fails',stock+"t.resolution.note='Edited.';",`${nc} disposition approval`);
await expectFail('changing the recorded name on the stock NC approval fails',stock+"t.resolution.by={...t.resolution.by,name:'Someone Else'};",`${nc} disposition approval`);
await expectFail('removing the stock NC approval manifest fails',stock+"delete t.resolution.manifest;",`${nc} disposition approval`);
r=await run(()=>{const s=structuredClone(state),t=(s.maneuver.ncs||[]).find(t=>t.resolution&&t.resolution.manifest);if(!t)return {none:true};delete t.affected;const v=MES.verifyManifests(s);return {id:t.id,ok:v.ok,where:v.failures.map(f=>f.where)};});
ok('removing the affected record from an approved stock NC fails rather than skipping the check',r.ok===false&&r.where.some(w=>w.includes(`${r.id} disposition approval`)),JSON.stringify(r));
// A migrated escape: resolved with no disposition or affected record, an escape record, a closure with no manifest, and the
// structured record the migration writes (resolution.legacy). The exemption keys only on that record (#305); the server refuses
// any write that adds it (tests/test_migrated_escape_manifest.mjs). Any other resolved NC without a manifest fails.
const migrated=`const t=s.maneuver.ncs.find(t=>t.id==='${nc}');delete t.resolution.manifest;t.dispo=null;t.affected=null;t.mrbId=null;t.escape={from:'Final inspection',detectedAt:'Customer'};t.resolution.legacy={source:'escape',escapeId:'ESC-0001',migratedAt:new Date().toISOString()};`;
r=await run(src=>{const s=structuredClone(state);(new Function('s',src))(s);const v=MES.verifyManifests(s);return {ok:v.ok,where:v.failures.map(f=>f.where),valid:MES.validate(s)};},migrated);
ok('a stock NC migrated from a closed escape keeps its unsigned closure without a verification failure',!r.where.some(w=>w.includes(`${nc} disposition approval`))&&r.valid===true,JSON.stringify(r));
await expectFail('a signed NC that only gains a migration history entry still fails when its manifest is removed',stock+"delete t.resolution.manifest;t.history=[...(t.history||[]),{at:new Date().toISOString(),action:'Migrated from escape ESC-0001.',actor:'system'}];",`${nc} disposition approval`);
await expectFail('#305 the full migration shape with a system history entry but no migrated-escape record does not exempt the closure',migrated+"delete t.resolution.legacy;t.history=[...(t.history||[]),{at:new Date().toISOString(),action:'Migrated from escape ESC-0001.',actor:'system'}];",`${nc} disposition approval`);
await expectFail('a migrated NC that keeps a disposition record does not keep the exemption',migrated+"t.dispo={decision:'Scrap'};",`${nc} disposition approval`);
await expectFail('a migrated-escape record dated before the closure does not exempt it',migrated+"t.resolution.legacy.migratedAt='2000-01-01T00:00:00.000Z';",`${nc} disposition approval`);
await expectFail('a malformed migrated-escape record does not exempt the closure',migrated+"t.resolution.legacy={source:'escape',escapeId:'ESC-0001'};",`${nc} disposition approval`);
// A stock NC approval signed by this build binds the disposition record and who approved it and when, inside the hash.
r=await run(([id])=>{const s=structuredClone(state),t=s.maneuver.ncs.find(x=>x.id===id),r0=t.resolution;r0.manifest=MES.signManifest(s,r0.manifest.meaning,MES.ncApprovalSubject(t,r0.note,r0.by,r0.at,true,MES.mrbDecisionHashOf(s,t)),r0.at);const sg=r0.manifest.signer;r0.by={...r0.by,name:sg.name,role:sg.role,credentialId:sg.credentialId};r0.manifest=MES.signManifest(s,r0.manifest.meaning,MES.ncApprovalSubject(t,r0.note,r0.by,r0.at,true,MES.mrbDecisionHashOf(s,t)),r0.at);const ok0=MES.verifyManifests(s).ok;const edit=f=>{const x=structuredClone(s),y=x.maneuver.ncs.find(z=>z.id===id);f(y);return MES.verifyManifests(x).failures.some(z=>z.where.includes(`${id} disposition approval`));};const other={name:'Someone Else',role:'Quality Engineer',credentialId:'ACCT-other'};return {before:ok0,marker:Object.hasOwn(r0.manifest.subject,'signedAt'),dispoBy:edit(y=>{y.dispo.credentialId='ACCT-other';}),dispoNote:edit(y=>{y.dispo.note='Edited after approval.';}),jointTime:edit(y=>{const at='2026-01-01T00:00:00.000Z';y.resolution.at=at;y.resolution.manifest.at=at;}),jointSigner:edit(y=>{y.resolution.by={...y.resolution.by,...other};y.resolution.manifest.signer={...y.resolution.manifest.signer,...other};}),serials:edit(y=>{y.affected.serials=['SN-OTHER-1'];}),description:edit(y=>{y.description='A different discrepancy.';}),ncPedigree:edit(y=>{y.pedigree=y.pedigree==='Production'?'Development':'Production';}),quantity:edit(y=>{y.quantity=y.quantity+1;}),containment:edit(y=>{y.containment={...(y.containment||{}),note:'Rewritten after approval.'};}),raiser:edit(y=>{y.raisedBy={...y.raisedBy,name:'Someone Else',credentialId:'ACCT-other'};}),reworkLink:edit(y=>{y.reworkOrderId='WO-99999';}),boardResigned:(()=>{const x=structuredClone(s),y=x.maneuver.ncs.find(z=>z.id===id),m=x.maneuver.mrb.find(b=>b.id===y.mrbId);if(!m)return 'no board';const d=m.decision;d.note='A different rationale, signed again.';const keep=d.manifest.signer;d.manifest={...MES.signManifest(x,d.manifest.meaning,MES.mrbDecisionSubject(m,d.status,d.note,true,d.by,d.at),d.at),signer:keep};const f=MES.verifyManifests(x).failures;return f.some(z=>z.where.includes(`${id} disposition approval`))&&!f.some(z=>z.where.includes(`${m.id} board decision`));})(),bindsBoard:!!t.mrbId&&r0.manifest.subject.mrbDecision===MES.mrbDecisionHashOf(s,t)};},[nc]);
ok('a stock NC approval signed by this build binds the disposition record: changing who recorded it or its note fails',r.before===true&&r.marker===true&&r.dispoBy===true&&r.dispoNote===true,JSON.stringify(r));
ok('a stock NC approval signed by this build binds the approver and time: changing them together with the manifest metadata fails',r.jointTime===true&&r.jointSigner===true,JSON.stringify(r));
ok('a stock NC approval signed by this build binds the affected serials',r.serials===true,JSON.stringify(r));
ok('a stock NC approval signed by this build binds the NC itself: description, pedigree, quantity, containment and raiser',r.description&&r.ncPedigree&&r.quantity&&r.containment&&r.raiser,JSON.stringify(r));
ok('a rework order linked after approval is not part of the signed NC approval',r.reworkLink===false,JSON.stringify(r));
ok('a stock NC approval signed by this build binds the cited MRB decision: re-signing the board with other content fails the NC approval',r.bindsBoard===true&&r.boardResigned===true,JSON.stringify(r));
r=await run(([id])=>{const s=structuredClone(state);const before=JSON.stringify(s.maneuver.ncs.find(x=>x.id===id));const res=FlightManeuver.containNC(s,id,'Further units located and quarantined.');return {ok:res.ok,message:res.message,unchanged:JSON.stringify(s.maneuver.ncs.find(x=>x.id===id))===before};},[nc]);
ok('containment cannot be recorded on a resolved stock NC, and the refusal leaves it unchanged',r.ok===false&&/is resolved/.test(r.message)&&r.unchanged===true,JSON.stringify(r));
await expectFail('deleting the MRB a resolved stock NC cites fails',stock+"s.maneuver.mrb=s.maneuver.mrb.filter(m=>m.id!==t.mrbId);",`${nc} disposition approval`);
r=await run(([id])=>{const s=structuredClone(state),t=s.maneuver.ncs.find(x=>x.id===id);s.maneuver.mrb=s.maneuver.mrb.filter(m=>m.id!==t.mrbId);return {gap:MES.missingSignatures(s).some(g=>g.where===`${id} disposition approval`&&/cites/.test(g.reason)),valid:MES.validate(s)};},[nc]);
ok('MES.validate refuses a resolved stock NC whose cited MRB is gone',r.gap===true&&r.valid===false,JSON.stringify(r));
await expectFail('relabelling the stock NC approval signature meaning fails',stock+"t.resolution.manifest.meaning='Rejected for cause';",`${nc} disposition approval`);
await expectFail('relabelling the MRB decision signature meaning fails',board+"m.decision.manifest.meaning='MRB rejected';",`${mrb} board decision`);
// The 8130-9 completion, the AQI signature and the DAR acceptance signed by this build bind who signed and when inside the hash.
r=await run(([json,c])=>{const s=JSON.parse(json),o=s.orders.find(x=>x.id===c.id),p=o.conformity.find(x=>x.serial===c.serial);const sg=MES.signManifest(s,'x',{},p.form.prepared.at).signer,who={name:sg.name,role:sg.role,credentialId:sg.credentialId};const sb=(by,at)=>({signer:{name:by.name,role:by.role,credentialId:by.credentialId},signedAt:at});p.form.prepared.by={...p.form.prepared.by,...who};p.form.prepared.manifest=MES.signManifest(s,p.form.prepared.manifest.meaning,{order:o.id,...p.form,prepared:undefined,preparedStamp:p.form.prepared.by.stamp??null,...sb(p.form.prepared.by,p.form.prepared.at)},p.form.prepared.at);p.aqi.by={...p.aqi.by,...who};delete p.aqi.selfSigned;p.aqi.manifest=MES.signManifest(s,p.aqi.manifest.meaning,{order:o.id,serial:p.serial,form:p.form.prepared.manifest.hash,stamp:p.aqi.by.stamp??null,...sb(p.aqi.by,p.aqi.at)},p.aqi.at);if(p.aqi.by.credentialId===p.form.prepared.by.credentialId){p.aqi.selfSigned=true;p.aqi.manifest=MES.signManifest(s,p.aqi.manifest.meaning,{order:o.id,serial:p.serial,form:p.form.prepared.manifest.hash,stamp:p.aqi.by.stamp??null,...sb(p.aqi.by,p.aqi.at),selfSigned:true},p.aqi.at);}const d=p.darApproval;d.manifest=MES.signManifest(s,d.manifest.meaning,{order:o.id,serial:p.serial,name:d.name,designation:d.designation,date:d.date,form:p.form.prepared.manifest.hash,aqi:p.aqi.manifest.hash,...sb(d.by,d.at)},d.at);const base=MES.verifyManifests(s);const edit=(f,re)=>{const x=structuredClone(s),q=x.orders.find(z=>z.id===c.id).conformity.find(z=>z.serial===c.serial);f(q);return MES.verifyManifests(x).failures.some(z=>re.test(z.where));};const at='2026-01-01T00:00:00.000Z',other={name:'Someone Else',role:'Quality Engineer',credentialId:'ACCT-other'};return {before:base.ok,failures:base.failures.slice(0,3),form:edit(q=>{q.form.prepared.at=at;q.form.prepared.manifest.at=at;},/8130-9$/),aqi:edit(q=>{q.aqi.at=at;q.aqi.manifest.at=at;},/AQI signature/),dar:edit(q=>{q.darApproval.at=at;q.darApproval.manifest.at=at;},/DAR acceptance/),darBy:edit(q=>{q.darApproval.by={...q.darApproval.by,...other};},/DAR acceptance/),aqiSigner:edit(q=>{q.aqi.by={...q.aqi.by,...other};q.aqi.manifest.signer={...q.aqi.manifest.signer,...other};},/AQI signature/)};},[confJson,conf]);
ok('an 8130-9, AQI signature and DAR acceptance signed by this build verify, and changing a signing time together with its manifest time fails',r.before===true&&r.form===true&&r.aqi===true&&r.dar===true,JSON.stringify(r));
ok('an AQI signature or DAR acceptance signed by this build binds who signed: replacing the recorded signer (with the manifest signer) fails',r.aqiSigner===true&&r.darBy===true,JSON.stringify(r));
await expectFail('changing who approved the stock NC disposition fails',stock+"t.resolution.by={...t.resolution.by,credentialId:'ACCT-other',name:'Someone Else'};",`${nc} disposition approval`);
await expectFail('changing when the stock NC disposition was approved fails',stock+"t.resolution.at='2026-01-01T00:00:00.000Z';",`${nc} disposition approval`);

// An Approved PFMEA released its WI on the Safety Team buy-off: the buy-off record and its complete signature must stay.
r=await run(()=>{const base=structuredClone(state),t0=(base.maneuver.pfmeas||[])[0];if(!t0)return {none:true};const gap=f=>{const s=structuredClone(base),t=s.maneuver.pfmeas.find(x=>x.id===t0.id);f(t,s);return {gap:MES.missingSignatures(s).some(g=>g.where===`${t0.id} Safety Team buy-off`),valid:MES.validate(s)};};const at=new Date().toISOString(),by={...state.profile};const signedSafety=(t,s)=>({decision:'Approved',note:'Safety Team accepts the analysis.',by,at,manifest:MES.signManifest(s,'PFMEA Safety Team buy-off',{pfmea:t.id},at)});return {id:t0.id,missing:gap(t=>{t.status='Approved';t.safety=null;}),empty:gap((t,s)=>{t.status='Approved';t.safety={...signedSafety(t,s),manifest:{}};}),complete:gap((t,s)=>{t.status='Approved';t.safety=signedSafety(t,s);}),open:gap(()=>{})};});
ok('fixture: a PFMEA in the curated set',!r.none,JSON.stringify(r));
ok('an Approved PFMEA with no Safety Team buy-off record is a missing signature, and MES.validate refuses it',r.missing&&r.missing.gap===true&&r.missing.valid===false,JSON.stringify(r));
ok('a Safety Team buy-off whose manifest is empty is a missing signature',r.empty&&r.empty.gap===true&&r.empty.valid===false,JSON.stringify(r));
ok('a Safety Team buy-off with a complete signature, and an open PFMEA, are not reported as missing',r.complete&&r.complete.gap===false&&r.open&&r.open.gap===false,JSON.stringify(r));

// A Use for Dev approval downgrades the NC to Development before it is signed, so the approval it records verifies.
r=await run(()=>{const s=structuredClone(state);const x=FlightManeuver.raiseNC(s,{sourceType:'Serial number',type:'NC',title:'Use for Dev check',description:'Bench unit with a cosmetic defect.',partNumber:'SR-IH-040',revision:'A',serial:'IH-040-DEV1',quantity:1,foundAt:'Receiving inspection',pedigree:'Production'});if(!x.ok)return {step:'raise',m:x.message};const d=FlightManeuver.dispositionNC(s,x.id,{decision:'Use for Dev',note:'Usable on a development unit.'});if(!d.ok)return {step:'dispo',m:d.message};const a=FlightManeuver.approveNC(s,x.id,{defectCode:'DMG',subCode:'DMG-03',note:'Approved for development use.',quantity:1});if(!a.ok)return {step:'approve',m:a.message};const t=FlightManeuver.get(s,'ncs',x.id),v=MES.verifyManifests(s);return {pedigree:t.pedigree,signed:t.resolution.manifest.subject.nc.pedigree,fails:v.failures.filter(f=>f.where.includes(x.id)).map(f=>f.reason)};});
ok('a Use for Dev approval signs the downgraded Development pedigree and verifies',r.pedigree==='Development'&&r.signed==='Development'&&Array.isArray(r.fails)&&r.fails.length===0,JSON.stringify(r));
// Signatures from earlier builds of this change keep the form they were signed in: each added key is recomputed only when present.
r=await run(([json,id,mrb,car])=>{const s=JSON.parse(json);const t=s.maneuver.ncs.find(x=>x.id===id),r0=t.resolution;const keep=r0.manifest.signer;const full=MES.ncApprovalSubject(t,r0.note,r0.by,r0.at,true,MES.mrbDecisionHashOf(s,t));const gen=k=>{const sub={...full};k.forEach(x=>delete sub[x]);return sub;};const out={};const sign=(sub)=>{r0.manifest={...MES.signManifest(s,r0.manifest.meaning,sub,r0.at),signer:keep};r0.by={...r0.by,name:keep.name,role:keep.role,credentialId:keep.credentialId};return MES.verifyManifests(s).failures.filter(f=>f.where.includes(id)).map(f=>f.reason);};out.ncSignedAtOnly=sign(gen(['nc','serials','mrbDecision']));out.ncNoNc=sign(gen(['nc']));const m=s.maneuver.mrb.find(b=>b.id===mrb),d=m.decision,dk=d.manifest.signer;d.by={name:dk.name,role:dk.role,credentialId:dk.credentialId};const ms={...MES.mrbDecisionSubject(m,d.status,d.note,true,d.by,d.at)};delete ms.pedigree;d.manifest={...MES.signManifest(s,d.manifest.meaning,ms,d.at),signer:dk};out.mrbNoPedigree=MES.verifyManifests(s).failures.filter(f=>f.where.includes(mrb)).map(f=>f.reason);return out;},[confJson,nc,mrb]);
ok('a stock NC approval signed with signer and time but before the NC, serials or board hash were bound still verifies',r.ncSignedAtOnly.length===0&&r.ncNoNc.length===0,JSON.stringify(r));
ok('an MRB decision signed with signer and time but before the pedigree was bound still verifies',r.mrbNoPedigree.length===0,JSON.stringify(r));

// ---- box 22 is signed, validated and bound into the Skyryse QA approval ----
const fair=await run(()=>{const o=state.orders.find(o=>o.fair&&o.fair.status==='Approved');if(!o)return null;const s=structuredClone(state),x=s.orders.find(y=>y.id===o.id);x.fair.status='Open';x.fair.verified=null;x.fair.approved=null;delete x.fair.reviewed;
  const vf=MES.verifyFair(s,o.id,{pin:''});if(!vf.ok)return {id:o.id,vf};const rv=MES.reviewFair(s,o.id,{pin:''});const ap=rv.ok?MES.approveFair(s,o.id,{pin:''}):null;if(rv.ok&&ap&&ap.ok)state=s;return {id:o.id,rv,ap,valid:MES.validate(s),subject:x.fair.approved&&x.fair.approved.manifest.subject,reviewedHash:x.fair.reviewed&&x.fair.reviewed.manifest.hash};});
ok('box 22 signed and the FAIR approved',fair&&fair.rv.ok&&fair.ap&&fair.ap.ok&&fair.valid,JSON.stringify(fair));
ok('the Skyryse QA approval signs the box 22 review hash',fair&&fair.subject&&fair.subject.reviewed===fair.reviewedHash,JSON.stringify(fair&&fair.subject));
r=await run(([id])=>{const f=state.orders.find(o=>o.id===id).fair;return {reviewer:f.reviewed.manifest.subject.reviewer,by:f.reviewed.by.credentialId,at:f.reviewed.manifest.subject.reviewedAt===f.reviewed.at};},[fair.id]);
ok('box 22 signs the reviewer credential and time',r.reviewer===r.by&&r.at===true,JSON.stringify(r));
r=await run(()=>{const v=MES.verifyManifests(state);return {ok:v.ok,failures:v.failures};});
ok('the approved FAIR verifies',r.ok===true,JSON.stringify(r.failures));
const F=`const f=s.orders.find(o=>o.id==='${fair.id}').fair;`;
await expectFail('changing a FAIR characteristic result after verification fails',F+"f.chars[0].result='Edited after verification';",'FAIR verification');
await expectFail('adding a Form 2 line after verification fails',F+"f.form2=[...f.form2,{kind:'Material',name:'Added later',spec:'X',code:'',supplier:'Y',approval:'Yes',coc:'Z'}];",'FAIR verification');
await expectFail('replacing the box 22 reviewer after the approval fails',F+"f.reviewed.by={...f.reviewed.by,credentialId:'ACCT-intruder',name:'Someone Else'};",'FAIR');
await expectFail('re-signing box 22 as someone else after the approval fails',F+"f.reviewed={...f.reviewed,by:{...f.reviewed.by,credentialId:'ACCT-other'},manifest:MES.signManifest(s,'AS9102 FAIR reviewed and approved (blocks 22 and 23)',{fair:f.reviewed.manifest.subject.fair,verified:f.verified.manifest.hash,reviewer:'ACCT-other',reviewedAt:f.reviewed.at},f.reviewed.at)};",'FAIR approval');
await expectFail('changing the FAI reasons after verification fails',F+"f.reasons=[f.reasons[0]==='Mfg. process change'?'New part (first production)':'Mfg. process change'];",'FAIR verification');
await expectFail('removing box 22 after the approval fails',F+"delete f.reviewed;",'FAIR approval');
r=await run(([id])=>{const s=structuredClone(state),o=s.orders.find(x=>x.id===id),f=o.fair;const signed=f.verified.manifest.subject;const has=Object.hasOwn(signed,'rawReasons');const sub={...signed,rawReasons:['Mfg. process change']};f.verified={...f.verified,manifest:MES.signManifest(s,f.verified.manifest.meaning,sub,f.verified.at)};const sg=f.verified.manifest.signer;f.verified.by={...f.verified.by,name:sg.name,credentialId:sg.credentialId};const v=MES.verifyManifests(s);return {has,drift:v.failures.filter(x=>/FAIR verification/.test(x.where)).map(x=>x.reason)};},[fair.id]);
ok('a FAIR verified by this build signs the raw reasons, and a raw reason that differs from the signed one fails even when Form 1 would show the same reason',r.has===true&&r.drift.some(x=>/reasons/.test(x)),JSON.stringify(r));
await expectFail('removing the Skyryse QA approval from an Approved FAIR fails',F+"f.approved=null;",'FAIR approval');
await expectFail('removing the verification from a Verified or Approved FAIR fails',F+"f.verified=null;",'FAIR verification');
await expectFail('changing when the FAIR was verified fails',F+"f.verified.at='2026-01-01T00:00:00.000Z';",'FAIR verification');
await expectFail('deleting the signed content of a current FAIR verification fails rather than skipping the content check',F+"delete f.verified.manifest.subject;f.chars=[];",'FAIR verification');
r=await run(([id])=>{const s=structuredClone(state),f=s.orders.find(o=>o.id===id).fair;const at='2026-09-22T10:00:00.000Z';f.verified={...f.verified,at,manifest:{...f.verified.manifest,at}};delete f.verified.manifest.subject;delete f.verified.manifest.build;const v=MES.verifyManifests(s);return v.failures.filter(x=>/FAIR verification/.test(x.where)).map(x=>x.reason);},[fair.id]);
ok('a FAIR verified before manifests stored their subject (no subject, verified before 2026-09-27) is not failed for the missing subject',!r.some(x=>/lost its signed FAIR content/.test(x)),JSON.stringify(r));
r=await run(([id])=>{const s=structuredClone(state),f=s.orders.find(o=>o.id===id).fair;const at='2026-09-22T10:00:00.000Z';f.verified={...f.verified,at,manifest:{...f.verified.manifest,at,build:f.verified.manifest.build||MES.buildStamp()}};delete f.verified.manifest.subject;const v=MES.verifyManifests(s);return v.failures.filter(x=>/FAIR verification/.test(x.where)).map(x=>x.reason);},[fair.id]);
ok('a subjectless FAIR verification that carries a build stamp fails even when backdated (build stamps and stored subjects arrived together)',r.some(x=>/lost its signed FAIR content/.test(x)),JSON.stringify(r));
await expectFail('changing who gave the Skyryse QA approval fails',F+"f.approved.by={...f.approved.by,credentialId:'ACCT-other',name:'Someone Else'};",'FAIR approval');
r=await run(([id])=>{const s=structuredClone(state),f=s.orders.find(o=>o.id===id).fair;f.approved=null;return {valid:MES.validate(s)};},[fair.id]);
ok('MES.validate refuses an Approved FAIR with no approval record',r.valid===false,JSON.stringify(r));
r=await run(([id])=>{const mk=at=>{const s=structuredClone(state),f=s.orders.find(o=>o.id===id).fair;const sub={fair:f.approved.manifest.subject.fair,verified:f.verified.manifest.hash};f.approved={...f.approved,by:{...f.approved.by},at,manifest:MES.signManifest(s,'AS9102 FAIR Skyryse QA approval',sub,at)};delete f.approved.by.override;f.reviewed=null;const v=MES.verifyManifests(s);return v.failures.filter(x=>/FAIR approval/.test(x.where)).length;};return {before:mk('2026-09-20T10:00:00.000Z'),after:mk('2026-09-28T10:00:00.000Z')};},[fair.id]);
ok('an approval from before box 22 was mandatory may lack box 22; one recorded after cannot',r.before===0&&r.after>0,JSON.stringify(r));
r=await run(([id])=>{const s=structuredClone(state),f=s.orders.find(o=>o.id===id).fair;const at='2026-09-28T10:00:00.000Z',sub={fair:f.approved.manifest.subject.fair,verified:f.verified.manifest.hash};f.approved={...f.approved,at,manifest:MES.signManifest(s,'AS9102 FAIR Skyryse QA approval',sub,'2026-09-20T10:00:00.000Z')};f.reviewed=null;const v=MES.verifyManifests(s);return v.failures.filter(x=>/FAIR approval/.test(x.where)).map(x=>x.reason);},[fair.id]);
ok('backdating only the approval manifest time does not let a post-cutoff approval drop box 22',r.some(x=>/box 22 is missing/.test(x))&&r.some(x=>/does not match the approval signature/.test(x)),JSON.stringify(r));
await expectFail('removing the FAIR verification manifest fails',F+"delete f.verified.manifest;",'FAIR verification');
await expectFail('removing the Skyryse QA approval manifest fails',F+"delete f.approved.manifest;",'FAIR approval');
await expectFail('removing the box 22 manifest fails',F+"delete f.reviewed.manifest;",'FAIR box 22');
await expectFail('changing the recorded FAIR verifier away from the verification signer fails',F+"f.verified.by={...f.verified.by,credentialId:'ACCT-other'};",'FAIR verification');
r=await run(([id])=>{const s=structuredClone(state),f=s.orders.find(o=>o.id===id).fair;const old=MES.signManifest(s,'AS9102 FAIR reviewed and approved (blocks 22 and 23)',{fair:f.reviewed.manifest.subject.fair,verified:f.verified.manifest.hash},f.reviewed.at);delete old.subject;f.reviewed={...f.reviewed,by:{...f.reviewed.by},manifest:old};delete f.reviewed.by.override;f.approved=null;f.status='Verified';const v=MES.verifyManifests(s);return {ok:v.ok,failures:v.failures.filter(x=>/FAIR/.test(x.where))};},[fair.id]);
ok('a box 22 signed before manifest subjects were stored (old form, no subject) still verifies',r.failures.length===0,JSON.stringify(r));
await expectFail('replacing the box 22 signature after the approval fails',F+"f.reviewed.manifest={...f.reviewed.manifest,hash:'0'.repeat(64)};",'FAIR');
await expectFail('a box 22 that does not chain to the verified FAIR fails',F+"f.reviewed.manifest=MES.signManifest(s,'AS9102 FAIR reviewed and approved (blocks 22 and 23)',{fair:'FAIR-OTHER',verified:f.verified.manifest.hash},f.reviewed.at);",'FAIR box 22');
r=await run(([id])=>{const bad=edit=>{const s=structuredClone(state),f=s.orders.find(o=>o.id===id).fair;edit(f);return MES.validate(s);};return {emptySigner:bad(f=>{f.reviewed.manifest={...f.reviewed.manifest,signer:{}};}),otherSigner:bad(f=>{f.reviewed.manifest={...f.reviewed.manifest,signer:{...f.reviewed.manifest.signer,credentialId:'ACCT-other'}};}),otherTime:bad(f=>{f.reviewed.manifest={...f.reviewed.manifest,at:'2020-01-01T00:00:00.000Z'};}),emptyManifest:bad(f=>{f.reviewed.manifest={};}),noManifest:bad(f=>{delete f.reviewed.manifest;}),noSigner:bad(f=>{f.reviewed.by=null;}),badTime:bad(f=>{f.reviewed.at='yesterday';}),onOpen:bad(f=>{f.status='Open';f.verified=null;f.approved=null;}),ok:MES.validate(state)};},[fair.id]);
ok('box 22 without its signature manifest is refused by validation',r.noManifest===false,JSON.stringify(r));
ok('box 22 with an empty or malformed manifest is refused by validation',r.emptyManifest===false,JSON.stringify(r));
ok('box 22 whose manifest signer is empty or another person, or whose manifest time differs, is refused by validation',r.emptySigner===false&&r.otherSigner===false&&r.otherTime===false,JSON.stringify(r));
ok('box 22 without a named signer is refused by validation',r.noSigner===false,JSON.stringify(r));
ok('box 22 without a valid time is refused by validation',r.badTime===false,JSON.stringify(r));
ok('box 22 on a FAIR that is not verified is refused by validation',r.onOpen===false,JSON.stringify(r));
ok('the signed workspace itself validates',r.ok===true,JSON.stringify(r));
r=await run(([id])=>{const s=structuredClone(state),f=s.orders.find(o=>o.id===id).fair;if(!f.reviewed)return {none:true};f.reviewed={...f.reviewed,by:{...f.reviewed.by,name:'Someone Else'}};return {valid:MES.validate(s)};},[fair.id]);
ok('box 22 whose recorded reviewer name differs from its signature is refused by validation',r.valid===false,JSON.stringify(r));
r=await run(([id])=>{const s=structuredClone(state),o=s.orders.find(o=>o.id===id),f=o.fair;f.fai=undefined;o.fai={...(o.fai||{}),required:true,reason:'First work order from MWI-0001 Rev A.',wi:(o.fai&&o.fai.wi)||'MWI-0001|A',at:(o.fai&&o.fai.at)||new Date().toISOString(),by:(o.fai&&o.fai.by)||f.verified.by};f.reasons=['Mfg. process change'];const sub={...f.verified.manifest.subject,form1:{...f.verified.manifest.subject.form1,reasons:['Mfg. process change']}};delete sub.rawReasons;f.verified={...f.verified,manifest:MES.signManifest(s,f.verified.manifest.meaning,sub,f.verified.at)};f.status='Verified';f.reviewed=null;f.approved=null;const v=MES.verifyManifests(s);return {ok:v.ok,failures:v.failures.filter(x=>/FAIR/.test(x.where))};},[fair.id]);
ok('a FAIR verified before reason normalization (raw reasons signed) still verifies',r.ok===true||r.failures.length===0,JSON.stringify(r));
r=await run(([id])=>{const s=structuredClone(state),f=s.orders.find(o=>o.id===id).fair;f.status='Verified';f.approved=null;f.reviewed=null;return {valid:MES.validate(s)};},[fair.id]);
ok('a Verified FAIR with box 22 cleared (null) still validates as a record',r.valid===true,JSON.stringify(r));
// FAIR signatures made by this build bind the recorded inspection stamp and who signed and when, inside the hash.
r=await run(([id])=>{const f=state.orders.find(o=>o.id===id).fair;return {v:['verifierStamp','signedAt'].every(k=>Object.hasOwn(f.verified.manifest.subject,k)),r:['reviewerStamp','signedAt'].every(k=>Object.hasOwn(f.reviewed.manifest.subject,k)),a:['stamp','signedAt'].every(k=>Object.hasOwn(f.approved.manifest.subject,k))};},[fair.id]);
ok('the FAIR verification, box 22 and Skyryse QA approval sign the inspection stamp and the signer and time',r.v&&r.r&&r.a,JSON.stringify(r));
await expectFail('adding an override to the recorded FAIR verifier after signing fails',F+"f.verified.by={...f.verified.by,override:{kind:'Support Access override',reason:'Added later.'}};",'FAIR verification');
await expectFail('adding an override to the recorded box 22 reviewer after signing fails',F+"f.reviewed.by={...f.reviewed.by,override:{kind:'Support Access override',reason:'Added later.'}};",'FAIR box 22');
await expectFail('adding an override to the recorded Skyryse QA approver after signing fails',F+"f.approved.by={...f.approved.by,override:{kind:'Support Access override',reason:'Added later.'}};",'FAIR approval');
await expectFail('changing the FAIR verifier inspection stamp after signing fails',F+"f.verified.by={...f.verified.by,stamp:{number:'Q-999',type:'Quality'}};",'FAIR verification');
await expectFail('changing the box 22 reviewer inspection stamp after signing fails',F+"f.reviewed.by={...f.reviewed.by,stamp:{number:'Q-999',type:'Quality'}};",'FAIR box 22');
await expectFail('changing the Skyryse QA approver inspection stamp after signing fails',F+"f.approved.by={...f.approved.by,stamp:{number:'Q-999',type:'Quality'}};",'FAIR approval');
await expectFail('#313 backdating the Skyryse QA approval together with its manifest time fails',F+"const at='2026-09-20T00:00:00.000Z';f.approved.at=at;f.approved.manifest.at=at;",'FAIR approval');
await expectFail('#314 replacing the Skyryse QA approver together with the manifest signer fails',F+"const o={name:'Someone Else',role:'Quality Engineer',credentialId:'ACCT-other'};f.approved.by={...f.approved.by,...o};f.approved.manifest.signer={...f.approved.manifest.signer,...o};",'FAIR approval');
await expectFail('changing the FAIR verification time together with its manifest time fails',F+"const at='2026-09-28T00:00:00.000Z';f.verified.at=at;f.verified.manifest.at=at;",'FAIR verification');
await expectFail('#363 a current FAIR verification made to look older (signed content and build stamp deleted, both times moved back, content edited) fails at box 22 and the approval',F+"const at='2026-09-22T10:00:00.000Z';delete f.verified.manifest.subject;delete f.verified.manifest.build;f.verified.at=at;f.verified.manifest.at=at;f.comments='Edited after verification.';",'FAIR');
r=await run(([id])=>{const s=structuredClone(state),f=s.orders.find(o=>o.id===id).fair;const at='2026-09-22T10:00:00.000Z';delete f.verified.manifest.subject;delete f.verified.manifest.build;f.verified.at=at;f.verified.manifest.at=at;return MES.verifyManifests(s).failures.map(x=>x.where);},[fair.id]);
ok('the backdated verification breaks both the box 22 and the Skyryse QA approval signatures, which bind the verification time',r.some(w=>/FAIR box 22$/.test(w))&&r.some(w=>/FAIR approval$/.test(w)),JSON.stringify(r));
// #479: a box 22 and approval signed with the stamp and signer forms but without verifiedAt keep that form and still verify.
r=await run(([id])=>{const s=structuredClone(state),o=s.orders.find(x=>x.id===id),f=o.fair;const rb=f.reviewed,ab=f.approved;const sb=(by,at)=>({signer:{name:by.name??null,role:by.role??null,credentialId:by.credentialId??null},signedAt:at});const rsub={fair:rb.manifest.subject.fair,verified:f.verified.manifest.hash,reviewer:rb.by.credentialId,reviewedAt:rb.at,reviewerStamp:rb.by.stamp??null,...sb(rb.by,rb.at)};f.reviewed={...rb,by:{...rb.by},manifest:{...MES.signManifest(s,rb.manifest.meaning,rsub,rb.at),signer:rb.manifest.signer}};delete f.reviewed.by.override;const asub={fair:ab.manifest.subject.fair,verified:f.verified.manifest.hash,reviewed:f.reviewed.manifest.hash,stamp:ab.by.stamp??null,...sb(ab.by,ab.at)};f.approved={...ab,by:{...ab.by},manifest:{...MES.signManifest(s,ab.manifest.meaning,asub,ab.at),signer:ab.manifest.signer}};delete f.approved.by.override;return MES.verifyManifests(s).failures.filter(x=>x.where.startsWith(id)).map(x=>x.where+': '+x.reason);},[fair.id]);
ok('#479 a box 22 and approval signed without verifiedAt are recomputed in that form and still verify',r.length===0,JSON.stringify(r));
await expectFail('changing the box 22 time together with its manifest time fails',F+"const at='2026-09-28T00:00:00.000Z';f.reviewed.at=at;f.reviewed.manifest.at=at;",'FAIR box 22');
const fairJson=await run(()=>JSON.stringify(state));

// ---- the CAR closure, from the 150-order regression set ----
await open('demo_qa150_publish.html','master');
r=await run(()=>{const v=MES.verifyManifests(state);return {ok:v.ok,failures:v.failures};});
ok('the 150-order regression workspace verifies',r.ok===true,JSON.stringify(r.failures));
const rel=await run(()=>{const o=state.orders.find(o=>o.releaseApproval&&o.releaseApproval.manifest&&['Kitting','Building'].includes(o.status)&&o.operations.some(op=>!op.done&&!op.fromStandardRework));return o?{id:o.id,op:o.operations.filter(op=>!op.done&&!op.fromStandardRework).pop().id}:null;});
ok('fixture: a pre-release-approved order in Kitting or Building',!!rel,String(rel));
r=await run(([rel])=>{const s=structuredClone(state),o=s.orders.find(x=>x.id===rel.id),op=o.operations.find(x=>x.id===rel.op);const e=MES.editOrderOperation(s,rel.id,rel.op,{title:op.title+' (revised)',description:op.description,buyoffType:op.buyoffType,requiresTooling:!!op.requiresTooling,steps:(op.steps||[]).map(x=>x.title).join('\n')||'Step one',reason:'Clarify the operation title.'});const v=MES.verifyManifests(s);return {edit:e.ok,message:e.message,verify:v.ok,failures:v.failures};},[rel]);
ok('an authorized operation edit on a pre-release-approved order still verifies (the sequence change goes to QA, not to verification)',r.edit===true&&r.verify===true,JSON.stringify(r));
const car=await run(()=>{const c=(state.maneuver.cars||[]).find(c=>c.closure&&c.closure.manifest);return c&&c.id;});
ok('fixture: a closed CAR',!!car,String(car));
const C=`const c=s.maneuver.cars.find(c=>c.id==='${car}');`;
await expectFail('editing the CAR root cause after closure fails',C+"c.rootCause.statement='Edited after closure.';",`${car} closure`);
await expectFail('editing a CAR action after closure fails',C+"c.actions[0].description='Edited after closure.';",`${car} closure`);
await expectFail('editing the CAR effectiveness result after closure fails',C+"c.effectiveness.result='Not effective';",`${car} closure`);
await expectFail('editing the CAR closure statement after closure fails',C+"c.closure.note='Edited.';",`${car} closure`);
await expectFail('changing who closed the CAR fails',C+"c.closure.by={...c.closure.by,credentialId:'ACCT-other',name:'Someone Else'};",`${car} closure`);
await expectFail('changing when the CAR was closed fails',C+"c.closure.at='2026-01-01T00:00:00.000Z';",`${car} closure`);
await expectFail('removing the CAR closure manifest fails',C+"delete c.closure.manifest;",`${car} closure`);

const F0="const f=s.orders.find(o=>o.fair&&o.fair.status==='Approved'&&o.fair.approved).fair;";
// Standalone and offline saves run MES.validate, not verifyManifests: a missing signed record or signature is refused there too.
r=await run(([json,src])=>{const base=JSON.parse(json),out={};for(const [k,e] of Object.entries(src)){const s=structuredClone(k==='partialCar'?state:base);try{(new Function('s',e))(s);out[k]=MES.validate(s);}catch(x){out[k]='err '+x.message;}}const s=structuredClone(base);(new Function('s',src.aqi))(s);out.diagnose=(MES.diagnose(s)||{}).detail||'';out.clean=MES.validate(structuredClone(base));return out;},[confJson,{aqi:pkg+"p.aqi=null;",dar:pkg+"delete p.darApproval.manifest;",form:pkg+"delete p.form.prepared.manifest;",mrb:board+"delete m.decision.manifest;",nc:stock+"delete t.resolution.manifest;",emptyAqi:pkg+"p.aqi.manifest={};",emptyMrb:board+"m.decision.manifest={};",partialCar:C+"delete c.closure.manifest.hash;",emptyFair:F0+"f.approved.manifest={};",emptyNc:stock+"t.resolution.manifest={};"}]);
ok('MES.validate (standalone load and save) refuses a removed AQI signature, DAR manifest, 8130-9 manifest, MRB manifest or NC approval manifest',r.clean===true&&['aqi','dar','form','mrb','nc'].every(k=>r[k]===false),JSON.stringify(r));
ok('MES.validate refuses an empty or partial manifest object in place of a signature (AQI, MRB, CAR, FAIR approval, NC approval)',['emptyAqi','emptyMrb','partialCar','emptyFair','emptyNc'].every(k=>r[k]===false),JSON.stringify(r));
ok('the validation diagnosis names the incomplete signed record',/A signed record is incomplete at .*AQI signature/.test(r.diagnose),JSON.stringify(r.diagnose));

// ---- a CAR closure signed by this build also binds each action's evidence and completer ----
r=await run(([car])=>{const s=structuredClone(state),c=s.maneuver.cars.find(c=>c.id===car);c.actions.forEach(a=>{a.evidence=a.evidence||'Work instruction revised and trained.';a.completedBy=a.completedBy||{name:'Kai Quality',role:'Quality Engineer',credentialId:'ACCT-kqe'};});const sg=MES.signManifest(s,'Corrective action closure',{},c.closure.at).signer;c.closure.by={name:sg.name,role:sg.role,credentialId:sg.credentialId};c.closure.manifest=MES.signManifest(s,'Corrective action closure',MES.carClosureSubject(c,c.closure.note,true,c.closure.by,c.closure.at),c.closure.at);const ok0=MES.verifyManifests(s).ok;const edit=f=>{const x=structuredClone(s),y=x.maneuver.cars.find(z=>z.id===car);f(y);const v=MES.verifyManifests(x);return v.failures.some(z=>z.where.includes(`${car} closure`));};return {before:ok0,marker:c.closure.manifest.subject.actionEvidence===true,evidence:edit(y=>{y.actions[0].evidence='Replaced after closure.';}),completer:edit(y=>{y.actions[0].completedBy={...y.actions[0].completedBy,credentialId:'ACCT-other'};}),strip:edit(y=>{y.actions[0].evidence='Replaced after closure.';delete y.closure.manifest.subject.actions[0].evidence;})};},[car]);
ok('a CAR closure signed by this build binds each action\'s evidence and completer: it verifies, and replacing either afterwards fails',r.before===true&&r.marker===true&&r.evidence===true&&r.completer===true,JSON.stringify(r));
ok('editing the stored closure subject does not let replaced evidence pass (the form follows the hashed marker)',r.strip===true,JSON.stringify(r));
r=await run(([car])=>{const s=structuredClone(state),c=s.maneuver.cars.find(c=>c.id===car);const sg=MES.signManifest(s,'Corrective action closure',{},c.closure.at).signer;c.closure.by={name:sg.name,role:sg.role,credentialId:sg.credentialId};c.closure.manifest=MES.signManifest(s,'Corrective action closure',MES.carClosureSubject(c,c.closure.note,true,c.closure.by,c.closure.at),c.closure.at);const ok0=MES.verifyManifests(s).ok;const edit=f=>{const x=structuredClone(s),y=x.maneuver.cars.find(z=>z.id===car);f(y);return MES.verifyManifests(x).failures.some(z=>z.where.includes(`${car} closure`));};return {before:ok0,containment:edit(y=>{y.containment={...(y.containment||{}),note:'Edited after closure.'};}),rootCause:edit(y=>{y.rootCause={...y.rootCause,whys:['Edited after closure.']};}),verification:edit(y=>{y.verification={...y.verification,note:'Edited after closure.'};}),effectiveness:edit(y=>{y.effectiveness={...y.effectiveness,note:'Edited after closure.'};}),completerName:(()=>{const x=structuredClone(s),y=x.maneuver.cars.find(z=>z.id===car);if(!y.actions.some(a=>a.completedBy))return 'none';y.actions.find(a=>a.completedBy).completedBy={...y.actions.find(a=>a.completedBy).completedBy,name:'Someone Else'};return MES.verifyManifests(x).failures.some(z=>z.where.includes(`${car} closure`));})(),dueDate:edit(y=>{y.actions[0].dueDate='2030-01-01';})};},[car]);
ok('a CAR closure signed by this build binds the containment, the full root cause analysis, and the verification and effectiveness records',r.before===true&&r.containment&&r.rootCause&&r.verification&&r.effectiveness,JSON.stringify(r));
ok('a CAR closure signed by this build binds each action due date and the completer\'s full identity',r.dueDate===true&&r.completerName===true,JSON.stringify(r));
r=await run(([json,mrb])=>{const s=JSON.parse(json),m=s.maneuver.mrb.find(x=>x.id===mrb),d=m.decision;const sg=MES.signManifest(s,d.manifest.meaning,{},d.at).signer;d.by={name:sg.name,role:sg.role,credentialId:sg.credentialId};d.manifest=MES.signManifest(s,d.manifest.meaning,MES.mrbDecisionSubject(m,d.status,d.note,true,d.by,d.at),d.at);const ok0=MES.verifyManifests(s).ok;const edit=f=>{const x=structuredClone(s),y=x.maneuver.mrb.find(z=>z.id===mrb);f(y);return MES.verifyManifests(x).failures.some(z=>z.where.includes(`${mrb} board decision`));};return {before:ok0,marker:d.manifest.subject.rationale===true,voteNote:edit(y=>{y.votes[0].note='Edited after the decision.';}),summary:edit(y=>{y.summary='Edited after the decision.';}),voterName:edit(y=>{y.votes[0].by={...y.votes[0].by,name:'Someone Else'};})};},[confJson,mrb]);
ok('an MRB decision signed by this build binds each vote rationale and the board summary',r.before===true&&r.marker===true&&r.voteNote===true&&r.summary===true,JSON.stringify(r));
ok('an MRB decision signed by this build binds each voter\'s full identity',r.voterName===true,JSON.stringify(r));
r=await run(([json,mrb,car])=>{const at='2026-01-01T00:00:00.000Z',other={name:'Someone Else',role:'Quality Engineer',credentialId:'ACCT-other'};const s=JSON.parse(json),m=s.maneuver.mrb.find(x=>x.id===mrb),d=m.decision;const sg=MES.signManifest(s,d.manifest.meaning,{},d.at).signer;d.by={name:sg.name,role:sg.role,credentialId:sg.credentialId};d.manifest=MES.signManifest(s,d.manifest.meaning,MES.mrbDecisionSubject(m,d.status,d.note,true,d.by,d.at),d.at);const q=structuredClone(state),c=q.maneuver.cars.find(x=>x.id===car);c.closure.by={name:sg.name,role:sg.role,credentialId:sg.credentialId};c.closure.manifest=MES.signManifest(q,'Corrective action closure',MES.carClosureSubject(c,c.closure.note,true,c.closure.by,c.closure.at),c.closure.at);const fails=(ws,f,where)=>{const x=structuredClone(ws);f(x);return MES.verifyManifests(x).failures.some(z=>z.where.includes(where));};const md=x=>x.maneuver.mrb.find(y=>y.id===mrb).decision,cc=x=>x.maneuver.cars.find(y=>y.id===car).closure;return {pedigree:fails(s,x=>{const b=x.maneuver.mrb.find(y=>y.id===mrb);b.pedigree=b.pedigree==='Production'?'Development':'Production';},`${mrb} board decision`),carDescription:fails(q,x=>{x.maneuver.cars.find(y=>y.id===car).description='A different problem statement.';},`${car} closure`),carSource:fails(q,x=>{const y=x.maneuver.cars.find(z=>z.id===car);y.sourceType=y.sourceType==='Observation'?'NC':'Observation';},`${car} closure`),carOwner:fails(q,x=>{const y=x.maneuver.cars.find(z=>z.id===car);y.owner={...y.owner,name:'Someone Else',credentialId:'ACCT-other'};},`${car} closure`),carDue:fails(q,x=>{x.maneuver.cars.find(z=>z.id===car).dueDate='2030-01-01';},`${car} closure`),carMeaning:fails(q,x=>{cc(x).manifest.meaning='Corrective action cancelled';},`${car} closure`),mrbOk:MES.verifyManifests(s).ok,carOk:MES.verifyManifests(q).ok,mrbTime:fails(s,x=>{md(x).at=at;md(x).manifest.at=at;},`${mrb} board decision`),mrbSigner:fails(s,x=>{md(x).by={...md(x).by,...other};md(x).manifest.signer={...md(x).manifest.signer,...other};},`${mrb} board decision`),carTime:fails(q,x=>{cc(x).at=at;cc(x).manifest.at=at;},`${car} closure`),carSigner:fails(q,x=>{cc(x).by={...cc(x).by,...other};cc(x).manifest.signer={...cc(x).manifest.signer,...other};},`${car} closure`)};},[confJson,mrb,car]);
ok('an MRB decision and a CAR closure signed by this build bind who signed and when: changing them together with the manifest metadata fails',r.mrbOk&&r.carOk&&r.mrbTime&&r.mrbSigner&&r.carTime&&r.carSigner,JSON.stringify(r));
ok('an MRB decision signed by this build binds the pedigree',r.pedigree===true,JSON.stringify(r));
ok('a CAR closure signed by this build binds the problem statement, source, owner and due date',r.carDescription&&r.carSource&&r.carOwner&&r.carDue,JSON.stringify(r));
ok('relabelling the CAR closure signature meaning fails',r.carMeaning===true,JSON.stringify(r));
r=await run(([car])=>{const q=structuredClone(state),c=q.maneuver.cars.find(x=>x.id===car);const sg=MES.signManifest(q,'Corrective action closure',{},c.closure.at).signer;c.closure.by={name:sg.name,role:sg.role,credentialId:sg.credentialId};const sub={...MES.carClosureSubject(c,c.closure.note,true,c.closure.by,c.closure.at)};['description','sourceType','link','owner','dueDate'].forEach(k=>delete sub[k]);c.closure.manifest=MES.signManifest(q,'Corrective action closure',sub,c.closure.at);return MES.verifyManifests(q).failures.filter(f=>f.where.includes(car)).map(f=>f.reason);},[car]);
ok('a CAR closure signed with signer and time but before the request identity was bound still verifies',r.length===0,JSON.stringify(r));

// ---- verification fails closed: a manifest whose stored subject was signed by this build is recomputed even when
// the live record adds or drops a key ----
r=await run(([car])=>{const s=structuredClone(state),c=s.maneuver.cars.find(c=>c.id===car);const subject={id:c.id,title:c.title,severity:c.severity,rootCause:c.rootCause.statement,actions:c.actions.map(a=>({id:a.id,description:a.description,completedAt:a.completedAt})),verification:c.verification.at,effectiveness:c.effectiveness.result,note:c.closure.note};c.closure.manifest=MES.signManifest(s,'Corrective action closure',subject,c.closure.at);const sg=c.closure.manifest.signer;c.closure.by={name:sg.name,role:sg.role,credentialId:sg.credentialId};const ok0=MES.verifyManifests(s).ok;c.rootCause=null;const v=MES.verifyManifests(s);return {before:ok0,ok:v.ok,where:v.failures.map(f=>f.where)};},[car]);
ok('a freshly signed CAR closure verifies, and removing its root cause afterwards fails',r.before===true&&r.ok===false&&r.where.some(w=>w.includes(`${car} closure`)),JSON.stringify(r));

// ---- production validation refuses a box 22 signed by the verifier (the demo lifts this rule, D-33) ----
await p.goto('file://'+FIXTURES+'publish.html');await p.waitForTimeout(1200);
r=await run(([json,id])=>{const base=JSON.parse(json),f=base.orders.find(o=>o.id===id).fair;const other={...f.reviewed.by,credentialId:'ACCT-second',name:'Second Reviewer'};const mk=by=>{const s=structuredClone(base),g=s.orders.find(o=>o.id===id).fair;g.reviewed={...g.reviewed,by,manifest:{...g.reviewed.manifest,signer:{...g.reviewed.manifest.signer,credentialId:by.credentialId,name:by.name}}};return s;};const self=mk({...f.verified.by});const second=mk(other);const fv=s=>MES.validate(s);const moved=mk({...f.verified.by});moved.orders.find(o=>o.id===id).fair.verified.by={...f.verified.by,credentialId:'ACCT-moved'};return {sameCred:f.verified.by.credentialId,second:fv(second),self:fv(self),moved:fv(moved)};},[fairJson,fair.id]);
ok('in production, validation accepts a box 22 signed by a second person and refuses one signed by the verifier',r.second===true&&r.self===false,JSON.stringify(r));
ok('in production, validation refuses a box 22 signed by the verification signer even when the recorded verifier was changed',r.moved===false,JSON.stringify(r));
// ---- production: the AQI self-signature flag must match who completed the 8130-9 (the demo lifts this, see DEMO_DEVIATIONS) ----
await p.goto('file://'+FIXTURES+'publish.html');await p.waitForTimeout(1200);
r=await run(([json,c])=>{const base=JSON.parse(json);const mk=f=>{const s=structuredClone(base),p=s.orders.find(o=>o.id===c.id).conformity.find(x=>x.serial===c.serial);f(p);const v=MES.verifyManifests(s);return v.failures.filter(x=>/AQI signature/.test(x.where)).map(x=>x.reason);};return {clean:mk(()=>{}),samePerson:mk(p=>{p.form.prepared.by={...p.aqi.by};p.form.prepared.manifest={...p.form.prepared.manifest,signer:{...p.form.prepared.manifest.signer,credentialId:p.aqi.by.credentialId}};})};},[confJson,conf]);
ok('in production, an 8130-9 completed and AQI-signed by the same person without the self-signature record fails verification',r.clean.length===0&&r.samePerson.some(x=>/self-signature/.test(x)),JSON.stringify(r));
// A saved copy whose signed content was edited outside the app is not opened.
await p.goto('file://'+FIXTURES+'demo_publish.html');await p.waitForTimeout(1500);
// The demo build keeps its workspace under its own key (a demo deviation).
const key='skyryse-mes-work-order-qa100-v1';
ok('fixture: the demo keeps its workspace in browser storage',await run(k=>!!localStorage.getItem(k),key),key);
await run(([json,key])=>localStorage.setItem(key,json),[confJson,key]);await p.reload();await p.waitForTimeout(2500);
// ---- standalone save and load recompute every signature (#315) ----
// A save that would break a signature is refused and rolled back.
r=await run(([mrb])=>{const before=JSON.stringify(state);const m=state.maneuver.mrb.find(x=>x.id===mrb);m.decision.note='Edited after the decision.';const saved=save();const after=JSON.stringify(state);return {saved,rolledBack:after===before};},[mrb]);
const r2=await run(([mrb])=>{const next=structuredClone(state);next.maneuver.mrb.find(x=>x.id===mrb).decision.note='Edited after the decision.';try{mediaCommit(next);return {thrown:false};}catch(e){return {thrown:true,message:e.message};}},[mrb]);
ok('the media write path refuses a workspace whose signature would fail verification',r2.thrown===true&&/would fail verification at .*board decision/.test(r2.message),JSON.stringify(r2));
ok('a standalone save that would break a signature is refused and rolled back',r.saved===false&&r.rolledBack===true,JSON.stringify(r));
await run(([json,mrb,key])=>{const s=JSON.parse(json),m=s.maneuver.mrb.find(x=>x.id===mrb);m.decision.note='Edited outside the app.';localStorage.setItem(key,JSON.stringify(s));},[confJson,mrb,key]);
await p.reload();await p.waitForTimeout(2500);
r=await run(()=>{const box=document.querySelector('#storage-alert');return {hidden:box?box.hidden:null,text:box?box.textContent:''};});
ok('a saved workspace whose signed content was edited outside the app is not opened, and the alert names the record',r.hidden===false&&/failed verification at .*board decision/.test(r.text),JSON.stringify(r));
// A saved copy that needs the one-time calibration seal (or start marker) and also has a damaged signature is refused
// before the seal is written back, so the stored copy is left exactly as it was.
const damagedUnsealed=await run(([json,mrb,key])=>{const s=JSON.parse(json),m=s.maneuver.mrb.find(x=>x.id===mrb);const rc=MES.recordCalibration(s,{tag:'SEAL-A',description:'DIGITAL CALIPER',torque:false,serial:'',calibratedAt:'2026-09-28',expires:'2027-09-28',status:'In Calibration',location:'',note:'Lab cert 42'});if(!rc.ok)return {raw:'',needsSeal:false,rc};s.calibrationLog.forEach(e=>{delete e.previousHash;});delete s.calibrationLogHead;delete s.calibrationLogStart;m.decision.note='Edited outside the app.';const raw=JSON.stringify(s);const up=MES.upgrade(JSON.parse(raw));localStorage.setItem(key,raw);return {raw,needsSeal:!!(up&&(up.calibrationLogHead||up.calibrationLogStart))};},[confJson,mrb,key]);
ok('fixture: the damaged copy holds a calibration log from before the chain, so the load writes the one-time seal back',damagedUnsealed.needsSeal===true,JSON.stringify({needsSeal:damagedUnsealed.needsSeal,rc:damagedUnsealed.rc}));
await p.reload();await p.waitForTimeout(2500);
r=await run(([key,raw])=>{const box=document.querySelector('#storage-alert');return {hidden:box?box.hidden:null,text:box?box.textContent:'',unchanged:localStorage.getItem(key)===raw};},[key,damagedUnsealed.raw]);
ok('a saved copy that needs the calibration seal and fails verification is refused, and the stored copy is not changed',r.hidden===false&&/failed verification at .*board decision/.test(r.text)&&r.unchanged===true,JSON.stringify({hidden:r.hidden,text:r.text.slice(0,200),unchanged:r.unchanged}));
ok('no page errors',errs.length===0,errs.join(' | '));
console.log('errors',errs,'FAILS',JSON.stringify(fails));await b.close();
process.exit(fails.length?1:0);
