import assert from 'node:assert/strict';
import { chromium } from 'playwright';

const fixture = new URL('./fixtures/demo_qa150_publish.html', import.meta.url).href;
const browser = await chromium.launch(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {});
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 980 } });
  await context.addInitScript(() => {
    localStorage.setItem('skyryse-mes-auth-v1', JSON.stringify({ users: [{ username: 'admin', displayName: 'Flight Master', salt: 'test', hash: 'unused', role: 'admin', createdAt: new Date().toISOString() }] }));
    sessionStorage.setItem('skyryse-mes-session-v1', 'admin');
    sessionStorage.setItem('sk-boot-seen', '1');
  });
  const page = await context.newPage(), errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(fixture);
  await page.waitForFunction(() => window.__ready === true);
  await page.evaluate(() => { view = 'serials'; render(); });
  await page.getByRole('heading', { name: 'Serial numbers.' }).waitFor();
  await page.screenshot({ path: new URL('../artifacts/design/final/flight-control-serials-1440.png', import.meta.url).pathname });
  const rows = page.locator('.fr-serials tbody tr');
  assert.ok(await rows.count() > 0, 'the React register renders current serial assignment records');
  const first = rows.first(), serial = await first.locator('td').first().innerText();
  assert.ok(serial.trim(), 'serial numbers remain visible in the table');
  assert.equal(await first.locator('td').nth(1).innerText().then(v => v.includes('Rev')), true, 'part revision remains visible');
  await page.getByRole('textbox', { name: 'Search serial numbers' }).fill(serial.trim());
  assert.equal(await rows.count(), 1, 'search filters the current serial records');
  const density = page.locator('.fr-serials .fr-density');
  await density.click();
  assert.equal(await density.getAttribute('aria-pressed'), 'true', 'compact density can be selected');
  assert.ok((await page.locator('.fr-serials table').getAttribute('class')).includes('fr-compact'));
  await rows.first().locator('.fr-record-link').click();
  const drawer = page.locator('.fr-drawer[open]');
  await drawer.waitFor();
  assert.ok((await drawer.innerText()).includes(serial.trim()));
  await page.keyboard.press('Escape');
  await drawer.waitFor({ state: 'detached' });
  assert.equal(await rows.count(), 1, 'closing the drawer keeps the current search context');
  assert.equal(await page.evaluate(() => document.activeElement.matches('.fr-record-link')), true, 'closing the drawer returns focus to its serial row');
  await rows.first().locator('.fr-record-link').click();
  await drawer.waitFor();
  await drawer.getByRole('button', { name: 'Open traceability' }).click({ force: true });
  await page.getByRole('heading', { name: 'Traceability' }).waitFor();
  assert.ok((await page.locator('#trace-q').inputValue()).includes(serial.trim()), 'drawer trace action routes into the existing live trace report');
  await page.evaluate(() => { view = 'serials'; render(); });
  await page.getByRole('heading', { name: 'Serial numbers.' }).waitFor();
  const lotButton = page.locator('.fr-serials tbody tr td:nth-child(5) button').first();
  assert.ok(await lotButton.count() > 0, 'the fixture includes a lot-linked serial record');
  const lot = (await lotButton.innerText()).trim();
  await lotButton.click();
  await page.getByRole('heading', { name: 'Traceability' }).waitFor();
  assert.equal(await page.locator('#trace-q').inputValue(), lot, 'lot links open the existing traceability workflow');
  await page.evaluate(() => { view = 'serials'; render(); });
  await page.getByRole('heading', { name: 'Serial numbers.' }).waitFor();
  await page.locator('.fr-serials tbody tr').first().locator('.fr-record-link').click();
  await drawer.waitFor();
  await drawer.getByRole('button', { name: 'Open work order inventory' }).click({ force: true });
  await page.locator('body[data-view="order"]').waitFor();
  assert.equal(await page.evaluate(() => tab), 'inventory', 'drawer work-order action opens the existing inventory workflow');
  assert.deepEqual(errors, []);
  await context.close();
  console.log('React Flight Control serial register renders live records, search and density controls, accessible details and traceability routing.');
} finally { await browser.close(); }
