import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const {
  claudeApproved,
  changedFilesComplete,
  descriptionSha256,
  hasProtectedAutoMergeChange,
  hasUnresolvedImportant,
  isIndependentReviewer,
  isEligiblePullRequest,
  isImportantFinding,
  jinxApproved,
  latestCiSucceeded,
} = require('../.github/scripts/review-gate.cjs');

const head = 'a'.repeat(40);
const main = 'b'.repeat(40);
const pull = {
  title: 'Gate test PR', body: 'A description for this review.', state: 'open', draft: false,
  mergeable: true, base: { ref: 'main', sha: main }, head: { ref: 'feature', sha: head },
};
const descriptionSha = descriptionSha256(pull);

const jinxReview = {
  user: { login: 'jinx-reviewer' },
  submitted_at: '2026-09-27T12:00:00Z',
  state: 'COMMENTED',
  commit_id: head,
  body: 'Jinx verdict: No blockers\nReviewed head ' + head,
};
assert.equal(jinxApproved([jinxReview], 'jinx-reviewer', head), true);
assert.equal(jinxApproved([{ ...jinxReview, body: '**Jinx verdict:** No blockers\n\nReviewed by Jinx (Muse AI)' }], 'jinx-reviewer', head), true, 'markdown-emphasized Jinx verdict is accepted');
assert.equal(jinxApproved([jinxReview], 'jinx-reviewer', 'c'.repeat(40)), false, 'stale Jinx SHA refuses');
assert.equal(jinxApproved([{ ...jinxReview, state: 'APPROVED' }], 'jinx-reviewer', head), false, 'wrong Jinx review state refuses');
assert.equal(jinxApproved([{ ...jinxReview, body: 'No blockers in the first pass; still investigating.' }], 'jinx-reviewer', head), false, 'ambiguous Jinx wording refuses');
assert.equal(jinxApproved([jinxReview, { ...jinxReview, submitted_at: '2026-09-27T13:00:00Z', body: 'Jinx verdict: changes needed' }], 'jinx-reviewer', head), false, 'latest Jinx review wins');
assert.equal(isIndependentReviewer('jinx-reviewer', 'repo-owner'), true);
assert.equal(isIndependentReviewer('repo-owner', 'repo-owner'), false, 'PR author cannot self-approve as Jinx');
assert.equal(isIndependentReviewer('', 'repo-owner'), false, 'missing Jinx identity refuses');

const claudeComment = {
  user: { login: 'claude[bot]', type: 'Bot' },
  created_at: '2026-09-27T12:00:00Z',
  body: `Reviewed the requested changes.\n\nPR head SHA reviewed: ${head}\nMain SHA reviewed against: ${main}\nPR description SHA-256 reviewed: ${descriptionSha}\nClaude verdict: OK to merge\n\n---\n_Generated by Claude Code_`,
};
assert.equal(claudeApproved([claudeComment], head, main, descriptionSha), true);
assert.equal(claudeApproved([claudeComment], 'c'.repeat(40), main, descriptionSha), false, 'stale Claude head refuses');
assert.equal(claudeApproved([claudeComment], head, 'd'.repeat(40), descriptionSha), false, 'stale Claude base refuses');
assert.equal(claudeApproved([claudeComment], head, main, 'c'.repeat(64)), false, 'edited PR title or description invalidates Claude');
assert.equal(claudeApproved([{ ...claudeComment, user: { login: 'repo-owner', type: 'User' } }], head, main, descriptionSha), false, 'non-bot Claude signal refuses');
assert.equal(claudeApproved([{ ...claudeComment, body: claudeComment.body.replace('OK to merge', 'changes needed (1 important)') }], head, main, descriptionSha), false, 'negative Claude verdict refuses');
assert.equal(claudeApproved([claudeComment, { ...claudeComment, created_at: '2026-09-27T13:00:00Z', body: 'Claude verdict: changes needed (1 important)' }], head, main, descriptionSha), false, 'latest Claude verdict wins');

assert.equal(isImportantFinding('Important: CI gate bypass.'), true);
assert.equal(isImportantFinding('**Important:** CI gate bypass.'), true);
assert.equal(isImportantFinding('- **Important:** CI gate bypass.'), true);
assert.equal(isImportantFinding('1. **Important:** CI gate bypass.'), true);
assert.equal(isImportantFinding('> - **Important:** CI gate bypass.'), true);
assert.equal(isImportantFinding('**1. Important:** CI gate bypass.'), true);
assert.equal(isImportantFinding('**<sub><sub>![P1 Badge](https://img.shields.io/badge/P1-orange?style=flat)</sub></sub> Subscribe to ready-for-review events'), true);
assert.equal(isImportantFinding('**<sub><sub>![P0 Badge](https://img.shields.io/badge/P0-red?style=flat)</sub></sub> Critical merge bypass'), true);
assert.equal(isImportantFinding('No blocking issues.'), false);
assert.equal(hasUnresolvedImportant([{ isResolved: false, comments: [{ body: '- **Important:** still open' }] }]), true);
assert.equal(hasUnresolvedImportant([{ isResolved: false, comments: [{ body: '**![P1 Badge]** still open' }] }]), true);
assert.equal(hasUnresolvedImportant([{ isResolved: false, comments: [{ body: '**![P0 Badge]** critical issue' }] }]), true, 'P0 review findings block the merge');
assert.equal(hasUnresolvedImportant([{ isResolved: true, comments: [{ body: 'Important: addressed' }] }]), false);

assert.equal(isEligiblePullRequest(pull, main, 0), true);
assert.equal(isEligiblePullRequest({ ...pull, state: 'closed' }, main, 0), false, 'closed PR refuses');
assert.equal(isEligiblePullRequest({ ...pull, draft: true }, main, 0), false, 'draft PR refuses');
assert.equal(isEligiblePullRequest({ ...pull, base: { ref: 'release', sha: main } }, main, 0), false, 'wrong PR base refuses');
assert.equal(isEligiblePullRequest({ ...pull, base: { ref: 'main', sha: 'c'.repeat(40) } }, main, 0), false, 'moved base SHA refuses');
assert.equal(isEligiblePullRequest({ ...pull, mergeable: false }, main, 0), false, 'merge conflict refuses');
assert.equal(isEligiblePullRequest({ ...pull, mergeable: null }, main, 0), false, 'unknown merge state refuses');
assert.equal(isEligiblePullRequest(pull, main, 1), false, 'behind main refuses');

assert.equal(hasProtectedAutoMergeChange([{ filename: '.github/workflows/ci.yml' }]), true);
assert.equal(hasProtectedAutoMergeChange([{ filename: 'tests/allowed_skips.json' }]), true);
assert.equal(hasProtectedAutoMergeChange([{ filename: 'tests/test_frozen_contract.mjs' }]), true);
assert.equal(hasProtectedAutoMergeChange([{ filename: 'tests/test_review_gate.mjs' }]), true);
assert.equal(hasProtectedAutoMergeChange([{ filename: '.github/scripts/review-gate.cjs' }]), true);
assert.equal(hasProtectedAutoMergeChange([{ filename: 'tools/run-suites.mjs' }]), true);
assert.equal(hasProtectedAutoMergeChange([{ filename: '.github/disabled/ci.yml', previous_filename: '.github/workflows/ci.yml' }]), true, 'renaming a protected file refuses');
assert.equal(hasProtectedAutoMergeChange([{ filename: 'docs/CLAUDE_REVIEW_ROUTINE.md' }]), false);
assert.equal(changedFilesComplete([{ filename: 'a' }, { filename: 'b' }], 2), true);
assert.equal(changedFilesComplete([{ filename: 'a' }], 2), false, 'truncated file lists refuse');
assert.equal(changedFilesComplete([], undefined), false, 'missing expected file count refuses');

const ciRun = {
  event: 'pull_request',
  pull_requests: [{ number: 12, head: { sha: head } }],
  head_sha: head,
  created_at: '2026-09-27T12:00:00Z',
  conclusion: 'success',
};
assert.equal(latestCiSucceeded([ciRun], 12, head), true);
assert.equal(latestCiSucceeded([ciRun], 13, head), false, 'CI from another PR refuses');
assert.equal(latestCiSucceeded([{ ...ciRun, head_sha: 'c'.repeat(40) }], 12, head), false, 'CI from another head refuses');
assert.equal(latestCiSucceeded([{ ...ciRun, conclusion: 'failure' }], 12, head), false, 'failed latest CI refuses');

const mergeWorkflow = fs.readFileSync(path.join(root, '.github/workflows/auto-merge-reviewed-pr.yml'), 'utf8');
const claudeWorkflow = fs.readFileSync(path.join(root, '.github/workflows/claude-pr-review.yml'), 'utf8');
assert.match(mergeWorkflow, /pull_request_target:\s*\n\s*types: \[opened, synchronize, ready_for_review, reopened, edited\]/);
assert.doesNotMatch(mergeWorkflow, /^\s*pull_request_review:/m, 'privileged gate avoids PR merge-branch review event');
assert.match(mergeWorkflow, /cron: '\*\/5 \* \* \* \*'/, 'scheduled sweep retries after reviews and thread resolution');
assert.match(mergeWorkflow, /ref: refs\/heads\/main/, 'gate code is checked out from trusted main');
assert.match(claudeWorkflow, /environment:\s*\n\s*name: claude-review/);
assert.match(claudeWorkflow, /PR description SHA-256 reviewed:/);
assert.match(claudeWorkflow, /types: \[opened, synchronize, ready_for_review, reopened, edited\]/, 'description edits trigger a fresh Claude review');

console.log('Review gate signal and refusal cases passed.');
