import {chromium} from 'playwright';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const p=await (await b.newContext({viewport:{width:1440,height:1000}})).newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
const fails=[]; const step=(w,r)=>{const ok=r&&r.ok!==false;console.log((ok?'  ok   ':'  FAIL ')+w+(ok?'':' -> '+(r&&r.message)));if(!ok)fails.push(w);};
const no=(w,r)=>step(w,{ok:!(r&&r.ok),message:r&&r.message||'was allowed'});
await p.goto('file:///home/claude/fc/demo_qa150_publish.html'); await p.waitForTimeout(900);
await p.evaluate(x=>{const un=document.querySelector('#sk-boot input[name=username]');const pw=document.querySelector('#sk-boot input[type=password]');un.value=x;un.dispatchEvent(new Event('input',{bubbles:true}));pw.value='demo1234';pw.dispatchEvent(new Event('input',{bubbles:true}));un.closest('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));},'master');
await p.waitForTimeout(2600); await p.evaluate(()=>{document.body.click();document.querySelectorAll('.mnv-landing').forEach(e=>e.remove());});
const run=(fn,a)=>p.evaluate(fn,a);
const fx=await run(()=>{const o=state.orders.find(o=>o.status==='Building'&&!MES.blockingTickets(o).length&&(()=>{const n=o.operations.find(x=>!x.done);return n&&MES.isInspectionOp(n)&&o.operations.indexOf(n)>0;})());if(!o)return null;const n=o.operations.find(x=>!x.done);return {o:o.id,op:n.id,prev:o.operations[o.operations.indexOf(n)-1].id,later:(o.operations[o.operations.indexOf(n)+1]||{}).id,serials:MES.orderSerials(state,o).map(e=>e.serial)};});
console.log('fixture',JSON.stringify(fx));
if(!fx){console.log('no fixture');process.exit(1);}
no('buy-off without standard inspection ack refused',await run(a=>{const x=structuredClone(state);const op=MES.getOrder(x,a.o).operations.find(y=>y.id===a.op);op.steps=[];op.stepChecks={};const r=MES.completeOperation(x,a.o,a.op,'',{stampNumber:'x',pin:''});return {ok:r.ok||!/standard inspection/i.test(r.message),message:r.message};},fx));
await run(a=>{selectedId=a.o;view='order';tab='operations';render();},fx); await p.waitForTimeout(300);
step('standard inspection header at top of the operation',{ok:await run(()=>{const t=document.querySelector('#operation-detail .task-content');return !!t&&t.firstElementChild&&t.firstElementChild.classList.contains('std-insp');}),message:'no banner'});
step('Reject inspection button',{ok:await run(()=>!!document.querySelector('[data-action="insp-reject"]')),message:'no button'});
await p.waitForTimeout(3500);await run(()=>{render();document.querySelector('#operation-detail').scrollIntoView();});await p.waitForTimeout(300);await p.screenshot({path:'/home/claude/shots/v75_insp.png'});
no('reject without source op refused',await run(a=>MES.rejectInspection(structuredClone(state),a.o,a.op,{type:'NC',title:'Loose',description:'Loose nut',requirement:'WI 030-B',serials:a.serials}),fx));
if(fx.later) no('reject against a later op refused',await run(a=>MES.rejectInspection(structuredClone(state),a.o,a.op,{sourceOperationId:a.later,type:'NC',title:'Loose',description:'Loose nut',requirement:'WI 030-B',serials:a.serials}),fx));
no('reject without requirement refused',await run(a=>MES.rejectInspection(structuredClone(state),a.o,a.op,{sourceOperationId:a.prev,type:'NC',title:'Loose',description:'Loose nut',requirement:'',serials:a.serials}),fx));
await p.click('[data-action="insp-reject"]'); await p.waitForTimeout(300);
step('reject dialog asks for the operation',{ok:await run(()=>!!document.querySelector('#insp-reject-form #ir-source')),message:'no form'});
await p.selectOption('#ir-source',fx.prev); await p.fill('#ir-title','Backshell not torqued'); await p.fill('#ir-req','WI step 030-B: 25 in-lb, torque stripe'); await p.fill('#ir-desc','J3 backshell turns by hand, no torque stripe');
if(fx.serials.length>1) await p.check(`#insp-reject-form input[name=serial][value="${fx.serials[0]}"]`);
await p.click('#insp-reject-form button[type=submit]'); await p.waitForTimeout(500);
const res=await run(a=>{const o=MES.getOrder(state,a.o);const t=o.tickets[o.tickets.length-1];return {valid:MES.validate(state),id:t.id,op:t.operationId,det:t.detected&&t.detected.operationId,held:MES.blockingTickets(o,a.op).length,dlg:$('#dialog').open&&$('#dialog').textContent.includes(t.id)};},fx);
console.log('  ',JSON.stringify(res));
step('ticket raised against the chosen op, detected at the inspection',{ok:res.op===fx.prev&&res.det===fx.op,message:JSON.stringify(res)});
step('inspection on hold',{ok:res.held>0,message:'not held'});
step('state valid',{ok:res.valid,message:'invalid'});
step('ticket dialog opens after reject',{ok:res.dlg,message:'no ticket dialog'});
await run(()=>$('#dialog').open&&$('#dialog').close());
// WI read view banner
await run(()=>{view='wis';render();});await p.waitForTimeout(300);
const wid=await run(()=>{const w=state.masterWIs.find(w=>w.operations.some(o=>o.inspectionPoint));const b=document.querySelector(`[data-action="wi-open"][data-id="${w.id}"],[data-action="wi-open"][data-wi="${w.id}"]`)||document.querySelector('[data-action="wi-open"]');b&&b.click();return w.id;});await p.waitForTimeout(400);
const wiB=await run(()=>document.querySelectorAll('.std-insp').length);
step('WI view shows the standard inspection header',{ok:wiB>0,message:'none'});await p.screenshot({path:'/home/claude/shots/v75_wi.png'});
step('traveler prints standard inspection',{ok:await run(a=>/STANDARD INSPECTION/.test(MESPrint.traveler(MES.getOrder(state,a.o),{serials:[],printedAt:new Date().toISOString(),printedBy:'x'})),fx),message:'missing'});
console.log('errors',errs,'FAILS',JSON.stringify(fails)); await b.close();
