import {chromium} from 'playwright';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const ctx=await b.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}); const p=await ctx.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
const fails=[]; const step=(w,r)=>{const ok=r&&r.ok!==false;console.log((ok?'  ok   ':'  FAIL ')+w+(ok?'':' -> '+(r&&r.message)));if(!ok)fails.push(w);return r;};
const no=(w,r)=>step(w,{ok:!(r&&r.ok),message:r&&r.message||'was allowed'});
async function signIn(u){ await p.evaluate(()=>{try{sessionStorage.removeItem('skyryse-mes-session-v1');}catch(e){}}).catch(()=>{});
  await p.goto('file:///home/claude/fc/demo_qa150_publish.html'); await p.waitForTimeout(900);
  await p.evaluate(x=>{const un=document.querySelector('#sk-boot input[name=username]');if(!un)return;const pw=document.querySelector('#sk-boot input[type=password]');un.value=x;un.dispatchEvent(new Event('input',{bubbles:true}));pw.value='demo1234';pw.dispatchEvent(new Event('input',{bubbles:true}));un.closest('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));},u);
  await p.waitForTimeout(2600); await p.evaluate(()=>{document.body.click();document.querySelectorAll('.mnv-landing').forEach(e=>e.remove());}); }
const run=(fn,a)=>p.evaluate(fn,a);
const S=(fn,a)=>run(new Function('a',`const r=(${fn})(a);if(r&&r.ok)save();return r&&{ok:r.ok,message:r.message};`),a);
const valid=async w=>step('valid · '+w,{ok:await run(()=>MES.validate(state)),message:'state invalid'});
await signIn('master');
// ---- MCR operation is mandatory ----
const wi=await run(()=>{const w=state.masterWIs.find(x=>x.status==='Released');return {id:w.id,rev:w.revision,op:w.operations[0].id};});
no('MCR without an operation refused',await run(w=>MES.submitECRRequest(state,{type:'process',wiId:w.id,wiRevision:w.rev,opId:'',title:'Clarify torque',description:'Add unit',reason:'Operator question'}),wi));
step('MCR with an operation',await S(w=>MES.submitECRRequest(state,{type:'process',wiId:w.id,wiRevision:w.rev,opId:w.op,title:'Clarify torque',description:'Add unit',reason:'Operator question'}),wi));
await run(()=>{ecrFormDialog('process',{});}); await p.waitForTimeout(300);
step('MCR form: operation required, no "optional"',{ok:await run(()=>{const s=document.querySelector('#ecr-op');return !!s&&s.required&&!/optional/i.test(s.closest('.field').textContent);}),message:'not required'});
await run(()=>$('#dialog').close());
// ---- FAIR ----
const O='WO-10196';
step('mark FAI order',await S(o=>{const x=MES.getOrder(state,o);x.fai={required:true,wi:'MWI-TEST|A',at:new Date().toISOString(),by:x.history[0]&&x.history[0].by||MES.getOrder(state,'WO-10197').operations[0].buyoff||state.profile,reason:'First work order from MWI-TEST Rev A.'};return {ok:MES.validate(state),message:'fai shape'};},O));
await run(()=>{const x=MES.getOrder(state,'WO-10196');if(!MES.validate(state)){x.fai.by={name:state.profile.name,role:state.profile.role,credentialId:state.profile.credentialId};}});
await valid('fai flag');
no('close refused without approved FAIR',await run(o=>MES.closeOrder(state,o),O));
await run(o=>{selectedId=o;view='order';tab='quality';render();},O); await p.waitForTimeout(300);
step('FAIR panel offers start',{ok:await run(()=>!!document.querySelector('[data-action="fair-start"]')),message:'no start'});
await p.click('[data-action="fair-start"]'); await p.waitForTimeout(400);
step('FAIR seeded from kit',{ok:await run(o=>{const f=MES.getOrder(state,o).fair;return f&&f.index.length>0&&f.reasons.length===1&&f.status==='Open';},O),message:'not seeded'});
await valid('seeded');
step('Form 1 header',await S(o=>MES.saveFairHeader(state,o,{type:'Full',reasons:['New part (first production)'],supplierCode:'8xyz1',po:'',sampleSize:'1',additionalChanges:'MCR-0001',comments:'First build'}),O));
no('partial FAI needs baseline',await run(o=>{const s=structuredClone(state);MES.saveFairHeader(s,o,{type:'Partial'});return {ok:!MES.fairReview(s,MES.getOrder(s,o)).some(g=>/partial FAI/.test(g))};},O));
step('index lot ids',await S(o=>MES.setFairIndex(state,o,MES.getOrder(state,o).fair.index.map((x,i)=>({...x,fairId:x.fairId||'LOT-'+(i+1)}))),O));
no('Form 2 without spec refused',await run(o=>MES.addFairForm2(structuredClone(state),o,{kind:'Material',name:'Al 6061-T6',spec:'',supplier:'Acme, CA',approval:'Yes',coc:'C1'}),O));
step('Form 2 material',await S(o=>MES.addFairForm2(state,o,{kind:'Material',name:'Aluminum 6061-T6',spec:'AMS-QQ-A-250/11',code:'',supplier:'Acme Metals, Torrance CA',approval:'Yes',coc:'COC-7781'}),O));
step('Form 2 special process',await S(o=>MES.addFairForm2(state,o,{kind:'Special process',name:'Anodize Type II',spec:'MIL-A-8625 Type II Class 2',code:'',supplier:'Plating Co, Gardena CA',approval:'Yes',coc:'COC-2201'}),O));
step('Form 2 test',await S(o=>MES.setFairTest(state,o,null,{add:true,procedure:'ATP-110-001 Rev A',report:'ATR-10196',software:'1.4.2'}),O));
no('quantitative needs a value',await run(o=>MES.addFairChar(structuredClone(state),o,{no:'1',ref:'Sht 1 B3',designator:'',requirement:'0.250 ±0.005 in',result:'pass',ok:'yes',tool:'CMM-01'}),O));
no('NC needs a ticket on the order',await run(o=>MES.addFairChar(structuredClone(state),o,{no:'1',ref:'Sht 1 B3',designator:'',requirement:'0.250 ±0.005 in',result:'0.262',ok:'no',nc:'IDR-9999',tool:'CMM-01'}),O));
step('char 1',await S(o=>MES.addFairChar(state,o,{no:'1',ref:'Sht 1 B3',designator:'Key',requirement:'0.250 ±0.005 in',result:'0.2512',ok:'yes',tool:'CMM-01 / RPT-551'}),O));
step('char 3 (balloon number kept)',await S(o=>MES.addFairChar(state,o,{no:'3',ref:'Sht 2 note 4',designator:'',requirement:'Note 4: part mark per MIL-STD-130',result:'Conforms',ok:'yes',tool:'Visual'}),O));
no('duplicate balloon refused',await run(o=>MES.addFairChar(structuredClone(state),o,{no:'3',ref:'x',requirement:'x'}),O));
step('char 2 no result yet',await S(o=>MES.addFairChar(state,o,{no:'2',ref:'Sht 1 C2',requirement:'Ø 0.125 +0.002/-0.000'}),O));
step('review flags char 2',{ok:await run(o=>MES.fairReview(state,MES.getOrder(state,o)).some(g=>/results missing for 2/.test(g)),O),message:'no flag'});
step('char 2 result',await S(o=>MES.updateFairChar(state,o,'C-2',{result:'0.1261',ok:'yes',tool:'PIN-GAGE-14'}),O));
step('order sorted by balloon',{ok:await run(o=>MES.getOrder(state,o).fair.chars.map(c=>c.id).join()==='C-1,C-2,C-3',O),message:'order'});
step('review clean',{ok:await run(o=>MES.fairReview(state,MES.getOrder(state,o)).length===0,O),message:JSON.stringify(await run(o=>MES.fairReview(state,MES.getOrder(state,o)),O))});
await valid('fair data');
await run(o=>{render();},O); await p.waitForTimeout(300);
await p.screenshot({path:'/home/claude/shots/v74_fair.png',fullPage:true});
await signIn('quality');
step('verify (quality stamp)',await S(o=>MES.verifyFair(state,o,{pin:''}),O));
no('edit after verify refused',await run(o=>MES.addFairChar(structuredClone(state),o,{no:'9',ref:'x',requirement:'x'}),O));
step('approve (Skyryse QA)',await S(o=>MES.approveFair(state,o,{pin:''}),O));
await valid('fair approved');
await run(o=>{selectedId=o;view='order';tab='quality';render();},O); await p.waitForTimeout(300);
const [dl]=await Promise.all([p.waitForEvent('download',{timeout:5000}).catch(()=>null),p.click('[data-action="fair-download"]')]);
if(dl){const fs=await import('fs');const path=await dl.path();const h=fs.readFileSync(path,'utf8');step('FAIR download has Forms 1 to 3 blocks',{ok:/Form 1/.test(h)&&/Form 2/.test(h)&&/Form 3/.test(h)&&/25\. Date/.test(h)&&/3A\. Sample size/.test(h)&&/AMS-QQ-A-250\/11/.test(h),message:'content'});fs.copyFileSync(path,'/home/claude/shots/v74_fair_download.html');}else step('FAIR download',{ok:false,message:'none'});
step('FAI pill shows approved',{ok:await run(()=>/FAIR approved/.test(document.querySelector('#order-title').textContent)),message:'pill'});
step('close order with approved FAIR',await S(o=>MES.closeOrder(state,o),O));
// ---- Conformity package ----
const sn=await run(o=>MES.confSerials(state,MES.getOrder(state,o))[0],O);
await run(o=>{render();},O); await p.waitForTimeout(200);
step('conformity panel offers start',{ok:await run(()=>!!document.querySelector('[data-form="conf-start"]')),message:'no start form'});
step('start package',await S(([o,s])=>MES.startConformity(state,o,{serial:s,jira:'conf-12',rfc:''}),[O,sn]));
no('duplicate package refused',await run(([o,s])=>MES.startConformity(structuredClone(state),o,{serial:s}),[O,sn]));
step('package details',await S(([o,s])=>MES.saveConformity(state,o,s,{mdlRev:'G',mdlReceived:new Date().toISOString().slice(0,10),staging:'Cage B, shelf 2'}),[O,sn]));
no('1.3 needs MDL',await run(([o,s])=>{const x=structuredClone(state);MES.saveConformity(x,o,s,{mdlRev:''});return MES.checkConformity(x,o,s,'1.3',true);},[O,sn]));
for(const k of ['1.2','1.3','1.4','3.1','3.2','3.3','3.4','4.1a','4.1b','4.1c','4.1d','4.2']) { const r=await S(([o,s,k])=>MES.checkConformity(state,o,s,k,true),[O,sn,k]); step('step '+k,r); }
no('N/A without justification refused',await run(([o,s])=>MES.checkConformity(structuredClone(state),o,s,'3.3',{value:'N/A',note:''}),[O,sn]));
step('N/A with justification',await S(([o,s])=>MES.checkConformity(state,o,s,'3.3',{value:'N/A',note:'No buy parts in this LRU kit'}),[O,sn]));
step('No recorded with reason',await S(([o,s])=>MES.checkConformity(state,o,s,'4.1b',{value:'No',note:'Dust cap missing on J3'}),[O,sn]));
step('No blocks the package',{ok:await run(([o,s])=>MES.confGaps(state,MES.getOrder(state,o),MES.getOrder(state,o).conformity[0],'prepare').some(g=>/4\.1b is marked not acceptable/.test(g)),[O,sn]),message:'no gap'});
step('re-record 4.1b Yes',await S(([o,s])=>MES.checkConformity(state,o,s,'4.1b',{value:'Yes'}),[O,sn]));
await run(([o,s])=>{openConfWizard(o,s,4);},[O,sn]); await p.waitForTimeout(300);
step('wizard: 8 pages, Yes/No/N/A on each step',{ok:await run(()=>document.querySelectorAll('.conf-wiz-step').length===8&&document.querySelectorAll('.conf-wiz .conf-acc [name=value]').length>=15),message:'wizard'});
await p.screenshot({path:'/home/claude/shots/v74_wizard.png'});
await p.click('.conf-wiz [data-action="conf-page"][data-page="0"]'); await p.waitForTimeout(300);
await p.fill('.conf-wiz [name=staging]','Cage C, shelf 1'); await p.click('.conf-wiz [data-action="conf-save-progress"]'); await p.waitForTimeout(300);
step('save progress writes typed field',{ok:await run(([o])=>MES.getOrder(state,o).conformity[0].staging==='Cage C, shelf 1'&&/Saved/.test(document.querySelector('.conf-saved').textContent),[O]),message:'not saved'});
await p.fill('.conf-wiz [name=jira]','CONF-77'); await p.press('.conf-wiz [name=jira]','Tab'); await p.waitForTimeout(300);
step('autosave on change',{ok:await run(([o])=>MES.getOrder(state,o).conformity[0].jira==='CONF-77',[O]),message:'no autosave'});
await p.click('.conf-wiz [data-action="conf-page"][data-page="1"]'); await p.waitForTimeout(300);
step('Next page keeps dialog open on phase 1',{ok:await run(()=>$('#dialog').open&&/Phase 1/.test(document.querySelector('.conf-wiz-title').textContent)),message:'nav'});
await run(()=>$('#dialog').close());
no('8130-9 before RFC refused',await run(([o,s])=>MES.complete8130_9(structuredClone(state),o,s,{section:'Aircraft',item:'A',make:'Skyryse',model:'R66',basis:'Parts conform'},{pin:''}),[O,sn]));
step('RFC and NC decision',await S(([o,s])=>MES.saveConformity(state,o,s,{rfc:'rfc-0042',nc:'No'}),[O,sn]));
step('complete 8130-9 (quality)',await S(([o,s])=>MES.complete8130_9(state,o,s,{section:'Aircraft',item:'A',make:'Skyryse',model:'R66',basis:'Parts are in conformity with Master Data List AA-CRT-0001 Rev G'},{pin:''}),[O,sn]));
no('data locked after 8130-9',await run(([o,s])=>MES.saveConformity(structuredClone(state),o,s,{rfc:'RFC-9'}),[O,sn]));
step('void and redo',await S(([o,s])=>MES.void8130_9(state,o,s,'Model entered wrong'),[O,sn]));
step('complete again',await S(([o,s])=>MES.complete8130_9(state,o,s,{section:'Aircraft',item:'A',make:'Skyryse',model:'R66',basis:'Parts are in conformity with Master Data List AA-CRT-0001 Rev G'},{pin:''}),[O,sn]));
step('6.1 matches RFC',await S(([o,s])=>MES.checkConformity(state,o,s,'6.1',true),[O,sn]));
no('AQI needs 8130-9 AI stamp (quality refused)',await run(([o,s])=>MES.aqiSign8130_9(structuredClone(state),o,s,{pin:''}),[O,sn]));
await valid('8130-9 completed');
await signIn('master');
step('AQI signs (master, AI stamp)',await S(([o,s])=>MES.aqiSign8130_9(state,o,s,{pin:''}),[O,sn]));
no('notify before tag refused',await run(([o,s])=>MES.notifyCertification(structuredClone(state),o,s),[O,sn]));
for(const k of ['6.3a','6.3b']) step('step '+k,await S(([o,s,k])=>MES.checkConformity(state,o,s,k,true),[O,sn,k]));
step('notify Certification',await S(([o,s])=>MES.notifyCertification(state,o,s),[O,sn]));
step('DAR details',await S(([o,s])=>MES.saveConformity(state,o,s,{darName:'J. Rivera',darDesignation:'DAR-F 123',darDate:new Date().toISOString().slice(0,10)}),[O,sn]));
step('step 7.2',await S(([o,s])=>MES.checkConformity(state,o,s,'7.2',true),[O,sn]));
step('DAR finding',await S(([o,s])=>MES.addDarFinding(state,o,s,{text:'Data plate font below drawing minimum',owner:'Ops Manager',rcca:''}),[O,sn]));
no('approval blocked by open finding',await run(([o,s])=>MES.recordDarApproval(structuredClone(state),o,s,{name:'J. Rivera',designation:'DAR-F 123',date:new Date().toISOString().slice(0,10),aqiPresent:true,fieldsSigned:true}),[O,sn]));
no('finding needs DAR acceptance',await run(([o,s])=>MES.acceptDarFinding(structuredClone(state),o,s,'F-1',{rcca:'RCCA-9',resolution:'Replaced plate',dar:false}),[O,sn]));
step('finding accepted',await S(([o,s])=>MES.acceptDarFinding(state,o,s,'F-1',{rcca:'RCCA-9',resolution:'Replaced data plate per drawing',dar:true}),[O,sn]));
step('DAR approval: CONFORMED',await S(([o,s])=>MES.recordDarApproval(state,o,s,{name:'J. Rivera',designation:'DAR-F 123',date:new Date().toISOString().slice(0,10),aqiPresent:true,fieldsSigned:true}),[O,sn]));
step('8130-3 recorded',await S(([o,s])=>MES.record8130_3(state,o,s,{number:'fc-0001',issuer:'DAR',issuerName:'J. Rivera DAR-F 123',date:new Date().toISOString().slice(0,10),block11:'PROTOTYPE'}),[O,sn]));
for(const k of ['7.6','7.7']) step('step '+k,await S(([o,s,k])=>MES.checkConformity(state,o,s,k,true),[O,sn,k]));
step('close package',await S(([o,s])=>MES.closeConformity(state,o,s),[O,sn]));
await valid('package closed');
await run(o=>{selectedId=o;view='order';tab='quality';render();document.querySelectorAll('.conf-phase').forEach(d=>d.open=true);},O); await p.waitForTimeout(300);
await p.screenshot({path:'/home/claude/shots/v74_conf.png',fullPage:true});
const [d2]=await Promise.all([p.waitForEvent('download',{timeout:5000}).catch(()=>null),p.click('[data-action="conf-8130"]')]);
if(d2){const fs=await import('fs');const h=fs.readFileSync(await d2.path(),'utf8');fs.writeFileSync('/home/claude/shots/v74_8130.html',h);step('8130-9 download: sections, AQI, DAR',{ok:/Section IV/.test(h)&&/Authorized Quality Inspector/.test(h)&&/J\. Rivera/.test(h)&&/21\.33\(a\)/.test(h),message:'content'});}else step('8130-9 download',{ok:false,message:'none'});
const tr=await run(sn=>{const r=MES.traceReport(state,sn);return r.ok?JSON.stringify(r.build).slice(0,4000):r.message;},sn);
step('trace shows conformity',{ok:/CONFORMED/.test(tr)&&/FAIR/.test(tr),message:tr.slice(0,300)});
// ---- ATP assets ----
no('ATP needs an asset',await run(()=>MES.atpAssets([],new Date().toISOString())));
no('manual asset needs cal or no-cal',await run(()=>MES.atpAssets([{asset:'TS-01',description:'ATP test stand'}],new Date().toISOString())));
no('expired cal refused',await run(()=>MES.atpAssets([{asset:'PS-2',description:'Power supply',calDue:'2020-01-01'}],new Date().toISOString())));
step('logged tool + manual + fixture',await run(()=>{const t=MES.CAL_TOOLS.find(t=>MES.toolCheck(t.tag).ok);const r=MES.atpAssets([{asset:t.tag},{asset:'PS-2',description:'Power supply',calDue:'2099-01-01'},{asset:'FX-7',description:'Harness fixture',noCal:true}],new Date().toISOString());return {ok:r.ok&&r.list.length===3&&r.list[0].source==='Calibrated Tool Log',message:r.message};}));
const atp=await run(()=>{const o=state.orders.find(o=>o.status==='Building'&&o.operations.some(op=>!op.done));const op=o.operations.find(op=>!op.done);op.classification=MES.ATP_CLASS;const why=MES.validate(state)?'':(MES.diagnose(state)||{}).detail;selectedId=o.id;view='order';tab='execution';render();return {o:o.id,op:op.id,why};});
console.log('   atp fixture',JSON.stringify(atp));
await p.waitForTimeout(300);
step('ATP buy-off form shows asset block',{ok:await run(a=>{const o=MES.getOrder(state,a.o),op=o.operations.find(x=>x.id===a.op);const d=document.createElement('div');d.innerHTML=renderTaskForm(o,op,o.operations.indexOf(op));return !!d.querySelector('.atp-assets [data-asset-row] [name=assetId]');},atp),message:'no block'});
const ar=await run(a=>{const x=state;const o=MES.getOrder(x,a.o),op=o.operations.find(y=>y.id===a.op);op.steps=[];op.stepChecks={};op.requiresTooling=false;op.requiresRecording=false;if(!MES.validate(x))return {ok:false,message:'fixture: '+(MES.diagnose(x)||{}).detail};const r=MES.completeOperation(x,a.o,a.op,'',{stampNumber:'x',pin:'',testAssets:[]});return r;},atp);console.log('   atp refusal:',ar.message);
step('ATP buy-off without asset refused with the asset message',{ok:!ar.ok&&/test equipment or asset/.test(ar.message),message:ar.message});
// ---- Traveler prompt ----
const dr=await run(()=>{const o=state.orders.find(o=>o.status==='Draft'&&!(MES.requiresReleaseQA(o)&&!MES.releaseApproval(o)));return o&&o.id;});
if(dr){await run(o=>{selectedId=o;view='order';tab='overview';render();},dr);await p.waitForTimeout(200);
  step('advance to kitting',await S(o=>MES.advance(state,o),dr));
  await run(()=>render()); await p.waitForTimeout(700);
  step('traveler prompt appears',{ok:await run(()=>$('#dialog').open&&/traveler/i.test($('#dialog').textContent)),message:'no prompt'});
  await run(()=>$('#dialog').open&&$('#dialog').close());
  await run(()=>{tab='materials';render();}); await p.waitForTimeout(200);
  step('Kit tab has Print traveler',{ok:await run(()=>!!document.querySelector('.traveler-panel [data-action="print-traveler"]')),message:'no button'});
  step('traveler html is F-850-001',{ok:await run(o=>/F-850-001/.test(MESPrint.traveler(MES.getOrder(state,o),{serials:[],printedAt:new Date().toISOString(),printedBy:'x'})),dr),message:'no form number'});
} else step('draft order for traveler',{ok:false,message:'none'});
// ---- Part Conformity operation ----
const pc=await run(()=>{const o=state.orders.find(o=>o.status==='Building'&&MES.orderSerials(state,o).length===1&&!o.tickets.some(t=>t.status==='Open'));const last=o.operations[o.operations.length-1];const op={...structuredClone(last),id:'op-conf',title:'Part conformity review',classification:MES.CONF_CLASS,done:false,buyoff:null,note:'',steps:[],stepChecks:{},evidence:[],requiresTooling:false,requiresRecording:false};delete op.inspectionPoint;o.operations.forEach(x=>{if(!x.done){x.done=true;x.note='Fixture';x.buyoff=x.buyoff||{name:'t',role:'t',credentialId:'t',at:new Date().toISOString(),virtual:true};}});o.operations.push(op);return {o:o.id,valid:MES.validate(state),why:(MES.diagnose(state)||{}).detail};});
console.log('   conf op fixture',JSON.stringify(pc));
step('start package at the Part Conformity op',await run(a=>MES.startConformity(state,a.o,{serial:MES.confSerials(state,MES.getOrder(state,a.o))[0]}),pc));
step('op gate refuses before Phase 6',{ok:!(await run(a=>MES.confOpGate(state,MES.getOrder(state,a.o)).ok,pc)),message:'gate open'});
await run(a=>{selectedId=a.o;view='order';tab='operations';render();},pc); await p.waitForTimeout(300);
console.log('   exec text:',(await run(()=>document.querySelector('#main').textContent.replace(/\s+/g,' ').slice(0,1500))));
step('op card shows checklist launcher',{ok:await run(()=>!!document.querySelector('.conf-op [data-action="conf-wizard"]')),message:'no launcher'});
await p.screenshot({path:'/home/claude/shots/v74_conf_op.png'});
await valid('end');
console.log('page errors',errs); console.log('FAILS',JSON.stringify(fails));
await b.close();
