// The PFMEA Safety Team buy-off: who may give it and what its signature binds.
// Nobody whose work the buy-off accepts may give it: a failure-mode author, a no-risk reviewer, an action closer
// or the person who completed the analysis (a QA Manager holds edit-wi and safety-buyoff, so this matters).
// The signature manifest binds the analysis content and the Safety Team rationale, and verifyManifests recomputes
// it from the stored PFMEA, so an edit after signing fails verification. Older buy-offs keep verifying.
import {chromium} from 'playwright';
const TESTS=decodeURI(new URL('.',import.meta.url).pathname);
const FIXTURES=process.env.FS_FIXTURES_DIR?process.env.FS_FIXTURES_DIR.replace(/\/?$/,'/'):TESTS+'fixtures/';
const PROD='file://'+FIXTURES+'publish.html';
const AUTH='skyryse-mes-auth-v1',SESSION='skyryse-mes-session-v1';
const b=await chromium.launch(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{});
const p=await (await b.newContext({viewport:{width:1440,height:1000}})).newPage();
const errs=[];p.on('pageerror',e=>errs.push(e.message));
const fails=[];const ok=(w,c,m='')=>{console.log((c?'  ok   ':'  FAIL ')+w+(c?'':' -> '+m));if(!c)fails.push(w);};
const run=(fn,a)=>p.evaluate(fn,a);
const as=u=>run(([S,u])=>sessionStorage.setItem(S,u),[SESSION,u]);

await p.goto(PROD);await p.waitForTimeout(900);
await run(()=>{const un=document.querySelector('#sk-boot input[name=username]');const f=un.closest('form');const set=(el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));};set(un,'jdoe');set(f.querySelector('input[type=password]'),'demo1234');const cf=f.querySelector('input[name=confirm]');if(cf)set(cf,'demo1234');const d=f.querySelector('input[name=displayName]');if(d)set(d,'Jordan Doe');f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});
await p.waitForTimeout(2600);
await run(async([AUTH])=>{const a=JSON.parse(localStorage.getItem(AUTH));const salt='00112233445566778899aabbccddeeff';const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');const hash=hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(salt+':demo1234')));
  const add=(username,displayName,role)=>{if(!a.users.some(u=>u.username===username))a.users.push({username,displayName,salt,hash,role,createdAt:new Date().toISOString(),createdBy:'jdoe'});};
  add('kqe','Kai Quality','qe');add('tme','Taylor Engineer','me');add('pqm','Parker Manager','qm');add('lqm','Lee Manager','qm');add('ssafe','Sky Safety','safety');
  localStorage.setItem(AUTH,JSON.stringify(a));},[AUTH]);

// A critical safety WI with its PFMEA in analysis. The QA review is Lee's, the PFMEA was opened by Kai.
await as('jdoe');
const fx=await run(()=>{const wi=state.masterWIs.find(w=>w.status==='Draft'&&w.operations.length>=3);const ago=d=>new Date(Date.now()-d*86400000).toISOString();const me={name:'Taylor Engineer',role:'Manufacturing Engineer',credentialId:'ACCT-tme',account:'tme'};const qa={name:'Lee Manager',role:'Quality Manager',credentialId:'ACCT-lqm',account:'lqm'};
  wi.criticalSafety=true;wi.eco='ECO-2301';wi.peerReview={name:me.name,role:me.role,credentialId:me.credentialId,at:ago(3),virtual:true};wi.qaReview={name:qa.name,role:qa.role,credentialId:qa.credentialId,at:ago(2),virtual:true};
  if(!Array.isArray(state.maneuver.pfmeas))state.maneuver.pfmeas=[];
  state.maneuver.pfmeas.push({id:'PFM-301',wiId:wi.id,wiRevision:wi.revision,partNumber:wi.partNumber,title:wi.title,status:'Analysis',scope:{team:'T. Engineer (ME), L. Manager (QA), Safety Team representative',boundaries:'Every operation of this revision.',by:me,at:ago(2)},rows:[{id:'FM-1',opId:wi.operations[0].id,mode:'Wrong kit issued',effect:'Non-conforming part',cause:'Label not checked',controls:'Kit list',s:4,o:3,d:4,rpn:48,action:'',owner:'',due:null,done:null,by:me,at:ago(2)}],reviewed:Object.fromEntries(wi.operations.slice(2).map(op=>[op.id,{by:me,at:ago(2),note:'No credible failure mode.'}])),analysisDone:null,actionsDone:null,safety:null,returns:[],openedBy:{name:'Kai Quality',role:'Quality Engineer',credentialId:'ACCT-kqe',account:'kqe'},openedAt:ago(2),attachments:[],history:[]});
  return {saved:save(),valid:MES.validate(state),op:wi.operations[1].id};});
ok('fixture: a critical safety PFMEA in analysis with one operation left to review',fx.saved&&fx.valid,JSON.stringify(fx));

// ---- a QA Manager who marks an operation no-risk cannot then give the Safety Team buy-off ----
// Parker (QA Manager) reviews the open operation as no-risk, Taylor completes the analysis.
await as('pqm');
let r=await run(([op])=>{const r=FlightManeuver.markOpNoRisk(state,'PFM-301',op,'Fastener torque is verified by the next inspection.');if(r.ok)save();return r;},[fx.op]);
ok('a QA Manager holds edit-wi and may record a no-risk review',r.ok===true,JSON.stringify(r));
await as('tme');
r=await run(()=>{const r=FlightManeuver.completePfmeaAnalysis(state,'PFM-301');if(r.ok)save();return {ok:r.ok,message:r.message,status:FlightManeuver.get(state,'pfmeas','PFM-301').status};});
ok('analysis completed and sent to the Safety Team',r.ok===true&&r.status==='Safety review',JSON.stringify(r));
const buyoff=(note='Controls adequate for every failure mode.')=>run(([note])=>{const s=structuredClone(state);const res=FlightManeuver.pfmeaSafetyBuyoff(s,'PFM-301',{decision:'Approve',note});const t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');return {ok:res.ok,message:res.message,status:t.status,safety:t.safety,changed:JSON.stringify(s)!==JSON.stringify(state)};},[note]);
await as('pqm');r=await buyoff();
ok('the QA Manager who recorded a no-risk review is refused the Safety Team buy-off',r.ok===false&&/you recorded part of this analysis/.test(r.message),JSON.stringify(r));
ok('the refused buy-off changes nothing',r.changed===false&&r.status==='Safety review'&&r.safety===null,JSON.stringify(r));
await as('tme');r=await buyoff();
ok('the person who completed the analysis has no safety-buyoff and is refused',r.ok===false,JSON.stringify(r));

// An action closer and the analysis completer are refused the same way.
const variant=(fn)=>run(([fn])=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301'),pqm={name:'Parker Manager',role:'Quality Manager',credentialId:'ACCT-pqm',account:'pqm'};
  delete t.reviewed[Object.keys(t.reviewed).find(k=>t.reviewed[k].by.credentialId==='ACCT-pqm')];t.rows.push({id:'FM-2',opId:s.masterWIs.find(w=>w.id===t.wiId&&w.revision===t.wiRevision).operations[1].id,mode:'Fastener under-torqued',effect:'Loose joint',cause:'Wrong setting',controls:'Torque audit',s:9,o:2,d:3,rpn:54,action:'Add a torque-limiting driver',owner:'T. Engineer',due:'2026-11-01',done:null,by:{name:'Taylor Engineer',role:'Manufacturing Engineer',credentialId:'ACCT-tme',account:'tme'},at:new Date().toISOString()});
  // Parker's no-risk review was removed above; drop its history entry and contributor record too, so each variant adds only its own contribution.
  t.history=(t.history||[]).filter(h=>!String(h.actor||'').endsWith('ACCT-pqm'));t.contributors=(t.contributors||[]).filter(c=>c!=='ACCT-pqm');
  // FM-2 is a row saved before actionSet existed: its action setter is named only in the ticket history.
  t.history.push({at:new Date().toISOString(),action:'FM-2 action: Add a torque-limiting driver (owner T. Engineer, due 2026-11-01).',actor:'Taylor Engineer · ACCT-tme'});
  if(fn==='legacySetter')t.history[t.history.length-1].actor='Parker Manager · ACCT-pqm';
  if(fn==='legacyUnknown')t.history.pop();
  const hist=(action,actor)=>t.history.push({at:new Date().toISOString(),action,actor});
  if(fn==='overwrittenSetter'){hist('FM-2 action: Add a torque-limiting driver (owner T. Engineer, due 2026-11-01).','Parker Manager · ACCT-pqm');t.rows[1].actionSet={by:{name:'Taylor Engineer',role:'Manufacturing Engineer',credentialId:'ACCT-tme',account:'tme'},at:new Date().toISOString()};}
  if(fn==='clearedCloser')hist('FM-2 action closed. Revised RPN 18 (was 54).','Parker Manager · ACCT-pqm');
  if(fn==='clearedCompleter')hist('Analysis complete: 2 failure modes, 1 high risk.','Parker Manager · ACCT-pqm');
  if(fn==='agedOut')t.contributors=[...(t.contributors||[]),'ACCT-pqm'];
  if(fn==='returner')hist('Returned by the Safety Team: Re-score FM-2 after the driver trial.','Parker Manager · ACCT-pqm');
  if(fn==='closer')t.rows[1].done={evidence:'Driver issued and verified.',s:9,o:1,d:2,rpn:18,by:pqm,at:new Date().toISOString()};
  if(fn==='scoper')t.scope={...t.scope,by:pqm};
  if(fn==='setter')t.rows[1].actionSet={by:pqm,at:new Date().toISOString()};
  if(fn==='actions')t.actionsDone={by:pqm,at:new Date().toISOString()};
  if(fn==='completer'){t.rows[1].done={evidence:'Driver issued and verified.',s:9,o:1,d:2,rpn:18,by:{name:'Taylor Engineer',role:'Manufacturing Engineer',credentialId:'ACCT-tme',account:'tme'},at:new Date().toISOString()};t.analysisDone={by:pqm,at:new Date().toISOString()};}
  const res=FlightManeuver.pfmeaSafetyBuyoff(s,'PFM-301',{decision:'Approve',note:'Controls adequate.'});return {ok:res.ok,message:res.message,valid:MES.validate(s)};},[fn]);
await as('pqm');
r=await variant('closer');ok('the QA Manager who closed a PFMEA action is refused the Safety Team buy-off',r.ok===false&&/you recorded part of this analysis/.test(r.message),JSON.stringify(r));
r=await variant('completer');ok('the QA Manager who completed the analysis is refused the Safety Team buy-off',r.ok===false&&/you recorded part of this analysis/.test(r.message),JSON.stringify(r));
r=await variant('scoper');ok('the QA Manager who recorded the scope and team is refused the Safety Team buy-off',r.ok===false&&/you recorded part of this analysis/.test(r.message),JSON.stringify(r));
r=await variant('actions');ok('the QA Manager who completed the action step is refused the Safety Team buy-off',r.ok===false&&/you recorded part of this analysis/.test(r.message),JSON.stringify(r));
r=await variant('setter');ok('the QA Manager who set a PFMEA action, owner and due date is refused the Safety Team buy-off',r.ok===false&&/you recorded part of this analysis/.test(r.message),JSON.stringify(r));
r=await run(()=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');t.status='Analysis';const res=FlightManeuver.setPfmeaAction(s,'PFM-301',t.rows[0].id,{action:'Add a kit label scan',owner:'T. Engineer',due:'2026-12-01'});return {ok:res.ok,message:res.message,by:t.rows[0].actionSet&&t.rows[0].actionSet.by.credentialId,valid:MES.validate(s)};});
ok('setting a PFMEA action records who set it',r.ok===true&&r.by==='ACCT-pqm'&&r.valid===true,JSON.stringify(r));
r=await variant('overwrittenSetter');ok('a QA Manager whose action assignment was later re-set by someone else is still refused the Safety Team buy-off',r.ok===false&&/you recorded part of this analysis/.test(r.message),JSON.stringify(r));
r=await variant('clearedCloser');ok('a QA Manager whose action closure was later cleared is still refused the Safety Team buy-off',r.ok===false&&/you recorded part of this analysis/.test(r.message),JSON.stringify(r));
r=await variant('clearedCompleter');ok('a QA Manager who completed the analysis before a Safety Team return is still refused the Safety Team buy-off',r.ok===false&&/you recorded part of this analysis/.test(r.message),JSON.stringify(r));
r=await variant('returner');ok('a Safety Team member who returned the PFMEA may still give the buy-off after the rework',r.ok===true,JSON.stringify(r));
r=await variant('agedOut');ok('a QA Manager whose contribution has aged out of the 200-entry history is still refused, from the contributor list',r.ok===false&&/you recorded part of this analysis/.test(r.message),JSON.stringify(r));
r=await run(()=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');t.status='Analysis';const before=(t.contributors||[]).length;const res=FlightManeuver.setPfmeaAction(s,'PFM-301',t.rows[0].id,{action:'Add a kit label scan',owner:'T. Engineer',due:'2026-12-01'});return {ok:res.ok,has:(t.contributors||[]).includes('ACCT-pqm'),valid:MES.validate(s),dup:(()=>{FlightManeuver.setPfmeaAction(s,'PFM-301',t.rows[0].id,{action:'Add a kit label scan',owner:'T. Engineer',due:'2026-12-02'});return t.contributors.filter(c=>c==='ACCT-pqm').length;})()};});
ok('a PFMEA step records its actor once in the contributor list, which validates',r.ok===true&&r.has===true&&r.valid===true&&r.dup===1,JSON.stringify(r));
r=await run(()=>{const out={};const mk=f=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');f(t);return MES.validate(s);};out.notArray=mk(t=>{t.contributors='ACCT-x';});out.dup=mk(t=>{t.contributors=['ACCT-x','ACCT-x'];});out.nonString=mk(t=>{t.contributors=[{}];});return out;});
ok('validation refuses a malformed contributor list',r.notArray===false&&r.dup===false&&r.nonString===false,JSON.stringify(r));
// A PFMEA from before contributors were kept, whose history has reached its 200-entry cap, may have lost a contributor:
// anyone who can edit or approve work instructions is refused; a Safety Team member without those rights gives it.
const trimmed=(user,complete)=>run(([complete])=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');t.history=(t.history||[]).filter(h=>!String(h.actor||'').endsWith('ACCT-pqm'));t.contributors=(t.contributors||[]).filter(c=>c!=='ACCT-pqm');delete t.reviewed[Object.keys(t.reviewed).find(k=>t.reviewed[k].by.credentialId==='ACCT-pqm')];while(t.history.length<200)t.history.push({at:new Date().toISOString(),action:'Filler entry.',actor:'Taylor Engineer · ACCT-tme'});if(complete)t.contributorsComplete=true;else delete t.contributorsComplete;const res=FlightManeuver.pfmeaSafetyBuyoff(s,'PFM-301',{decision:'Approve',note:'Controls adequate.'});return {ok:res.ok,message:res.message,valid:MES.validate(s)};},[complete]);
await as('pqm');r=await trimmed('pqm',false);ok('on a pre-upgrade PFMEA with a trimmed history, a QA Manager (who can edit work instructions) is refused the buy-off',r.ok===false&&/history has been trimmed/.test(r.message),JSON.stringify(r));
await as('ssafe');r=await trimmed('ssafe',false);ok('on the same PFMEA, a Safety Team member is refused too: current roles are no evidence of who never contributed',r.ok===false&&/history has been trimmed/.test(r.message)&&/new revision of the work instruction/.test(r.message),JSON.stringify(r));
await as('pqm');r=await run(()=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');delete t.contributorsComplete;delete t.contributors;t.history=t.history.slice(0,10);while(t.history.length<199)t.history.push({at:new Date().toISOString(),action:'Filler entry.',actor:'Taylor Engineer · ACCT-tme'});t.status='Analysis';const res=FlightManeuver.setPfmeaAction(s,'PFM-301',t.rows[0].id,{action:'Add a kit label scan',owner:'T. Engineer',due:'2026-12-01'});return {ok:res.ok,message:res.message,len:t.history.length,complete:t.contributorsComplete,unconfirmed:MES.pfmeaContributorsUnconfirmed(t),valid:MES.validate(s)};});
ok('a pre-upgrade PFMEA whose history never reached the cap is marked complete on its next step, so reaching the cap later does not block it',r.len===200&&r.complete===true&&r.unconfirmed===false&&r.valid===true,JSON.stringify(r));
await as('pqm');r=await trimmed('pqm',true);ok('a PFMEA that kept every contributor from the start is not refused for a full history',r.ok===true,JSON.stringify(r));
r=await run(()=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');delete t.contributorsComplete;delete t.contributors;t.history=[{at:new Date().toISOString(),action:'FM-1 action: Old action (owner A, due 2026-12-01).',actor:'Lee Manager · ACCT-lqm'}];while(t.history.length<200)t.history.push({at:new Date().toISOString(),action:'Filler entry.',actor:'Taylor Engineer · ACCT-tme'});t.status='Analysis';const res=FlightManeuver.setPfmeaAction(s,'PFM-301',t.rows[0].id,{action:'Add a kit label scan',owner:'T. Engineer',due:'2026-12-01'});return {ok:res.ok,trimmed:!t.history.some(h=>String(h.actor).endsWith('ACCT-lqm')),kept:(t.contributors||[]).includes('ACCT-lqm'),contributor:MES.pfmeaContributors(t).has('ACCT-lqm'),valid:MES.validate(s)};});
ok('at the upgrade boundary, a contributor named only in the oldest history entry is kept in the contributor list when the next step trims that entry',r.ok===true&&r.trimmed===true&&r.kept===true&&r.contributor===true&&r.valid===true,JSON.stringify(r));
r=await run(()=>{const s=structuredClone(state);const wi=s.masterWIs.find(w=>!(s.maneuver.pfmeas||[]).some(t=>t.wiId===w.id&&t.wiRevision===w.revision));if(!wi)return {none:true};const res=FlightManeuver.openPFMEA(s,wi.id,wi.revision);const t=(s.maneuver.pfmeas||[]).find(x=>x.id===res.id);return {ok:res.ok,complete:t&&t.contributorsComplete,list:t&&t.contributors,valid:MES.validate(s)};});
ok('a newly opened PFMEA keeps every contributor from the start',r.ok===true&&r.complete===true&&Array.isArray(r.list)&&r.list.length===1&&r.valid===true,JSON.stringify(r));
r=await variant('legacySetter');ok('a QA Manager named in the history as setting an action on a pre-upgrade row is refused the Safety Team buy-off',r.ok===false&&/you recorded part of this analysis/.test(r.message),JSON.stringify(r));
r=await variant('legacyUnknown');ok('a pre-upgrade action whose setter is not on record refuses the Safety Team buy-off until it is recorded again',r.ok===false&&/does not show who assigned the action on FM-2/.test(r.message),JSON.stringify(r));
r=await run(()=>[...MES.pfmeaContributors({rows:[{id:'FM-9',by:null,action:'Scan the label'}],history:[{action:'FM-9 action: Scan the label (owner A, due 2026-12-01).',actor:'A · B · ACCT-x'},{action:'FM-90 action: other',actor:'Z · ACCT-z'}],reviewed:{}})]);
ok('every person the ticket history names counts, read from the credential at the end of the history actor',JSON.stringify(r.sort())==='["ACCT-x","ACCT-z"]',JSON.stringify(r));
r=await variant('none');ok('with none of that work, the same QA Manager gives the buy-off',r.ok===true,JSON.stringify(r));

// ---- the Safety Team role gives it, and the manifest binds the analysis content ----
await as('ssafe');
r=await run(()=>{const res=FlightManeuver.pfmeaSafetyBuyoff(state,'PFM-301',{decision:'Approve',note:'Controls adequate for every failure mode.'});if(res.ok)save();const t=FlightManeuver.get(state,'pfmeas','PFM-301');return {ok:res.ok,message:res.message,subject:t.safety&&t.safety.manifest&&t.safety.manifest.subject,verify:MES.verifyManifests(state)};});
ok('the Safety Team gives the buy-off',r.ok===true,JSON.stringify(r));
const sub=r.subject||{};
ok('the signed subject carries the Safety Team rationale',sub.note==='Controls adequate for every failure mode.',JSON.stringify(sub));
ok('the signed subject carries each failure mode, effect, cause, controls and scores',Array.isArray(sub.rows)&&sub.rows[0].mode==='Wrong kit issued'&&sub.rows[0].effect==='Non-conforming part'&&sub.rows[0].cause==='Label not checked'&&sub.rows[0].controls==='Kit list'&&sub.rows[0].s===4&&sub.rows[0].by==='ACCT-tme',JSON.stringify(sub.rows));
ok('the signed subject carries every no-risk rationale and who recorded it',Array.isArray(sub.reviewed)&&sub.reviewed.some(v=>v.opId===fx.op&&/next inspection/.test(v.note)&&v.by==='ACCT-pqm'),JSON.stringify(sub.reviewed));
ok('the signed subject carries the scope and team',sub.scope&&/Safety Team representative/.test(sub.scope.team),JSON.stringify(sub.scope));
ok('every manifest verifies after the buy-off',r.verify.ok===true,JSON.stringify(r.verify.failures));

// ---- an edit after signing fails verification ----
const tamper=fn=>run(([fn])=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');
  if(fn==='note')t.safety.note='Rubber stamp.';if(fn==='cause')t.rows[0].cause='Not recorded';if(fn==='controls')t.rows[0].controls='';if(fn==='reviewed')t.reviewed[Object.keys(t.reviewed)[0]].note='Edited after the buy-off.';if(fn==='scope')t.scope.team='Nobody';if(fn==='signer')t.safety.by={...t.safety.by,credentialId:'ACCT-someone',name:'Someone Else'};if(fn==='signerName')t.safety.by={...t.safety.by,name:'Someone Else'};if(fn==='signerRole')t.safety.by={...t.safety.by,role:'Quality Manager'};if(fn==='signedAt')t.safety.at='2020-01-01T00:00:00.000Z';if(fn==='analysisBy')t.analysisDone.by={...t.analysisDone.by,credentialId:'ACCT-someone'};if(fn==='actionsAt')t.actionsDone.at='2020-01-01T00:00:00.000Z';
  const v=MES.verifyManifests(s);return {ok:v.ok,failures:v.failures};},[fn]);
for(const [fn,what] of [['note','the Safety Team rationale'],['cause','a failure-mode cause'],['controls','the current controls'],['reviewed','a no-risk rationale'],['scope','the scope and team'],['signer','who gave the Safety Team buy-off'],['signerName','the Safety Team signer name'],['signerRole','the Safety Team signer role'],['signedAt','when the Safety Team buy-off was given'],['analysisBy','who completed the analysis'],['actionsAt','when the action step was completed']]){
  r=await tamper(fn);ok(`editing ${what} after the buy-off fails verification`,r.ok===false&&r.failures.some(f=>/PFM-301 Safety Team buy-off/.test(f.where)),JSON.stringify(r));
}

// ---- a recorded Safety Team buy-off without its manifest fails ----
r=await run(()=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');delete t.safety.manifest;const v=MES.verifyManifests(s);return {ok:v.ok,failures:v.failures,valid:MES.validate(s)};});
ok('deleting the Safety Team buy-off manifest fails verification',r.ok===false&&r.failures.some(f=>/PFM-301 Safety Team buy-off/.test(f.where)&&/no signature manifest/.test(f.reason)),JSON.stringify(r));
ok('deleting the Safety Team buy-off manifest makes the workspace invalid',r.valid===false,JSON.stringify(r));
r=await run(()=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');t.safety.manifest=null;return {ok:MES.verifyManifests(s).ok,valid:MES.validate(s)};});
ok('a null Safety Team buy-off manifest fails the same way',r.ok===false&&r.valid===false,JSON.stringify(r));
r=await run(()=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');t.safety=null;const v=MES.verifyManifests(s);return {status:t.status,ok:v.ok,failures:v.failures.filter(f=>/PFM-301/.test(f.where)).map(f=>f.reason),valid:MES.validate(s)};});
ok('an Approved PFMEA whose Safety Team buy-off record is removed fails verification and validation',r.status==='Approved'&&r.ok===false&&r.failures.some(x=>/no Safety Team buy-off record/.test(x))&&r.valid===false,JSON.stringify(r));
r=await run(()=>{const out={};const mk=f=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');f(t);return MES.validate(s);};out.clean=mk(()=>{});out.empty=mk(t=>{t.safety.manifest={};});out.noHash=mk(t=>{delete t.safety.manifest.hash;});out.badAlg=mk(t=>{t.safety.manifest.algorithm='MD5';});out.otherSigner=mk(t=>{t.safety.manifest.signer={...t.safety.manifest.signer,credentialId:'ACCT-other'};});out.otherTime=mk(t=>{t.safety.manifest.at='2026-01-01T00:00:00.000Z';});out.noSubject=mk(t=>{delete t.safety.manifest.subject;});out.earlyForm=mk(t=>{t.safety.manifest=MES.signManifest(state,t.safety.manifest.meaning,MES.pfmeaSafetyLegacySubject(t),t.safety.at);t.safety.manifest.signer={...t.safety.manifest.signer,name:t.safety.by.name,role:t.safety.by.role,credentialId:t.safety.by.credentialId};delete t.safety.manifest.subject;});out.noTimes=mk(t=>{delete t.safety.at;delete t.safety.manifest.at;});out.bareSigner=mk(t=>{t.safety.manifest.signer={credentialId:t.safety.manifest.signer.credentialId};});out.otherName=mk(t=>{t.safety.manifest.signer={...t.safety.manifest.signer,name:'Someone Else'};});out.noRole=mk(t=>{delete t.safety.manifest.signer.role;});out.otherRole=mk(t=>{t.safety.manifest.signer={...t.safety.manifest.signer,role:'Technician'};});out.emptySubject=mk(t=>{t.safety.manifest.subject={};});out.legacySubject=mk(t=>{t.safety.manifest.subject=MES.pfmeaSafetyLegacySubject(t);});out.otherNote=mk(t=>{t.safety.manifest.subject={...t.safety.manifest.subject,note:'Something else.'};});out.liveNote=mk(t=>{t.safety.note='Edited after signing.';});out.liveRow=mk(t=>{t.rows[0].controls='Edited after signing';});out.liveScope=mk(t=>{t.scope.team='Edited team';});out.earlyLiveRpn=mk(t=>{t.safety.manifest=MES.signManifest(state,t.safety.manifest.meaning,MES.pfmeaSafetyLegacySubject(t),t.safety.at);t.safety.manifest.signer={...t.safety.manifest.signer,name:t.safety.by.name,role:t.safety.by.role,credentialId:t.safety.by.credentialId};delete t.safety.manifest.subject;t.rows[0].opId='OP-EDITED';});out.earlyStored=mk(t=>{t.safety.manifest=MES.signManifest(state,t.safety.manifest.meaning,MES.pfmeaSafetyLegacySubject(t),t.safety.at);t.safety.manifest.signer={...t.safety.manifest.signer,name:t.safety.by.name,role:t.safety.by.role,credentialId:t.safety.by.credentialId};});return out;});
ok('validation (standalone saves) refuses an empty or incomplete Safety Team manifest (including one with both times removed or a credential-only signer) and one whose signer or time differs from the buy-off; a current manifest stripped of its subject is refused, and an early one whose hash is the older ids-and-RPN subject still validates',r.clean===true&&['empty','noHash','badAlg','otherSigner','otherTime','noTimes','bareSigner','otherName','noRole','otherRole'].every(k=>r[k]===false)&&r.noSubject===false&&r.earlyForm===true,JSON.stringify(r));
ok('validation (standalone saves) recomputes the Safety Team subject from the stored PFMEA: a stored subject replaced with {}, with the older form, or with another rationale is refused, and so is a rationale, failure mode or scope edited after signing; an early manifest is refused once its rows change, and still validates with or without its stored subject',['emptySubject','legacySubject','otherNote','liveNote','liveRow','liveScope','earlyLiveRpn'].every(k=>r[k]===false)&&r.earlyStored===true&&r.earlyForm===true,JSON.stringify(r));
r=await run(()=>{const out={};const base=()=>{const s=structuredClone(state);return [s,s.maneuver.pfmeas.find(x=>x.id==='PFM-301')];};const both=(f)=>{const [s,t]=base();f(t);return {valid:MES.validate(s),verify:MES.verifyManifests(s).ok};};const t0=base()[1];out.signedBy=t0.safety.manifest.subject.signedBy;out.signedAt=t0.safety.manifest.subject.signedAt;out.at=t0.safety.at;out.by=t0.safety.by;out.name=both(t=>{t.safety.by={...t.safety.by,name:'Someone Else'};t.safety.manifest.signer={...t.safety.manifest.signer,name:'Someone Else'};});out.role=both(t=>{t.safety.by={...t.safety.by,role:'Technician'};t.safety.manifest.signer={...t.safety.manifest.signer,role:'Technician'};});out.cred=both(t=>{t.safety.by={...t.safety.by,credentialId:'ACCT-other'};t.safety.manifest.signer={...t.safety.manifest.signer,credentialId:'ACCT-other'};});out.time=both(t=>{t.safety.at='2026-01-02T00:00:00.000Z';t.safety.manifest.at='2026-01-02T00:00:00.000Z';});out.noteOnly=both(t=>{const m=MES.signManifest(state,t.safety.manifest.meaning,MES.pfmeaSafetySubject(t,t.safety.note),t.safety.at);m.signer={...m.signer,name:t.safety.by.name,role:t.safety.by.role,credentialId:t.safety.by.credentialId};t.safety.manifest=m;});out.noteOnlyEdited=both(t=>{const m=MES.signManifest(state,t.safety.manifest.meaning,MES.pfmeaSafetySubject(t,t.safety.note),t.safety.at);m.signer={...m.signer,name:t.safety.by.name,role:t.safety.by.role,credentialId:t.safety.by.credentialId};t.safety.manifest=m;t.rows[0].controls='Edited after signing';});return out;});
ok('the signed subject binds the Safety Team signer (credential, name, role) and the buy-off time',r.signedBy&&r.by&&r.signedBy.credentialId===r.by.credentialId&&r.signedBy.name===r.by.name&&r.signedBy.role===r.by.role&&r.signedAt===r.at,JSON.stringify([r.signedBy,r.signedAt,r.by,r.at]));
ok('editing the buy-off signer name, role or credential, or its time, together with the manifest signer or time fails both validation and verification',['name','role','cred','time'].every(k=>r[k].valid===false&&r[k].verify===false),JSON.stringify(r));
ok('a buy-off signed before the signer was bound (rationale subject, no signedBy) still validates and verifies, and still fails once its analysis is edited',r.noteOnly.valid===true&&r.noteOnly.verify===true&&r.noteOnlyEdited.valid===false&&r.noteOnlyEdited.verify===false,JSON.stringify([r.noteOnly,r.noteOnlyEdited]));

// ---- a buy-off signed before this rule keeps verifying against what it stored ----
r=await run(()=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');const legacy={pfmea:t.id,wi:`${t.wiId} Rev ${t.wiRevision}`,rows:t.rows.map(r=>({id:r.id,opId:r.opId,rpn:r.rpn,revised:r.done?r.done.rpn:null}))};t.safety.manifest=MES.signManifest(s,'PFMEA Safety Team buy-off',legacy,t.safety.at);t.rows[0].cause='Edited later';const v=MES.verifyManifests(s);return {ok:v.ok,failures:v.failures,valid:MES.validate(s)};});
ok('an older buy-off manifest (ids and RPNs only) still verifies and the workspace still loads',r.ok===true&&r.valid===true,JSON.stringify(r));
r=await run(()=>{const s=structuredClone(state),t=s.maneuver.pfmeas.find(x=>x.id==='PFM-301');const legacy={pfmea:t.id,wi:`${t.wiId} Rev ${t.wiRevision}`,rows:t.rows.map(r=>({id:r.id,opId:r.opId,rpn:r.rpn,revised:r.done?r.done.rpn:null}))};t.safety.manifest=MES.signManifest(s,'PFMEA Safety Team buy-off',legacy,t.safety.at);const edit=f=>{const c=structuredClone(s),x=c.maneuver.pfmeas.find(y=>y.id==='PFM-301');f(x);const v=MES.verifyManifests(c);return v.failures.some(e=>/PFM-301 Safety Team buy-off/.test(e.where));};return {opId:edit(x=>{x.rows[0].opId='op-999';}),rpn:edit(x=>{x.rows[0].s=5;x.rows[0].rpn=60;}),rowId:edit(x=>{x.rows[0].id='FM-9';})};});
ok('an older buy-off is still recomputed from the live rows: an operation, RPN or row id edit fails',r.opId&&r.rpn&&r.rowId,JSON.stringify(r));

ok('state valid at end',await run(()=>MES.validate(state)));
ok('no page errors',errs.length===0,errs.join(' | '));
console.log('errors',errs,'FAILS',JSON.stringify(fails));await b.close();
process.exit(fails.length?1:0);
