import assert from 'node:assert/strict';
import { createHost } from '../server/mes-host.mjs';
import { fileURLToPath } from 'node:url';
const host=createHost(fileURLToPath(new URL('../index.html',import.meta.url))),{MES}=host,state=MES.ensureMasterWIs(MES.seed());
const qe={username:'skill-qe',displayName:'Quality Engineer',role:'qe'},qm={username:'skill-qm',displayName:'Quality Manager',role:'qm'},admin={username:'skill-admin',displayName:'Master Access',role:'admin'};
const as=(account,fn)=>host.withAccount(account,fn,state);let checks=0;const check=(name,ok)=>{checks++;assert.ok(ok,name);console.log(`ok ${name}`);};
check('only the twelve approved Flight skills are available and excluded automotive or WI revision skills are absent',MES.FLIGHT_SKILLS.length===12&&!MES.FLIGHT_SKILLS.some(s=>['apqp','ppap','control-plan','training','wi-revision'].includes(s.key))&&!MES.runSkill(state,{skill:'apqp',reason:'Test excluded skill'}).ok);
const wi=state.masterWIs.find(item=>item.status==='Draft');
const plan=wi&&as(admin,()=>MES.setForm3Plan(state,wi.id,wi.revision,[{balloon:1,characteristic:'Bore diameter',requirement:'10.00 ±0.05 mm'},{balloon:2,characteristic:'Hole position',requirement:'⌀0.2 to datum A|B'}]));
check('Form 3 plan is tied to an editable master WI draft and carries a verifying digest',!!plan?.ok&&wi.form3Plan.balloonCount===2&&wi.form3Plan.sha256===MES.sha256(MES.canonical(wi.form3Plan.characteristics))&&MES.validate(state)&&MES.verifyManifests(state).ok);
check('malformed or duplicate Form 3 balloon numbers are refused without replacing the saved plan',!as(admin,()=>MES.setForm3Plan(state,wi.id,wi.revision,[{balloon:1,characteristic:'One',requirement:'A'},{balloon:1,characteristic:'Two',requirement:'B'}])).ok&&wi.form3Plan.balloonCount===2);
check('skill run needs a reason and creates a draft without mutating any target record',!as(qe,()=>MES.runSkill(state,{skill:'five-why',problem:'fit issue'})).ok);
const before=JSON.stringify(state.orders);
check('only QA Manager or Master Access can create a signed skill trigger',!as(qe,()=>MES.setSkillTrigger(state,{skill:'five-why',event:'nc-raised',enabled:true,rationale:'Approved NC analysis trigger.'})).ok);
const trigger=as(qm,()=>MES.setSkillTrigger(state,{skill:'five-why',event:'nc-raised',enabled:true,rationale:'Approved NC analysis trigger.'}));
const first=as(qm,()=>MES.runSkill(state,{skill:'five-why',problem:'Part failed fit',reason:'Investigate reported fit issue',targetRefs:['NC-1'],triggerId:trigger.id}));
check('five-why draft is deterministic, references its target and leaves production records untouched',first.ok&&state.aiSkillDrafts[0].body.whyChain.length===5&&state.aiSkillDrafts[0].targetRefs[0]==='NC-1'&&JSON.stringify(state.orders)===before&&MES.verifyAIActionLog(state).ok&&MES.verifyManifests(state).ok);
const duplicate=as(qm,()=>MES.runSkill(state,{skill:'five-why',problem:'Part failed fit',reason:'Investigate reported fit issue',targetRefs:['NC-1'],triggerId:trigger.id}));
check('replaying the same trigger and input creates no second draft or action',duplicate.ok&&duplicate.duplicate&&state.aiSkillDrafts.length===1&&state.aiActionLog.length===1);
check('every [confirm] scaffold blocks acceptance as a finding',as(qm,()=>MES.reviewSkillDraft(state,first.id,'Reviewed draft.')).ok&&!as(admin,()=>MES.acceptSkillDraft(state,first.id,'Accept')).ok&&state.aiSkillDrafts[0].status==='Reviewed');
check('reviewer cannot accept their own review',!as(qm,()=>MES.acceptSkillDraft(state,first.id,'Same person')).ok);
const updated=as(qm,()=>MES.updateSkillDraft(state,first.id,{problem:'Verified fit interference at Op 20.',whyChain:[{step:1,statement:'Lot verification was omitted.'}],rootCause:'Kit lot verification was omitted.'},'Replaced scaffolds with evidence from NC-1.'));
as(qm,()=>MES.reviewSkillDraft(state,first.id,'Reviewed edited analysis against NC-1.'));
check('a different qualified person can accept completed, scaffold-free analysis while source records remain unchanged',updated.ok&&as(admin,()=>MES.acceptSkillDraft(state,first.id,'Accepted after evidence review.')).ok&&MES.validate(state)&&MES.verifyManifests(state).ok&&JSON.stringify(state.orders)===before);
const spc=as(qe,()=>MES.runSkill(state,{skill:'spc-chart-builder',values:[10.01,10.02,9.99,10,10.01],lsl:9.9,usl:10.1,reason:'Summarize supplied measurements.',targetRefs:['LOT-1']}));
const spcBody=state.aiSkillDrafts.at(-1)?.body;
check('SPC draft computes I-MR limits, stability signals, and capability from verified numeric readings',spc.ok&&spcBody.n===5&&spcBody.chart==='Individuals and moving range (I-MR)'&&spcBody.ucl>spcBody.xbar&&spcBody.lcl<spcBody.xbar&&spcBody.cpk>0&&Array.isArray(spcBody.signals)&&state.aiActionLog.at(-1).outputHash&&MES.verifyAIActionLog(state).ok);
const msa=as(qe,()=>MES.runSkill(state,{skill:'msa-gage-rr-builder',gage:'CAL-001',data:{operators:[{name:'A',parts:[[10,10.1],[20,20.1]]},{name:'B',parts:[[10.2,10.3],[20.2,20.3]]}]},tolerance:10,reason:'Evaluate the gage using the completed crossed study.',targetRefs:['STUDY-1']}));
const msaBody=state.aiSkillDrafts.at(-1)?.body;
check('MSA draft computes repeatability, reproducibility, percent GRR and distinct categories for a balanced crossed study',msa.ok&&msaBody.studyDesign.parts===2&&msaBody.ev>0&&msaBody.av>0&&msaBody.grr>0&&msaBody.pctGRR<10&&msaBody.ndc>=5&&state.aiActionLog.at(-1).outputHash&&MES.verifyAIActionLog(state).ok);
console.log(`qms_skills: ${checks} checks, all passed`);
