import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHost } from '../server/mes-host.mjs';
import { fileURLToPath } from 'node:url';
const host=createHost(fileURLToPath(new URL('../index.html',import.meta.url))),{MES,FlightManeuver}=host,state=MES.ensureMasterWIs(MES.seed());
const qe={username:'skill-qe',displayName:'Quality Engineer',role:'qe'},qm={username:'skill-qm',displayName:'Quality Manager',role:'qm'},admin={username:'skill-admin',displayName:'Master Access',role:'admin'};
const as=(account,fn)=>host.withAccount(account,fn,state);let checks=0;const check=(name,ok)=>{checks++;assert.ok(ok,name);console.log(`ok ${name}`);};
FlightManeuver.ensure(state);
const nc=as(qm,()=>FlightManeuver.raiseNC(state,{title:'Supplier anodize shade variation',description:'Supplier dye lot changed and the receiving inspection found shade variation.',partNumber:'PN-SKILL-1',revision:'A',sourceType:'PO line',sourcePo:'PO-SKILL',sourceLine:'1',foundAt:'Receiving inspection',quantity:3,pedigree:'Production'}));
assert.ok(nc.ok);
const due=new Date();due.setDate(due.getDate()+30);
const car=as(qm,()=>FlightManeuver.raiseCAR(state,{title:'Supplier anodize shade variation',description:'Investigate repeated shade variation reported by receiving inspection.',sourceType:'NC',severity:'Minor',dueDate:due.toISOString().slice(0,10),ref:nc.id}));
assert.ok(car.ok);
check('only the twelve approved Flight skills are available and excluded automotive or WI revision skills are absent',MES.FLIGHT_SKILLS.length===12&&!MES.FLIGHT_SKILLS.some(s=>['apqp','ppap','control-plan','training','wi-revision'].includes(s.key))&&!MES.runSkill(state,{skill:'apqp',reason:'Test excluded skill'}).ok);
const wi=state.masterWIs.find(item=>item.status==='Draft');
const plan=wi&&as(admin,()=>MES.setForm3Plan(state,wi.id,wi.revision,[{balloon:1,characteristic:'Bore diameter',requirement:'10.00 ±0.05 mm'},{balloon:2,characteristic:'Hole position',requirement:'⌀0.2 to datum A|B'}]));
check('Form 3 plan is tied to an editable master WI draft and carries a verifying digest',!!plan?.ok&&wi.form3Plan.balloonCount===2&&wi.form3Plan.sha256===MES.sha256(MES.canonical(wi.form3Plan.characteristics))&&MES.validate(state)&&MES.verifyManifests(state).ok);
check('malformed or duplicate Form 3 balloon numbers are refused without replacing the saved plan',!as(admin,()=>MES.setForm3Plan(state,wi.id,wi.revision,[{balloon:1,characteristic:'One',requirement:'A'},{balloon:1,characteristic:'Two',requirement:'B'}])).ok&&wi.form3Plan.balloonCount===2);
check('skill run needs a reason and creates a draft without mutating any target record',!as(qe,()=>MES.runSkill(state,{skill:'five-why',problem:'fit issue'})).ok);
const before=JSON.stringify(state.orders);
check('only QA Manager or Master Access can create a signed skill trigger',!as(qe,()=>MES.setSkillTrigger(state,{skill:'five-why',event:'nc-raised',enabled:true,rationale:'Approved NC analysis trigger.'})).ok);
const trigger=as(qm,()=>MES.setSkillTrigger(state,{skill:'five-why',event:'nc-raised',enabled:true,rationale:'Approved NC analysis trigger.'}));
const first=as(qm,()=>MES.runSkill(state,{skill:'five-why',reason:'Investigate the source nonconformance.',targetRefs:[nc.id],triggerId:trigger.id}));
check('five-why draft requires and cites a real NC, separates record facts from five unverified causes, and leaves production records untouched',first.ok&&state.aiSkillDrafts[0].body.whyChain.length===5&&state.aiSkillDrafts[0].body.problem.id===nc.id&&state.aiSkillDrafts[0].body.whyChain.every(why=>why.status==='Needs investigation')&&state.aiSkillDrafts[0].targetRefs.includes(nc.id)&&JSON.stringify(state.orders)===before&&MES.verifyAIActionLog(state).ok&&MES.verifyManifests(state).ok);
check('five-why refuses an unknown record reference without writing an action or draft',!as(qm,()=>MES.runSkill(state,{skill:'five-why',reason:'Investigate a missing source record.',targetRefs:['NC-9999']})).ok&&state.aiSkillDrafts.length===1&&state.aiActionLog.length===1);
const duplicate=as(qm,()=>MES.runSkill(state,{skill:'five-why',reason:'Investigate the source nonconformance.',targetRefs:[nc.id],triggerId:trigger.id}));
check('replaying the same trigger and input creates no second draft or action',duplicate.ok&&duplicate.duplicate&&state.aiSkillDrafts.length===1&&state.aiActionLog.length===1);
const ballooning=as(qe,()=>MES.runSkill(state,{skill:'as9102-ballooning-v2',wiId:wi.id,revision:wi.revision,drawingReference:'DWG-SKILL-1 Rev A',reason:'Prepare a balloon review from the saved plan.'}));
const balloonBody=state.aiSkillDrafts.at(-1)?.body;
check('AS9102 ballooning drafts the exact WI Form 3 plan with its digest and controlled drawing comparison scaffold',ballooning.ok&&balloonBody.standard==='AS9102 Rev C'&&balloonBody.planHash===wi.form3Plan.sha256&&balloonBody.balloons.length===2&&balloonBody.balloons[0].number===1&&balloonBody.balloons[0].status.includes('[confirm]')&&balloonBody.evidenceReferences[0]===`${wi.id}|${wi.revision}`);
const noPlan=as(qe,()=>MES.runSkill(state,{skill:'as9102-ballooning-v2',wiId:'MWI-9999',revision:'A',characteristics:[{balloon:1}],reason:'Try an unregistered drawing plan.'}));
check('AS9102 ballooning refuses arbitrary characteristics not held in a saved WI plan',!noPlan.ok&&state.aiSkillDrafts.length===2);
const pfmea=as(admin,()=>FlightManeuver.openPFMEA(state,wi.id,wi.revision));
assert.ok(pfmea.ok);
const pfmeaBefore=JSON.stringify(state.maneuver.pfmeas.find(item=>item.id===pfmea.id));
const pfmeaDraft=as(qe,()=>MES.runSkill(state,{skill:'pfmea-builder',wiId:wi.id,revision:wi.revision,reason:'Prepare candidate risk modes for the WI team.'}));
const pfmeaBody=state.aiSkillDrafts.at(-1)?.body;
check('PFMEA builder uses the actual WI operations, records candidate hypotheses, and leaves S/O/D unscored',pfmeaDraft.ok&&pfmeaBody.wiId===wi.id&&pfmeaBody.rows.length>=wi.operations.length&&pfmeaBody.rows.every(row=>row.severity===null&&row.detection===null&&row.reviewStatus.includes('[confirm]'))&&pfmeaBody.evidenceReferences.includes(`${wi.id}|${wi.revision}`)&&JSON.stringify(state.maneuver.pfmeas.find(item=>item.id===pfmea.id))===pfmeaBefore);
const pfmeaCheck=as(qe,()=>MES.runSkill(state,{skill:'pfmea-checklist-reviewer',pfmeaId:pfmea.id,reason:'Check the PFMEA record coverage and fields.'}));
const pfmeaCheckBody=state.aiSkillDrafts.at(-1)?.body;
check('PFMEA checklist checks operation coverage and arithmetic while leaving the PFMEA approval to its existing workflow',pfmeaCheck.ok&&pfmeaCheckBody.pfmeaId===pfmea.id&&pfmeaCheckBody.checks.length===7&&pfmeaCheckBody.checks.some(item=>item.status.includes('[confirm]'))&&pfmeaCheckBody.conclusion.startsWith('Incomplete:')&&pfmeaCheckBody.limitations.some(item=>item.includes('not a standards conformity determination')));
const noPfmea=as(qe,()=>MES.runSkill(state,{skill:'pfmea-checklist-reviewer',pfmeaId:'PFM-9999',reason:'Check an unrecorded PFMEA.'}));
check('PFMEA checklist refuses unknown PFMEA IDs without adding a draft',!noPfmea.ok&&state.aiSkillDrafts.length===4);
const fairState=MES.upgrade(JSON.parse(readFileSync(new URL('../tools/demo/seed-curated.json',import.meta.url),'utf8')));
const fairBefore=JSON.stringify(fairState.orders);
const fairRun=host.withAccount(qe,()=>MES.runSkill(fairState,{skill:'fair-review-as9102',orderId:'WO-10004',reason:'Review the saved FAIR package.'}),fairState);
const fairBody=fairState.aiSkillDrafts.at(-1)?.body;
check('FAIR review analyzes a real FAI order snapshot and exposes gaps without signing or changing the FAIR',fairRun.ok&&fairBody.standard==='AS9102 Rev C'&&fairBody.forms.form1.partNumber===fairState.orders.find(order=>order.id==='WO-10004').partNumber&&fairBody.forms.form3.length===3&&Array.isArray(fairBody.findings)&&fairBody.approvalState.includes('does not verify')&&JSON.stringify(fairState.orders)===fairBefore);
const nonFai=host.withAccount(qe,()=>MES.runSkill(fairState,{skill:'fair-review-as9102',orderId:'WO-10001',reason:'Check a non-FAI work order.'}),fairState);
check('FAIR review refuses a non-FAI work order without writing a draft',!nonFai.ok&&fairState.aiSkillDrafts.length===1);
const fishbone=as(qe,()=>MES.runSkill(state,{skill:'fishbone',reason:'Sort the source NC evidence for review.',targetRefs:[nc.id]}));
const fishboneBody=state.aiSkillDrafts.at(-1)?.body;
check('fishbone groups real NC records only as transparent keyword candidates and stores the source ID',fishbone.ok&&fishboneBody.evidenceReferences.includes(nc.id)&&fishboneBody.categories.find(item=>item.category==='Material').evidence.some(item=>item.id===nc.id)&&fishboneBody.limitations.some(item=>item.includes('not a cause finding'))&&state.aiActionLog.at(-1).targetRefs.includes(nc.id));
const eightD=as(qe,()=>MES.runSkill(state,{skill:'eight-d-builder',reason:'Prepare the 8D from the source CAR and NC.',targetRefs:[car.id,nc.id]}));
const eightDBody=state.aiSkillDrafts.at(-1)?.body;
check('8D builder fills its eight disciplines from real CAR and NC fields and scaffolds missing evidence',eightD.ok&&eightDBody.disciplines.length===8&&eightDBody.evidenceReferences.includes(car.id)&&eightDBody.evidenceReferences.includes(nc.id)&&eightDBody.disciplines.find(item=>item.discipline.startsWith('D2')).content.partNumber==='PN-SKILL-1'&&eightDBody.disciplines.find(item=>item.discipline.startsWith('D3')).content.includes('[confirm]'));
const checklist=as(qe,()=>MES.runSkill(state,{skill:'eight-d-checklist-reviewer',reason:'Check the CAR record for 8D completeness.',targetRefs:[car.id]}));
const checklistBody=state.aiSkillDrafts.at(-1)?.body;
check('8D checklist reports present CAR fields separately from missing evidence and cannot approve the CAR',checklist.ok&&checklistBody.checklist.length===8&&checklistBody.checklist.find(item=>item.item==='D3 Containment').status.includes('[confirm]')&&checklistBody.conclusion.startsWith('Incomplete:')&&checklistBody.limitations.some(item=>item.includes('cannot judge technical adequacy')));
const prematureEffect=as(qe,()=>MES.runSkill(state,{skill:'effectiveness-follow-up',reason:'Check whether this CAR is ready for follow-up.',targetRefs:[car.id]}));
check('effectiveness follow-up refuses a CAR before independent verification and writes no draft',!prematureEffect.ok&&!state.aiSkillDrafts.some(draft=>draft.skill==='effectiveness-follow-up'));
as(qm,()=>FlightManeuver.recordContainment(state,car.id,'Receiving inspection isolated the affected lot.'));
as(qm,()=>FlightManeuver.recordRootCause(state,car.id,{why1:'The supplier dye process varied.',why2:'The dye concentration was not checked.',why3:'The supplier control did not require a logged check.',why4:'The purchase requirements omitted that verification.',why5:'Supplier process controls were not risk-reviewed.',fishMaterial:'Dye concentration varied between lots.',statement:'Supplier dye concentration was not controlled.',category:'Material'}));
const action=as(qm,()=>FlightManeuver.addAction(state,car.id,{description:'Add a documented concentration check to the supplier process.',owner:'Supplier Quality',dueDate:due.toISOString().slice(0,10)}));
assert.ok(action.ok);
assert.ok(as(qm,()=>FlightManeuver.completeAction(state,car.id,'CA-1','Supplier process sheet rev A records the concentration check.')).ok);
assert.ok(as(admin,()=>FlightManeuver.verifyCAR(state,car.id,'Confirmed the implemented supplier process check against the revised record.')).ok);
const carBeforeFollowup=JSON.stringify(state.maneuver.cars.find(item=>item.id===car.id));
const effect=as(qe,()=>MES.runSkill(state,{skill:'effectiveness-follow-up',reason:'Propose an evidence-based recurrence check.',days:60,targetRefs:[car.id,nc.id]}));
const effectBody=state.aiSkillDrafts.at(-1)?.body;
check('effectiveness follow-up derives the CAR verification date and prior NC baseline without recording an outcome',effect.ok&&effectBody.carId===car.id&&effectBody.partNumber==='PN-SKILL-1'&&effectBody.baseline.recordIds.includes(nc.id)&&effectBody.days===60&&effectBody.checkDate===new Date(Date.parse(effectBody.verification.at)+60*86400000).toISOString().slice(0,10)&&effectBody.criteria.includes('[confirm]')&&JSON.stringify(state.maneuver.cars.find(item=>item.id===car.id))===carBeforeFollowup);
check('every [confirm] scaffold blocks acceptance as a finding',as(qm,()=>MES.reviewSkillDraft(state,first.id,'Reviewed draft.')).ok&&!as(admin,()=>MES.acceptSkillDraft(state,first.id,'Accept')).ok&&state.aiSkillDrafts[0].status==='Reviewed');
check('reviewer cannot accept their own review',!as(qm,()=>MES.acceptSkillDraft(state,first.id,'Same person')).ok);
const updated=as(qm,()=>MES.updateSkillDraft(state,first.id,{problem:'Verified fit interference at Op 20.',whyChain:[{step:1,statement:'Lot verification was omitted.'}],rootCause:'Kit lot verification was omitted.'},'Replaced scaffolds with evidence from NC-1.'));
as(qm,()=>MES.reviewSkillDraft(state,first.id,'Reviewed edited analysis against NC-1.'));
check('a different qualified person can accept completed, scaffold-free analysis while source records remain unchanged',updated.ok&&as(admin,()=>MES.acceptSkillDraft(state,first.id,'Accepted after evidence review.')).ok&&MES.validate(state)&&MES.verifyManifests(state).ok&&JSON.stringify(state.orders)===before);
const spc=as(qe,()=>MES.runSkill(state,{skill:'spc-chart-builder',values:[10.01,10.02,9.99,10,10.01],lsl:9.9,usl:10.1,reason:'Summarize supplied measurements.',targetRefs:['LOT-1']}));
const spcBody=state.aiSkillDrafts.at(-1)?.body;
check('SPC draft computes I-MR limits, stability signals, and capability from verified numeric readings',spc.ok&&spcBody.n===5&&spcBody.chart==='Individuals and moving range (I-MR)'&&spcBody.ucl>spcBody.xbar&&spcBody.lcl<spcBody.xbar&&spcBody.cpk>0&&Array.isArray(spcBody.signals)&&state.aiActionLog.at(-1).outputHash&&MES.verifyAIActionLog(state).ok);
const msa=as(qe,()=>MES.runSkill(state,{skill:'msa-gage-rr-builder',gage:'CAL-001',data:{operators:[{name:'A',parts:[[10,10.1],[20,20.1]]},{name:'B',parts:[[10.2,10.3],[20.2,20.3]]}]},tolerance:10,reason:'Evaluate the gage using the completed crossed study.',targetRefs:['STUDY-1']}));
const msaBody=state.aiSkillDrafts.at(-1)?.body;
check('MSA draft computes repeatability, reproducibility, percent GRR and distinct categories for a balanced crossed study',msa.ok&&msaBody.studyDesign.parts===2&&msaBody.ev>0&&msaBody.av>0&&msaBody.grr>0&&msaBody.pctGRR<10&&msaBody.ndc>=5&&state.aiActionLog.at(-1).outputHash&&MES.verifyAIActionLog(state).ok);
const drawingBefore=JSON.stringify(state.masterWIs);
const drawing=as(qe,()=>MES.runSkill(state,{skill:'dwg-review',reason:'Prepare a checklist for an engineering drawing review.',drawingReference:'DWG-SKILL-42',revision:'B',units:'mm',generalTolerance:'ISO 2768-mK',datumReferences:['A','B','C'],dimensions:[{feature:'Mounting bore',nominal:'10.00',tolerance:'±0.05'}],geometricControls:[{feature:'Mounting bore',control:'Position ⌀0.2',datums:['A','B','C']}],notes:['Deburr all edges'],targetRefs:['DWG-SKILL-42']}));
const drawingBody=state.aiSkillDrafts.at(-1)?.body;
check('drawing review inventories supplied references and structured drawing data as human verification items, cites source, and never changes controlled records',drawing.ok&&drawingBody.drawing.revision==='B'&&drawingBody.datumReferences.length===3&&drawingBody.dimensions[0].nominal==='10.00'&&drawingBody.geometricControls[0].datums.length===3&&drawingBody.checklist.every(item=>item.status.startsWith('Input supplied'))&&drawingBody.decision.includes('No drawing image')&&drawingBody.evidenceReferences.includes('DWG-SKILL-42')&&JSON.stringify(state.masterWIs)===drawingBefore);
const incompleteDrawing=as(qe,()=>MES.runSkill(state,{skill:'dwg-review',reason:'Check which drawing review inputs remain missing.',drawingReference:'DWG-SKILL-42',revision:'B'}));
const incompleteBody=state.aiSkillDrafts.at(-1)?.body;
check('drawing review leaves absent drawing fields as explicit confirmation scaffolds and does not claim standards compliance',incompleteDrawing.ok&&incompleteBody.checklist.filter(item=>!item.provided).length===5&&incompleteBody.checklist.filter(item=>!item.provided).every(item=>item.status.includes('[confirm]'))&&incompleteBody.limitations.some(item=>item.includes('performs no OCR or CAD geometry inspection')));
console.log(`qms_skills: ${checks} checks, all passed`);
