import assert from 'node:assert/strict';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const {
  claudeApproved,
  hasProtectedAutoMergeChange,
  hasUnresolvedImportant,
  isImportantFinding,
  jinxApproved,
  latestCiSucceeded,
} = require('../.github/scripts/review-gate.cjs');

const head = 'a'.repeat(40);
const main = 'b'.repeat(40);

const jinxReview = {
  user: { login: 'jinx-reviewer' },
  submitted_at: '2026-09-27T12:00:00Z',
  state: 'COMMENTED',
  commit_id: head,
  body: 'Jinx verdict: No blockers\nReviewed head ' + head,
};
assert.equal(jinxApproved([jinxReview], 'jinx-reviewer', head), true);
assert.equal(jinxApproved([jinxReview], 'jinx-reviewer', 'c'.repeat(40)), false, 'stale Jinx SHA refuses');
assert.equal(jinxApproved([{ ...jinxReview, state: 'APPROVED' }], 'jinx-reviewer', head), false, 'wrong Jinx review state refuses');
assert.equal(jinxApproved([{ ...jinxReview, body: 'No blockers in the first pass; still investigating.' }], 'jinx-reviewer', head), false, 'ambiguous Jinx wording refuses');
assert.equal(jinxApproved([jinxReview, { ...jinxReview, submitted_at: '2026-09-27T13:00:00Z', body: 'Jinx verdict: changes needed' }], 'jinx-reviewer', head), false, 'latest Jinx review wins');

const claudeComment = {
  user: { login: 'claude[bot]', type: 'Bot' },
  created_at: '2026-09-27T12:00:00Z',
  body: `Reviewed the requested changes.\n\nPR head SHA reviewed: ${head}\nMain SHA reviewed against: ${main}\nClaude verdict: OK to merge\n\n---\n_Generated by Claude Code_`,
};
assert.equal(claudeApproved([claudeComment], head, main), true);
assert.equal(claudeApproved([claudeComment], 'c'.repeat(40), main), false, 'stale Claude head refuses');
assert.equal(claudeApproved([claudeComment], head, 'd'.repeat(40)), false, 'stale Claude base refuses');
assert.equal(claudeApproved([{ ...claudeComment, user: { login: 'repo-owner', type: 'User' } }], head, main), false, 'non-bot Claude signal refuses');
assert.equal(claudeApproved([{ ...claudeComment, body: claudeComment.body.replace('OK to merge', 'changes needed (1 important)') }], head, main), false, 'negative Claude verdict refuses');

assert.equal(isImportantFinding('Important: CI gate bypass.'), true);
assert.equal(isImportantFinding('**Important:** CI gate bypass.'), true);
assert.equal(isImportantFinding('- **Important:** CI gate bypass.'), true);
assert.equal(isImportantFinding('1. **Important:** CI gate bypass.'), true);
assert.equal(isImportantFinding('> - **Important:** CI gate bypass.'), true);
assert.equal(isImportantFinding('**1. Important:** CI gate bypass.'), true);
assert.equal(isImportantFinding('No blocking issues.'), false);
assert.equal(hasUnresolvedImportant([{ isResolved: false, comments: ['- **Important:** still open'] }]), true);
assert.equal(hasUnresolvedImportant([{ isResolved: true, comments: ['Important: addressed'] }]), false);

assert.equal(hasProtectedAutoMergeChange(['.github/workflows/ci.yml']), true);
assert.equal(hasProtectedAutoMergeChange(['tests/allowed_skips.json']), true);
assert.equal(hasProtectedAutoMergeChange(['tests/test_frozen_contract.mjs']), true);
assert.equal(hasProtectedAutoMergeChange(['tests/test_review_gate.mjs']), true);
assert.equal(hasProtectedAutoMergeChange(['.github/scripts/review-gate.cjs']), true);
assert.equal(hasProtectedAutoMergeChange(['tools/run-suites.mjs']), true);
assert.equal(hasProtectedAutoMergeChange(['docs/CLAUDE_REVIEW_ROUTINE.md']), false);

const ciRun = {
  event: 'pull_request',
  pull_requests: [{ number: 12, head: { sha: head } }],
  head_sha: head,
  created_at: '2026-09-27T12:00:00Z',
  conclusion: 'success',
};
assert.equal(latestCiSucceeded([ciRun], 12, head), true);
assert.equal(latestCiSucceeded([ciRun], 13, head), false, 'CI from another PR refuses');
assert.equal(latestCiSucceeded([{ ...ciRun, head_sha: 'c'.repeat(40) }], 12, head), false, 'CI from another head refuses');
assert.equal(latestCiSucceeded([{ ...ciRun, conclusion: 'failure' }], 12, head), false, 'failed latest CI refuses');

console.log('Review gate signal and refusal cases passed.');
