// The demo build is index.html plus the deviations below and nothing else. Each deviation is one
// replacement rule with an exact expected match count; tools/build-demo.mjs refuses to build if a
// target is missing or matches a different number of times. docs/DEMO_DEVIATIONS.md is generated
// from this list, so the document and the build cannot disagree. Ids come from the position in the
// list (D-1, D-2, ...) and each replacement carries its id as a DEMO marker where the syntax allows.
//
// Pilot seats: the named accounts tech, quality, mfgeng, operations and engineering keep the
// capabilities of their real role so a pilot can rehearse with them. Every other demo account
// (demo, master, safety, certification and any account a person creates) has full access.

export const PILOT_SEATS = Object.freeze(['tech', 'quality', 'mfgeng', 'operations', 'engineering']);
const FULL = "(typeof window!=='undefined'&&window.__demoFull&&window.__demoFull())";
const NEVER = id => `=== '__demo_never_matches__' /* DEMO ${id} */`;
const PRINT_MARK = '<div class="demo-print-mark" style="margin:0 0 8px;padding:6px 10px;border:2px solid #7a1f00;color:#7a1f00;font:700 14px/18px sans-serif;text-align:center;letter-spacing:.06em">DEMO, NOT FOR ACCEPTANCE</div>'
  // On screen the preview's fixed Print button sits at the top right; start the mark below it. Print is unchanged.
  + '<style>@media screen{.demo-print-mark{margin-top:56px!important}}</style>';

const LIST = [
  { area: 'Identity', title: 'Page title reads Flight System Demo',
    why: 'Anyone looking at a tab or a bookmark can tell the demo from the production build.',
    find: '<title>Flight System</title>', count: 1,
    replace: () => '<title>Flight System Demo</title>' },
  { area: 'Identity', title: 'Tab title reads Flight System Demo on every view',
    why: 'The title the app sets on each render keeps the word Demo.',
    find: 'document.title=`Flight System · ', count: 1,
    replace: (ctx, m, id) => `/* DEMO ${id} */document.title=\`Flight System Demo · ` },
  { area: 'Data', title: 'Sample workspace loaded on first open',
    why: 'The demo opens on a populated workspace (the curated set for demo.html, 150 work orders for the regression fixtures) instead of an empty one. The workspace is written in the head, before the app reads storage, so the first open needs no reload.',
    find: '<title>Flight System Demo</title>', count: 1,
    replace: (ctx, m, id) => `<title>Flight System Demo</title>\n<!-- DEMO ${id} --><script>window.__DEMO_SEED=${ctx.seed};(function(){try{if(!localStorage.getItem(${JSON.stringify(ctx.seedMark)})){localStorage.setItem('skyryse-mes-work-order-qa100-v1',JSON.stringify(window.__DEMO_SEED));localStorage.setItem(${JSON.stringify(ctx.seedMark)},new Date().toISOString());}}catch(e){}})();</script>` },
  { area: 'Accounts', title: 'Demo accounts preloaded; pilot seats named',
    why: 'Sign in without setting up accounts (password demo1234). The same script names the pilot seats that keep their real role and defines window.__demoFull() for every other account.',
    find: '<script>\nfunction skBoot(){', count: 1,
    replace: (ctx, m, id) => `<script>/* DEMO ${id}: demo accounts and the pilot seat list, loaded before the sign-in gate. */\nwindow.__DEMO_PILOT=${JSON.stringify(PILOT_SEATS)};\nwindow.__demoFull=function(){try{var u=sessionStorage.getItem('skyryse-mes-session-v1');return !!u&&window.__DEMO_PILOT.indexOf(u)<0;}catch(e){return false;}};\ntry{var A="skyryse-mes-auth-v1",cur=JSON.parse(localStorage.getItem(A)||"null");var demo=${ctx.accounts};\nif(!cur||!Array.isArray(cur.users)||!demo.users.every(function(d){return cur.users.some(function(u){return u.username===d.username;});})){var have=(cur&&Array.isArray(cur.users)?cur.users:[]);localStorage.setItem(A,JSON.stringify({users:have.concat(demo.users.filter(function(d){return !have.some(function(u){return u.username===d.username;});}))}));}}catch(e){}\n</script>\n<script>\nfunction skBoot(){` },
  { area: 'Data', title: 'Separate workspace storage key',
    why: 'The demo never reads or overwrites a production workspace kept in the same browser. The production key stays frozen.',
    find: "const KEY='skyryse-mes-work-order-v1';", count: 1,
    replace: (ctx, m, id) => `const KEY='skyryse-mes-work-order-qa100-v1'; /* DEMO ${id} */` },
  { area: 'Roles', title: 'Full capabilities for accounts that are not pilot seats',
    why: 'A solo walk-through can run every workflow. Pilot seats keep their real role.',
    find: 'function capsOf(u){', count: 1,
    replace: (ctx, m, id) => `function capsOf(u){if(u&&window.__DEMO_PILOT.indexOf(u.username)<0)return ALL_CAPS;/* DEMO ${id} */` },
  { area: 'Roles', title: 'Access management for accounts that are not pilot seats',
    why: 'Anyone walking the demo can add accounts and change roles. Pilot seats keep their real role.',
    find: "function canManageAccess(u){var r=roleOf(u);return r==='admin'||r==='qm'||r==='qs';}", count: 1,
    replace: (ctx, m, id) => `function canManageAccess(u){var r=roleOf(u);if(u&&window.__DEMO_PILOT.indexOf(u.username)<0)return true;/* DEMO ${id} */return r==='admin'||r==='qm'||r==='qs';}` },
  { area: 'Roles', title: 'QA Manager only settings open to accounts that are not pilot seats',
    why: 'The SDS book, the stamp register, stamp changes, the stamp CSV import, training requirements and training records can be exercised by the full-access accounts.',
    find: /if \(accountRole\(\) !== null && !\['qm', ?'admin'\]\.includes\(accountRole\(\)\)\)/g, count: 4,
    replace: (ctx, m, id) => m.replace('if (', `if (!${FULL} && /* DEMO ${id} */ `) },
  { area: 'Roles', title: 'Use for Dev approval open to accounts that are not pilot seats',
    why: 'Use for Dev needs a QA Manager in production; the full-access demo accounts can approve it.',
    find: /Use for Dev' && !\['qm', 'admin'\]\.includes\(accountRole\(\)\)/g, count: 2,
    replace: (ctx, m, id) => m.replace("&& !['qm'", `&& !${FULL} /* DEMO ${id} */ && !['qm'`) },
  { area: 'Roles', title: 'Every MRB seat for accounts that are not pilot seats',
    why: 'One person can walk a board to its decision. Pilot seats vote only the seats their role holds.',
    find: 'const seatsForRole = role => ALL_SEATS.filter(', count: 1,
    replace: (ctx, m, id) => `const seatsForRole = role => ${FULL} /* DEMO ${id} */ ? [...ALL_SEATS] : ALL_SEATS.filter(` },
  { area: 'Limits', title: 'Work order limit 250',
    why: 'Holds the 150-order regression dataset with room to create more.',
    find: 'const MAX_ORDERS = 100;', count: 1,
    replace: (ctx, m, id) => `const MAX_ORDERS = 250; /* DEMO ${id} */` },
  { area: 'Limits', title: 'Work order limit message says 250',
    why: 'The refusal names the demo limit.',
    find: /A workspace holds up to 100 work orders\./g, count: 4,
    replace: () => 'A workspace holds up to 250 work orders.' },
  { area: 'Stamps', title: 'Every account holds a demo stamp',
    why: 'Nobody is stopped mid-scenario by the Stamp Control Log. The holder is the account\'s own register stamp when it has one, otherwise a stamp numbered DEMO; it is marked demo so the next three deviations can recognise it.',
    find: '  function stampCheck(profile, at = new Date().toISOString()) {\n', count: 1,
    replace: (ctx, m, id) => `  function stampCheck(profile, at = new Date().toISOString()) {\n    /* DEMO ${id} */ { const h = stampHolderFor(profile); return { ok: true, holder: { ...(h || { number: 'DEMO', name: (profile && profile.name) || 'Demo user', buyoffType: 'Technician', type: 'Demo', department: 'Demo' }), demo: true } }; }\n` },
  { area: 'Stamps', title: 'A demo stamp buys off any operation type',
    why: 'The buy-off type check does not apply to a demo stamp.',
    find: '    return stamp.ok && stamp.holder.buyoffType !== type ? fail(', count: 1,
    replace: (ctx, m, id) => `    return stamp.ok && !stamp.holder.demo /* DEMO ${id} */ && stamp.holder.buyoffType !== type ? fail(` },
  { area: 'Stamps', title: 'Stamp number, training and PIN not checked at buy-off for a demo stamp',
    why: 'Any number typed into the stamp field completes the buy-off, and no training record or PIN is needed.',
    find: '    if (!stamp.override) {\n      if (String(execution.stampNumber', count: 1,
    replace: (ctx, m, id) => `    if (!stamp.override && !stamp.holder.demo /* DEMO ${id} */) {\n      if (String(execution.stampNumber` },
  { area: 'Stamps', title: 'Inspection steps checked off with a demo stamp',
    why: 'The inspection-point step check accepts a demo stamp of any type.',
    find: 'if (!sc.ok || sc.holder.buyoffType !== operation.buyoffType)', count: 1,
    replace: (ctx, m, id) => `if (!sc.ok || (!sc.holder.demo /* DEMO ${id} */ && sc.holder.buyoffType !== operation.buyoffType))` },
  { area: 'Stamps', title: 'PIN step-up lifted for FAIR and 8130-9 signatures',
    why: 'The inspector signing a FAIR or an 8130-9 is not asked for a stamp PIN. The PIN check itself is unchanged.',
    find: '    { const s2 = identityStepUp(holder, execution); if (!s2.ok) return fail(s2.message); }', count: 1,
    replace: (ctx, m, id) => `    /* DEMO ${id}: PIN step-up lifted for FAIR and 8130-9 signatures */` },
  { area: 'Stamps', title: 'Stamp PIN fields optional at buy-off',
    why: 'The buy-off panel and the stamp prompt do not require a PIN, since a demo stamp is not asked for one.',
    find: /<input id="(?:step-)?stamp-pin" name="pin" type="password" inputmode="numeric" class="mono" autocomplete="off" maxlength="8" required/g, count: 2,
    replace: (ctx, m, id) => m.replace(/ required$/, ` data-demo="DEMO ${id}"`) },
  { area: 'Stamps', title: 'Buy-off form does not pre-check the stamp in the browser',
    why: 'The engine is the only check (and the stamp deviations above relax it), so the form never blocks on a demo stamp.',
    find: 'if(!MES.masterAccess()&&form.dataset.supportReason===undefined){const stampResult', count: 1,
    replace: (ctx, m, id) => `if(false/* DEMO ${id} */&&!MES.masterAccess()&&form.dataset.supportReason===undefined){const stampResult` },
  { area: 'Separation of duties', title: 'Engine separation-of-duties comparisons never match',
    why: 'One person can author and approve, request and decide, prepare and sign, so a flow can be walked alone. Production enforces every one of these.',
    find: /=== actor\(state\)\.credentialId/g, count: 14,
    replace: (ctx, m, id) => NEVER(id) },
  { area: 'Separation of duties', title: 'Closure, software push and change approval self-checks never match',
    why: 'Same as the rule above for the checks that compare against the current actor held in a local variable.',
    find: /=== who\.credentialId/g, count: 3,
    replace: (ctx, m, id) => NEVER(id) },
  { area: 'Separation of duties', title: 'Two approvals from one discipline allowed',
    why: 'A pedigree change can be approved twice from the same discipline.',
    find: 'change.approvals.some(a => a.discipline === discipline)', count: 1,
    replace: (ctx, m, id) => `change.approvals.some(a => a.discipline ${NEVER(id)})` },
  { area: 'Separation of duties', title: 'Flight Maneuver same-person checks never match',
    why: 'Root cause and verification, and one person one MRB seat, are lifted in the demo.',
    find: 'const sameActor = (a, b) =>', count: 1,
    replace: (ctx, m, id) => `const sameActor = (a, b) => false && /* DEMO ${id} */` },
  { area: 'Separation of duties', title: 'An inspector may inspect work they performed',
    why: 'One person can build an operation and inspect it, so a work order can be walked alone. Production refuses this to every role, Master Access and Support Access included.',
    find: '  function ownWorkRefusal(state, order, operation) {\n    if (!isInspectionOp(operation)) return null;', count: 1,
    replace: (ctx, m, id) => `  function ownWorkRefusal(state, order, operation) {\n    return null; /* DEMO ${id} */` },
  { area: 'Separation of duties', title: 'Screens offer self-approval',
    why: 'The sequence release, closure withdrawal and pedigree approval controls render for the person who made the change.',
    find: /=== ?skActorId\(\)/g, count: 5,
    replace: (ctx, m, id) => NEVER(id) },
  { area: 'Separation of duties', title: 'NC quality review shows the approval form to the disposition author',
    why: 'The person who recorded the ME disposition can approve it and close the ticket, matching the engine relaxation above.',
    find: 'if(t.dispo?.credentialId!==skActorId())return ticketQualityReviewForm(o,t);', count: 1,
    replace: (ctx, m, id) => `if(true/* DEMO ${id} */||t.dispo?.credentialId!==skActorId())return ticketQualityReviewForm(o,t);` },
  { area: 'Separation of duties', title: 'Any valid credential counts as a QA credential for release records',
    why: 'Release approvals recorded by any demo account validate.',
    find: "const isQAProfile = profile => profileValid(profile) && ['Quality Manager', 'Quality Engineer', 'QA Reviewer', 'System Administrator'].includes(profile.role);", count: 1,
    replace: (ctx, m, id) => `const isQAProfile = profile => profileValid(profile); /* DEMO ${id} */` },
  { area: 'Marking', title: 'DEMO, NOT FOR ACCEPTANCE on every print and download',
    why: 'A printed or downloaded demo record cannot be mistaken for a production record.',
    find: 'function markDocument(html){', count: 1,
    replace: (ctx, m, id) => `function markDocument(html){/* DEMO ${id} */{const mark=${JSON.stringify(PRINT_MARK)};html=/<body[^>]*>/i.test(html)?html.replace(/<body[^>]*>/i,b=>b+mark):mark+html;}` },
  { area: 'Marking', title: 'Demo overlay appended',
    why: 'Loads the sample workspace once, issues stamps to the pilot accounts, seeds a PFMEA example, activates the generic role stamps and shows DEMO, NOT FOR ACCEPTANCE on every page, the sign-in screen included, with a note there giving the demo accounts and their password. Source: tools/demo/overlay.js.',
    find: /<\/body><\/html>\n?$/, count: 1,
    replace: (ctx, m, id) => `<script>\n${ctx.overlay.replace('DEMO OVERLAY', `DEMO ${id}`)}</script>\n</body></html>\n` },
  // Appended after the overlay so the ids above stay stable (ids come from list position).
  { area: 'Separation of duties', title: 'The author of a master WI may release it',
    why: 'One person can write a WI and release it, so a demo can be walked alone. Production refuses this to every role, Master Access and Support Access included.',
    find: '  const wiAuthorRefusal = (state, wi) => wiAuthors(wi).has(actor(state).credentialId) ?', count: 1,
    replace: (ctx, m, id) => `  const wiAuthorRefusal = (state, wi) => false /* DEMO ${id} */ && wiAuthors(wi).has(actor(state).credentialId) ?` },
  { area: 'Separation of duties', title: 'The author of a master WI may record its peer review',
    why: 'One person can write a WI and peer-review it, so a demo can be walked alone. Production refuses this to every role, Master Access and Support Access included.',
    find: '  const wiPeerReviewRefusal = (state, wi) => wiAuthors(wi).has(actor(state).credentialId) ?', count: 1,
    replace: (ctx, m, id) => `  const wiPeerReviewRefusal = (state, wi) => false /* DEMO ${id} */ && wiAuthors(wi).has(actor(state).credentialId) ?` },
  { area: 'Roles', title: 'Authorities follow the role without a QA Manager grant',
    why: 'Conformity work and AQI signatures work for eligible demo accounts without a named grant or current training record, so scenarios run without setup. Production requires a named grant and a current training record. Inspection requires an assigned active Quality stamp in production, while MRB seats follow role capabilities in both builds.',
    find: ' function grantActive(u,cap){', count: 1,
    replace: (ctx, m, id) => ` function grantActive(u,cap){return true;/* DEMO ${id} */` },
  { area: 'Separation of duties', title: 'The person who verified a FAIR may sign box 22',
    why: 'One person can verify a FAIR and review it in box 22, so an FAI order can be walked alone. Production refuses this to every role, Master Access and Support Access included. The QA approval still waits for box 22.',
    find: '    if (fair.verified && fair.verified.by && by.credentialId === fair.verified.by.credentialId) return fail(', count: 1,
    replace: (ctx, m, id) => `    if (false /* DEMO ${id} */ && fair.verified && fair.verified.by && by.credentialId === fair.verified.by.credentialId) return fail(` },
  { area: 'Data', title: 'Demo-only Flight Maneuver examples',
    why: 'Sample corrective actions, SPRs and NCs load only in the explicitly marked demo build. Production opens a valid empty register and never replaces damaged records with examples.',
    find: 'window.FlightManeuver.ensure(state);const FM=window.FlightManeuver;', count: 1,
    replace: (ctx, m, id) => `const hadManeuver=Object.hasOwn(state,'maneuver');window.FlightManeuver.ensure(state);if(!hadManeuver)window.FlightManeuver.seedDemoRecords(state);/* DEMO ${id} */const FM=window.FlightManeuver;` },
  { area: 'Data', title: 'Seed operational dates follow the first-load day',
    why: 'The sample workspace is captured on a fixed day. When a browser first loads it, due and start dates of open work, the MDL date of a package with no 8130-9 yet, planned need dates, open request and CAR due dates, and stamp expiries move forward by the days since capture, so the sample data does not age. A CAR, whose history quotes its due dates, and an order whose MDL date moves get a Demo build history entry naming the old and new dates. Signed and recorded dates (buy-offs, manifests, signatures, existing history, closed orders) never move. The calibrated tool snapshot moves by the same days (D-37). Source: tools/demo/seed-dates.mjs.',
    find: /JSON\.stringify\(window\.__DEMO_SEED\)/g, count: 2,
    replace: (ctx, m, id) => `JSON.stringify((${ctx.rebase})(window.__DEMO_SEED)/* DEMO ${id} */)` },
  { area: 'Roles', title: 'Any named signer role may sign a calibration entry',
    why: 'The full-access demo accounts (D-6) hold configure-qms whatever their role, so their calibration entries record and validate. Production accepts only the Quality Manager and System Administrator signer roles. Pilot seats are still refused by the configure-qms gate.',
    find: 'const calibrationSignerRole = role => CALIBRATION_SIGNER_ROLES.includes(role);', count: 1,
    replace: (ctx, m, id) => `const calibrationSignerRole = role => typeof role === 'string' && !!role.trim(); /* DEMO ${id} */` },
  { area: 'Data', title: 'Calibrated tool snapshot follows the first-load day',
    why: 'The demo seeds carry no calibration log, so demo tool checks read the Calibrated Tool Log snapshot shipped in the production file, and every snapshot tool would expire within a year of capture and block every operation that needs tooling. The snapshot label and every snapshot tool expiry move forward by the same days as the seed dates (D-35), counted from the day the browser first loaded the demo, so the spacing between tools is kept and tools still come due as days pass. Signed buy-offs keep the tool expiries they recorded. Production keeps the shipped snapshot. Source: tools/demo/seed-dates.mjs.',
    find: /const CAL_SNAPSHOT = '[^']*';\n  const CAL_TOOLS = Object\.freeze\(\[\[.*?\]\]\.map\(\(\[tag, description, serial, expires, status, location\]\) => Object\.freeze\(\{ tag, description, serial, expires, status, location \}\)\)\);/g, count: 1,
    replace: (ctx, m, id) => {
      const firstLoad = `(function(){try{return localStorage.getItem(${JSON.stringify(ctx.seedMark)})||undefined;}catch(e){return undefined;}})()`;
      const snapshot = /^const CAL_SNAPSHOT = ('[^']*');/.exec(m)[1];
      return m
        .replace(/^const CAL_SNAPSHOT = '[^']*';/, () => `/* DEMO ${id} */ const DEMO_CAL = (${ctx.calRebase})(${snapshot}, (typeof window !== 'undefined' && window.__DEMO_SEED) || null, ${firstLoad});\n  const CAL_SNAPSHOT = DEMO_CAL.snapshot;`)
        .replace(/Object\.freeze\(\{ tag, description, serial, expires, status, location \}\)\)\);$/, () => 'Object.freeze({ tag, description, serial, expires: DEMO_CAL.expires(expires), status, location })));');
    } },
  { area: 'Data', title: 'Never the production mirror',
    why: 'Whatever mirror address and token the production file sets (the fallback object or a mirror setting a page or proxy makes before load, window.SK_MIRROR), the demo replaces the whole setting with an empty address, so the mirror stays off: the demo never sends records made under its relaxed gates to the production retention database and never holds the production mirror token. Only tools/run-suites.mjs --mirror gives the demo its own throwaway server, through __FS_SUITE_DEMO_MIRROR__.',
    find: /window\.SK_MIRROR = [^;{]*\{[\s\S]*?\};/g, count: 1,
    replace: (ctx, m, id) => `/* DEMO ${id} */ window.SK_MIRROR = window.__FS_SUITE_DEMO_MIRROR__ || { url: '', token: '', batchSize: 50 };` },
  { area: 'Data', title: 'Separate mirror queue keys',
    why: 'Records, confirmations, acknowledgements and pending recoveries the demo keeps for a mirror are under skyryse-mes-demo-sync-*, so a production page in the same browser never sends a demo record to its mirror and never takes a demo acknowledgement as its own.',
    find: /(['"])skyryse-mes-sync-(?:queue|sent|client|ack|recovery)-v1\1/g, count: 5,
    replace: (ctx, m, id) => `${m.replace('skyryse-mes-sync-', 'skyryse-mes-demo-sync-')}/* DEMO ${id} */` },
];

export const DEVIATIONS = LIST.map((d, i) => Object.freeze({ ...d, id: `D-${i + 1}` }));
