// The demo build is index.html plus the deviations below and nothing else. Each deviation is one
// replacement rule with an exact expected match count; tools/build-demo.mjs refuses to build if a
// target is missing or matches a different number of times. docs/DEMO_DEVIATIONS.md is generated
// from this list, so the document and the build cannot disagree. Ids come from the position in the
// list (D-1, D-2, ...) and each replacement carries its id as a DEMO marker where the syntax allows.
//
// Pilot seats: the named accounts tech, quality, mfgeng, operations and engineering keep the
// capabilities of their real role so a pilot can rehearse with them. Every other demo account
// (demo, master, safety, certification and any account a person creates) has full access.

import * as SAMPLE from './sample-data.mjs';

// The production build ships each sample declaration below empty (issue #247). A deviation finds the empty form
// and puts back the sample source from sample-data.mjs, so only the demo carries sample data.
const EMPTY = Object.freeze({
  NETSUITE_STOCK: '  const NETSUITE_STOCK = Object.freeze({});\n',
  DEFAULT_KIT: '  function materials(ready = false) {\n    return [];\n  }\n',
  DEMO_PARTS: '  const DEMO_PARTS = Object.freeze([]);\n',
  DEMO_FINISHED_STOCK: '  const DEMO_FINISHED_STOCK = Object.freeze({});\n',
  DEMO_MBOM: '  const DEMO_MBOM = Object.freeze({});\n',
  DEMO_COMPONENT_LOTS: '  const DEMO_COMPONENT_LOTS = Object.freeze([]);\n',
  DEMO_LEAD_ACTUALS: '  const DEMO_LEAD_ACTUALS = Object.freeze([]);\n',
  STAMP_HOLDERS: '  const STAMP_HOLDERS = Object.freeze([]);\n',
  seedMasterWIs: '  function seedMasterWIs() {\n    return [];\n  }\n',
  STD_REWORK_SEED: '  const STD_REWORK_SEED = [];\n',
  PLANNED_ORDER_SEED: '    const seed = [];\n',
});
const escapeRe = text => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const emptyOf = names => new RegExp(names.map(n => escapeRe(EMPTY[n])).join('|'), 'g');
const sampleFor = (m, id) => `${m.match(/^ */)[0]}/* DEMO ${id}: sample data */\n${SAMPLE[Object.keys(EMPTY).find(n => EMPTY[n] === m)]}`;
const EMPTY_CAL = "const CAL_SNAPSHOT = '';\n  const CAL_TOOLS = Object.freeze([].map(([tag, description, serial, expires, status, location]) => Object.freeze({ tag, description, serial, expires, status, location })));";

export const PILOT_SEATS = Object.freeze(['tech', 'quality', 'mfgeng', 'operations', 'engineering']);
const FULL = "(typeof window!=='undefined'&&window.__demoFull&&window.__demoFull())";
const NEVER = id => `=== '__demo_never_matches__' /* DEMO ${id} */`;
const PRINT_MARK = '<div class="demo-print-mark" style="margin:0 0 8px;padding:6px 10px;border:2px solid #7a1f00;color:#7a1f00;font:700 14px/18px sans-serif;text-align:center;letter-spacing:.06em">DEMO, NOT FOR ACCEPTANCE</div>'
  // On screen the preview's fixed Print button sits at the top right; start the mark below it. Print is unchanged.
  + '<style>@media screen{.demo-print-mark{margin-top:56px!important}}</style>';

const LIST = [
  { area: 'Identity', title: 'Page title reads Flight System Demo',
    why: 'Anyone looking at a tab or a bookmark can tell the demo from the production build.',
    find: '<title>Flight System</title>', count: 1,
    replace: () => '<title>Flight System Demo</title>' },
  { area: 'Identity', title: 'Tab title reads Flight System Demo on every view',
    why: 'The title the app sets on each render keeps the word Demo.',
    find: 'document.title=`Flight System · ', count: 1,
    replace: (ctx, m, id) => `/* DEMO ${id} */document.title=\`Flight System Demo · ` },
  { area: 'Data', title: 'Sample workspace loaded on first open',
    why: 'The demo opens on a populated workspace (the curated set for demo.html, 150 work orders for the regression fixtures) instead of an empty one. The workspace is written in the head, before the app reads storage, so the first open needs no reload.',
    find: '<title>Flight System Demo</title>', count: 1,
    replace: (ctx, m, id) => `<title>Flight System Demo</title>\n<!-- DEMO ${id} --><script>window.__DEMO_SEED=${ctx.seed};(function(){try{if(!localStorage.getItem(${JSON.stringify(ctx.seedMark)})){localStorage.setItem('skyryse-mes-work-order-qa100-v1',JSON.stringify(window.__DEMO_SEED));localStorage.setItem(${JSON.stringify(ctx.seedMark)},new Date().toISOString());}}catch(e){}})();</script>` },
  { area: 'Accounts', title: 'Demo accounts preloaded; pilot seats named',
    why: 'Sign in without setting up accounts (password demo1234). The same script names the pilot seats that keep their real role and defines window.__demoFull() for every other account.',
    find: '<script>\nfunction skBoot(){', count: 1,
    replace: (ctx, m, id) => `<script>/* DEMO ${id}: demo accounts and the pilot seat list, loaded before the sign-in gate. */\nwindow.__DEMO_PILOT=${JSON.stringify(PILOT_SEATS)};\nwindow.__demoFull=function(){try{var u=sessionStorage.getItem('skyryse-mes-session-v1');return !!u&&window.__DEMO_PILOT.indexOf(u)<0;}catch(e){return false;}};\ntry{var A="skyryse-mes-auth-v1",cur=JSON.parse(localStorage.getItem(A)||"null");var demo=${ctx.accounts};\nif(!cur||!Array.isArray(cur.users)||!demo.users.every(function(d){return cur.users.some(function(u){return u.username===d.username;});})){var have=(cur&&Array.isArray(cur.users)?cur.users:[]);localStorage.setItem(A,JSON.stringify({users:have.concat(demo.users.filter(function(d){return !have.some(function(u){return u.username===d.username;});}))}));}}catch(e){}\n</script>\n<script>\nfunction skBoot(){` },
  { area: 'Data', title: 'Separate workspace storage key',
    why: 'The demo never reads or overwrites a production workspace kept in the same browser. The production key stays frozen.',
    find: "const KEY='skyryse-mes-work-order-v1';", count: 1,
    replace: (ctx, m, id) => `const KEY='skyryse-mes-work-order-qa100-v1'; /* DEMO ${id} */` },
  { area: 'Roles', title: 'Full capabilities for accounts that are not pilot seats',
    why: 'A solo walk-through can run every workflow. Pilot seats keep their real role.',
    find: 'function capsOf(u){', count: 1,
    replace: (ctx, m, id) => `function capsOf(u){if(u&&window.__DEMO_PILOT.indexOf(u.username)<0)return ALL_CAPS;/* DEMO ${id} */` },
  { area: 'Roles', title: 'Access management for accounts that are not pilot seats',
    why: 'Anyone walking the demo can add accounts and change roles. Pilot seats keep their real role.',
    find: "function canManageAccess(u){var r=roleOf(u);return r==='admin'||r==='qm'||r==='qs';}", count: 1,
    replace: (ctx, m, id) => `function canManageAccess(u){var r=roleOf(u);if(u&&window.__DEMO_PILOT.indexOf(u.username)<0)return true;/* DEMO ${id} */return r==='admin'||r==='qm'||r==='qs';}` },
  { area: 'Roles', title: 'QA Manager only settings open to accounts that are not pilot seats',
    why: 'The SDS book, the stamp register, stamp changes, the stamp CSV import, training requirements and training records can be exercised by the full-access accounts.',
    find: /if \(accountRole\(\) !== null && !\['qm', ?'admin'\]\.includes\(accountRole\(\)\)\)/g, count: 4,
    replace: (ctx, m, id) => m.replace('if (', `if (!${FULL} && /* DEMO ${id} */ `) },
  { area: 'Roles', title: 'Use for Dev approval open to accounts that are not pilot seats',
    why: 'Use for Dev needs a QA Manager in production; the full-access demo accounts can approve it.',
    find: /Use for Dev' && !\['qm', 'admin'\]\.includes\(accountRole\(\)\)/g, count: 2,
    replace: (ctx, m, id) => m.replace("&& !['qm'", `&& !${FULL} /* DEMO ${id} */ && !['qm'`) },
  { area: 'Roles', title: 'Every MRB seat for accounts that are not pilot seats',
    why: 'One person can walk a board to its decision. Pilot seats vote only the seats their role holds.',
    find: 'const seatsForRole = role => ALL_SEATS.filter(', count: 1,
    replace: (ctx, m, id) => `const seatsForRole = role => ${FULL} /* DEMO ${id} */ ? [...ALL_SEATS] : ALL_SEATS.filter(` },
  { area: 'Limits', title: 'Work order limit 250',
    why: 'Holds the 150-order regression dataset with room to create more.',
    find: 'const MAX_ORDERS = 100;', count: 1,
    replace: (ctx, m, id) => `const MAX_ORDERS = 250; /* DEMO ${id} */` },
  { area: 'Limits', title: 'Work order limit message says 250',
    why: 'The refusal names the demo limit.',
    find: /A workspace holds up to 100 work orders\./g, count: 4,
    replace: () => 'A workspace holds up to 250 work orders.' },
  { area: 'Stamps', title: 'Every account holds a demo stamp',
    why: 'Nobody is stopped mid-scenario by the Stamp Control Log. The holder is the account\'s own register stamp when it has one, otherwise a stamp numbered DEMO; it is marked demo so the next three deviations can recognise it.',
    find: '  function stampCheck(profile, at = new Date().toISOString()) {\n', count: 1,
    replace: (ctx, m, id) => `  function stampCheck(profile, at = new Date().toISOString()) {\n    /* DEMO ${id} */ { const h = stampHolderFor(profile); return { ok: true, holder: { ...(h || { number: 'DEMO', name: (profile && profile.name) || 'Demo user', buyoffType: 'Technician', type: 'Demo', department: 'Demo' }), demo: true } }; }\n` },
  { area: 'Stamps', title: 'A demo stamp buys off any operation type',
    why: 'The buy-off type check does not apply to a demo stamp.',
    find: '    return stamp.ok && stamp.holder.buyoffType !== type ? fail(', count: 1,
    replace: (ctx, m, id) => `    return stamp.ok && !stamp.holder.demo /* DEMO ${id} */ && stamp.holder.buyoffType !== type ? fail(` },
  { area: 'Stamps', title: 'Stamp number, training and PIN not checked at buy-off for a demo stamp',
    why: 'Any number typed into the stamp field completes the buy-off, and no training record or PIN is needed.',
    find: '    if (!stamp.override) {\n      if (String(execution.stampNumber', count: 1,
    replace: (ctx, m, id) => `    if (!stamp.override && !stamp.holder.demo /* DEMO ${id} */) {\n      if (String(execution.stampNumber` },
  { area: 'Stamps', title: 'Inspection steps checked off with a demo stamp',
    why: 'The inspection-point step check accepts a demo stamp of any type.',
    find: 'if (!sc.ok || sc.holder.buyoffType !== operation.buyoffType)', count: 1,
    replace: (ctx, m, id) => `if (!sc.ok || (!sc.holder.demo /* DEMO ${id} */ && sc.holder.buyoffType !== operation.buyoffType))` },
  { area: 'Stamps', title: 'PIN step-up lifted for FAIR and 8130-9 signatures',
    why: 'The inspector signing a FAIR or an 8130-9 is not asked for a stamp PIN. The PIN check itself is unchanged.',
    find: '    { const s2 = identityStepUp(holder, execution); if (!s2.ok) return fail(s2.message); }', count: 1,
    replace: (ctx, m, id) => `    /* DEMO ${id}: PIN step-up lifted for FAIR and 8130-9 signatures */` },
  { area: 'Stamps', title: 'Stamp PIN fields optional at buy-off',
    why: 'The buy-off panel and the stamp prompt do not require a PIN, since a demo stamp is not asked for one.',
    find: /<input id="(?:step-)?stamp-pin" name="pin" type="password" inputmode="numeric" class="mono" autocomplete="off" maxlength="8" required/g, count: 2,
    replace: (ctx, m, id) => m.replace(/ required$/, ` data-demo="DEMO ${id}"`) },
  { area: 'Stamps', title: 'Buy-off form does not pre-check the stamp in the browser',
    why: 'The engine is the only check (and the stamp deviations above relax it), so the form never blocks on a demo stamp.',
    find: 'if(!MES.masterAccess()&&form.dataset.supportReason===undefined){const stampResult', count: 1,
    replace: (ctx, m, id) => `if(false/* DEMO ${id} */&&!MES.masterAccess()&&form.dataset.supportReason===undefined){const stampResult` },
  { area: 'Separation of duties', title: 'Engine separation-of-duties comparisons never match',
    why: 'One person can author and approve, request and decide, prepare and sign, so a flow can be walked alone. Production enforces every one of these.',
    find: /=== actor\(state\)\.credentialId/g, count: 14,
    replace: (ctx, m, id) => NEVER(id) },
  { area: 'Separation of duties', title: 'Closure, software push and change approval self-checks never match',
    why: 'Same as the rule above for the checks that compare against the current actor held in a local variable.',
    find: /=== who\.credentialId/g, count: 3,
    replace: (ctx, m, id) => NEVER(id) },
  { area: 'Separation of duties', title: 'Two approvals from one discipline allowed',
    why: 'A pedigree change can be approved twice from the same discipline.',
    find: 'change.approvals.some(a => a.discipline === discipline)', count: 1,
    replace: (ctx, m, id) => `change.approvals.some(a => a.discipline ${NEVER(id)})` },
  { area: 'Separation of duties', title: 'Flight Maneuver same-person checks never match',
    why: 'Root cause and verification, and one person one MRB seat, are lifted in the demo.',
    find: 'const sameActor = (a, b) =>', count: 1,
    replace: (ctx, m, id) => `const sameActor = (a, b) => false && /* DEMO ${id} */` },
  { area: 'Separation of duties', title: 'An inspector may inspect work they performed',
    why: 'One person can build an operation and inspect it, so a work order can be walked alone. Production refuses this to every role, Master Access and Support Access included.',
    find: '  function ownWorkRefusal(state, order, operation) {\n    if (!isInspectionOp(operation)) return null;', count: 1,
    replace: (ctx, m, id) => `  function ownWorkRefusal(state, order, operation) {\n    return null; /* DEMO ${id} */` },
  { area: 'Separation of duties', title: 'Screens offer self-approval',
    why: 'The sequence release, closure withdrawal and pedigree approval controls render for the person who made the change.',
    find: /=== ?skActorId\(\)/g, count: 5,
    replace: (ctx, m, id) => NEVER(id) },
  { area: 'Separation of duties', title: 'NC quality review shows the approval form to the disposition author',
    why: 'The person who recorded the ME disposition can approve it and close the ticket, matching the engine relaxation above.',
    find: 'if(t.dispo?.credentialId!==skActorId())return ticketQualityReviewForm(o,t);', count: 1,
    replace: (ctx, m, id) => `if(true/* DEMO ${id} */||t.dispo?.credentialId!==skActorId())return ticketQualityReviewForm(o,t);` },
  { area: 'Separation of duties', title: 'Any valid credential counts as a QA credential for release records',
    why: 'Release approvals recorded by any demo account validate.',
    find: "const isQAProfile = profile => profileValid(profile) && ['Quality Manager', 'Quality Engineer', 'QA Reviewer', 'System Administrator'].includes(profile.role);", count: 1,
    replace: (ctx, m, id) => `const isQAProfile = profile => profileValid(profile); /* DEMO ${id} */` },
  { area: 'Marking', title: 'DEMO, NOT FOR ACCEPTANCE on every print and download',
    why: 'A printed or downloaded demo record cannot be mistaken for a production record.',
    find: 'function markDocument(html){', count: 1,
    replace: (ctx, m, id) => `function markDocument(html){/* DEMO ${id} */{const mark=${JSON.stringify(PRINT_MARK)};html=/<body[^>]*>/i.test(html)?html.replace(/<body[^>]*>/i,b=>b+mark):mark+html;}` },
  { area: 'Marking', title: 'Demo overlay appended',
    why: 'Loads the sample workspace once, issues stamps to the pilot accounts, seeds a PFMEA example, activates the generic role stamps and shows DEMO, NOT FOR ACCEPTANCE on every page, the sign-in screen included, with a note there giving the demo accounts and their password. Source: tools/demo/overlay.js.',
    find: /<\/body><\/html>\n?$/, count: 1,
    replace: (ctx, m, id) => `<script>\n${ctx.overlay.replace('DEMO OVERLAY', `DEMO ${id}`)}</script>\n</body></html>\n` },
  // Appended after the overlay so the ids above stay stable (ids come from list position).
  { area: 'Separation of duties', title: 'The author of a master WI may release it',
    why: 'One person can write a WI and release it, so a demo can be walked alone. Production refuses this to every role, Master Access and Support Access included.',
    find: '  const wiAuthorRefusal = (state, wi) => wiAuthors(wi).has(actor(state).credentialId) ?', count: 1,
    replace: (ctx, m, id) => `  const wiAuthorRefusal = (state, wi) => false /* DEMO ${id} */ && wiAuthors(wi).has(actor(state).credentialId) ?` },
  { area: 'Separation of duties', title: 'The author of a master WI may record its peer review',
    why: 'One person can write a WI and peer-review it, so a demo can be walked alone. Production refuses this to every role, Master Access and Support Access included.',
    find: '  const wiPeerReviewRefusal = (state, wi) => wiAuthors(wi).has(actor(state).credentialId) ?', count: 1,
    replace: (ctx, m, id) => `  const wiPeerReviewRefusal = (state, wi) => false /* DEMO ${id} */ && wiAuthors(wi).has(actor(state).credentialId) ?` },
  { area: 'Roles', title: 'Authorities follow the role without a QA Manager grant',
    why: 'Conformity work and AQI signatures work for eligible demo accounts without a named grant or current training record, so scenarios run without setup. Production requires a named grant and a current training record. Inspection requires an assigned active Quality stamp in production, while MRB seats follow role capabilities in both builds.',
    find: ' function grantActive(u,cap){', count: 1,
    replace: (ctx, m, id) => ` function grantActive(u,cap){return true;/* DEMO ${id} */` },
  { area: 'Separation of duties', title: 'The person who verified a FAIR may sign box 22',
    why: 'One person can verify a FAIR and review it in box 22, so an FAI order can be walked alone. Production refuses this to every role, Master Access and Support Access included. The QA approval still waits for box 22.',
    find: '    if (fair.verified && fair.verified.by && by.credentialId === fair.verified.by.credentialId) return fail(', count: 1,
    replace: (ctx, m, id) => `    if (false /* DEMO ${id} */ && fair.verified && fair.verified.by && by.credentialId === fair.verified.by.credentialId) return fail(` },
  { area: 'Data', title: 'Demo-only Flight Maneuver examples',
    why: 'Sample corrective actions, SPRs and NCs load only in the explicitly marked demo build. Production opens a valid empty register and never replaces damaged records with examples.',
    find: 'window.FlightManeuver.ensure(state);const FM=window.FlightManeuver;', count: 1,
    replace: (ctx, m, id) => `const hadManeuver=Object.hasOwn(state,'maneuver');window.FlightManeuver.ensure(state);if(!hadManeuver)window.FlightManeuver.seedDemoRecords(state);/* DEMO ${id} */const FM=window.FlightManeuver;` },
  { area: 'Data', title: 'Seed operational dates follow the first-load day',
    why: 'The sample workspace is captured on a fixed day. When a browser first loads it, due and start dates of open work, the MDL date of a package with no 8130-9 yet, planned need dates, open request and CAR due dates, and stamp expiries move forward by the days since capture, so the sample data does not age. A CAR, whose history quotes its due dates, and an order whose MDL date moves get a Demo build history entry naming the old and new dates. Signed and recorded dates (buy-offs, manifests, signatures, existing history, closed orders) never move. The calibrated tool snapshot moves by the same days (D-37). Source: tools/demo/seed-dates.mjs.',
    find: /JSON\.stringify\(window\.__DEMO_SEED\)/g, count: 2,
    replace: (ctx, m, id) => `JSON.stringify((${ctx.rebase})(window.__DEMO_SEED)/* DEMO ${id} */)` },
  { area: 'Roles', title: 'Any named signer role may sign a calibration entry',
    why: 'The full-access demo accounts (D-6) hold configure-qms whatever their role, so their calibration entries record and validate. Production accepts only the Quality Manager and System Administrator signer roles. Pilot seats are still refused by the configure-qms gate.',
    find: 'const calibrationSignerRole = role => CALIBRATION_SIGNER_ROLES.includes(role);', count: 1,
    replace: (ctx, m, id) => `const calibrationSignerRole = role => typeof role === 'string' && !!role.trim(); /* DEMO ${id} */` },
  { area: 'Data', title: 'Sample calibrated tool snapshot, following the first-load day',
    why: 'Production ships no tool snapshot: every tool in use comes from the signed calibration log that a QA Manager records or imports. The demo seeds carry no calibration log, so the demo loads the sample Calibrated Tool Log snapshot in tools/demo/cal-snapshot.json for its tool checks. Every sample tool would expire within a year of capture and block every operation that needs tooling, so the snapshot label and every tool expiry move forward by the same days as the seed dates (D-35), counted from the day the browser first loaded the demo; the spacing between tools is kept and tools still come due as days pass. Signed buy-offs keep the tool expiries they recorded. Source: tools/demo/seed-dates.mjs.',
    find: EMPTY_CAL, count: 1,
    replace: (ctx, m, id) => {
      const firstLoad = `(function(){try{return localStorage.getItem(${JSON.stringify(ctx.seedMark)})||undefined;}catch(e){return undefined;}})()`;
      // A JSON string is a valid JavaScript string literal; "<" is escaped so no label can close the script element.
      const snapshot = JSON.stringify(String(ctx.calSnapshot.snapshot)).replace(/</g, '\\u003c');
      return `/* DEMO ${id} */ const DEMO_CAL = (${ctx.calRebase})(${snapshot}, (typeof window !== 'undefined' && window.__DEMO_SEED) || null, ${firstLoad});\n  const CAL_SNAPSHOT = DEMO_CAL.snapshot;\n  const CAL_TOOLS = Object.freeze(${JSON.stringify(ctx.calSnapshot.tools).replace(/</g, '\\u003c')}.map(([tag, description, serial, expires, status, location]) => Object.freeze({ tag, description, serial, expires: DEMO_CAL.expires(expires), status, location })));`;
    } },
  { area: 'Accounts', title: 'Separate account storage key',
    why: 'The demo keeps its known-password accounts (D-4) under skyryse-mes-demo-auth-v1, so opening the demo in a browser that also holds the production build never adds master, demo or any other demo1234 account to the production account list, and the production page never sees a demo account. The production key stays frozen.',
    find: /(['"])skyryse-mes-auth-v1\1/g, count: 5,
    replace: (ctx, m, id) => `${m[0]}skyryse-mes-demo-auth-v1${m[0]}/* DEMO ${id} */` },
  { area: 'Data', title: 'Never the production mirror',
    why: 'Whatever mirror address and token the production file sets (the fallback object or a direct window.SK_MIRROR assignment), the demo replaces the whole setting with the one present before the page loaded, or an empty address. The demo never sends records made under its relaxed gates to the production retention database and never holds the production mirror token. tools/run-suites.mjs --mirror gives the demo its own throwaway server through __FS_SUITE_DEMO_MIRROR__, which D-42 captures.',
    find: /window\.SK_MIRROR = [^;{]*\{[\s\S]*?\};/g, count: 1,
    replace: (ctx, m, id) => `/* DEMO ${id} */ window.SK_MIRROR = window.__demoMirrorPreset || { url: '', token: '', batchSize: 50 };` },
  { area: 'Data', title: 'Separate mirror queue keys',
    why: 'Records the demo queues for a mirror are kept under skyryse-mes-demo-sync-*, so a production page in the same browser never sends a demo record to its mirror.',
    find: /(['"])skyryse-mes-sync-(?:queue|sent|client)-v1\1/g, count: 5,
    replace: (ctx, m, id) => `${m.replace('skyryse-mes-sync-', 'skyryse-mes-demo-sync-')}/* DEMO ${id} */` },
  { area: 'Accounts', title: 'Separate session, lockout, security log, sign-in tokens, drafts, evidence and saved table filter storage',
    why: 'Signing in to the demo never signs anyone in to the production page in the same tab, and signing out of the demo never removes the production server session token when the server also serves the demo. Failed or successful demo sign-ins never lock or unlock a production account of the same name, demo sign-ins and role changes never appear in the production security log or its export, and demo drafts, evidence and saved table filters stay out of production: a filter saved or removed in the demo never changes a production filter of the same name. Each key gains -demo- in the demo build; the production keys are unchanged.',
    find: /(['"])skyryse-mes-(session|lockout|security|oidc|server-token|drafts|evidence|tablefilters)-v1\1/g, count: 15,
    replace: (ctx, m, id) => `${m.replace('skyryse-mes-', 'skyryse-mes-demo-')}/* DEMO ${id} */` },
  { area: 'Data', title: 'Mirror setting taken before the page loads; old demo records dropped from the shared queue',
    why: 'Takes a mirror only from __FS_SUITE_DEMO_MIRROR__, which only tools/run-suites.mjs --mirror sets, and never from SK_MIRROR, so neither an address and token written in the production file (D-39) nor an SK_MIRROR a page or proxy sets before load reaches the demo. A demo built before D-40 queued its records under the production queue key if IT had set a mirror address in index.html; on first open the demo removes queued records that name the demo workspace, so a production page in the same browser cannot send them. Queued account records an older demo made are removed by production itself (purgeLegacyDemoState), which can tell them apart by their creator.',
    find: '<title>Flight System Demo</title>', count: 1,
    replace: (ctx, m, id) => `<script>/* DEMO ${id} */window.__demoMirrorPreset=window.__FS_SUITE_DEMO_MIRROR__||null;try{var Q='skyryse-mes-sync-'+'queue-v1',q=JSON.parse(localStorage.getItem(Q)||'null');if(Array.isArray(q)){var keep=q.filter(function(r){return !(r&&r.storeKey==='skyryse-mes-work-order-qa100-v1');});if(keep.length!==q.length)localStorage.setItem(Q,JSON.stringify(keep));}}catch(e){}</script>\n<title>Flight System Demo</title>` },
  { area: 'Data', title: 'Earlier demo recordings read from the old evidence store',
    why: 'D-41 gives the demo its own evidence database. A demo record made before that still names a recording kept in the old shared database, so when the demo database does not hold a recording the demo reads that one recording, by the ID its own record names, from the old database (never creating it) and copies it into the demo database. Production recordings are never listed or copied: only an ID a demo record names is read.',
    find: "get: async id => { if (!serverMode()) return transact('get', id);", count: 1,
    replace: (ctx, m, id) => `get: async id => { if (!serverMode()) { /* DEMO ${id} */ const own = await transact('get', id); if (own !== null) return own; const old = await new Promise(done => { try { let fresh = false; const r = root.indexedDB.open('skyryse-mes-' + 'evidence-v1'); r.onupgradeneeded = () => { fresh = true; r.transaction.abort(); }; r.onerror = () => done(null); r.onsuccess = () => { const d = r.result; if (fresh || !d.objectStoreNames.contains(STORE)) { d.close(); done(null); return; } try { const g = d.transaction(STORE, 'readonly').objectStore(STORE).get(id); g.onsuccess = () => { d.close(); done(g.result instanceof Blob ? g.result : null); }; g.onerror = () => { d.close(); done(null); }; } catch (e) { d.close(); done(null); } }; } catch (e) { done(null); } }); if (old) await transact('put', id, old).catch(() => {}); return old; }` },
  { area: 'Accounts', title: 'Production cleanup of older demo leftovers switched off',
    why: 'Production removes the known-password accounts, the accounts they created and the queued mirror records an older demo build left in its storage, moves the security events demo pages wrote out of the production security log, and then clears its mirror sent index and moves its drafts aside. The demo keeps its accounts under its own keys (D-38, D-41) and must not remove them, so the cleanup returns at once in the demo build.',
    find: 'function purgeLegacyDemoState(){\n', count: 1,
    replace: (ctx, m, id) => `function purgeLegacyDemoState(){return;/* DEMO ${id} */\n` },
  { area: 'Accounts', title: 'Local sign-in only',
    why: 'Whatever identity provider the production file or the page sets, the demo signs in only with its own local accounts (D-4) and the password demo1234. It never starts the production single sign-on redirect, never receives a production identity token, and signing out never calls the production provider.',
    find: '  var cfg = window.SK_IDENTITY;\n', count: 1,
    replace: (ctx, m, id) => `  var cfg = window.SK_IDENTITY; cfg.provider = 'local'; /* DEMO ${id} */\n` },
  { area: 'Accounts', title: 'Never the production server',
    why: 'Whatever server setting a deployment, proxy or page puts in front of the demo (window.FLIGHT_SERVER, which the Flight System server writes only into its production page), the demo removes it before any of its own scripts run and keeps it unset, so the demo never signs in to the production server, never loads or writes the shared production workspace, and always works on its own browser storage under its relaxed rules.',
    find: '<title>Flight System Demo</title>', count: 1,
    replace: (ctx, m, id) => `<script>/* DEMO ${id} */try{delete window.FLIGHT_SERVER;}catch(e){}try{Object.defineProperty(window,'FLIGHT_SERVER',{get:function(){return undefined;},set:function(){},configurable:false});}catch(e){window.FLIGHT_SERVER=undefined;}</script>\n${m}` },
  { area: 'Stamps', title: 'FAIR and 8130-9 signatures accept a lapsed register stamp',
    why: 'Production refuses a FAIR, 8130-9 or AQI signature when the signer has no current stamp of an allowed type (expired, not yet issued, or an additional stamp paused for training, #579). The demo signs with the account\'s first Active stamp of an allowed type, as it did before that rule, so a scenario is not stopped by stamp dates. An account with no Active stamp of an allowed type is still refused.',
    find: '    const current = checked.find(c => !c.problem);\n', count: 1,
    replace: (ctx, m, id) => `    const current = checked.find(c => !c.problem) || checked[0]; /* DEMO ${id} */\n` },
  { area: 'Data', title: 'Sample NetSuite stock, default kit lines and MRP forecast tables',
    why: 'Production ships no stock, starts every work order kit empty and ships empty forecast tables, so a production planned order records no NetSuite read until the live read is connected. The demo loads the sample lots (for example LOT-2401-0088), starts each new work order kit with the three sample lines those lots fill (SR-2401, SR-2402, SR-2403), and loads the finished goods on hand and the DEMO-marked bill of materials, component lots and lead-time actuals, so kitting and the Flight Plan forecast can be walked. Source: tools/demo/sample-data.mjs.',
    find: emptyOf(['NETSUITE_STOCK', 'DEFAULT_KIT', 'DEMO_PARTS', 'DEMO_FINISHED_STOCK', 'DEMO_MBOM', 'DEMO_COMPONENT_LOTS', 'DEMO_LEAD_ACTUALS']), count: 7,
    replace: (ctx, m, id) => sampleFor(m, id) },
  { area: 'Data', title: 'Sample master WIs, planned orders, stamp placeholders and starter rework drafts for a new demo workspace',
    why: 'A new production workspace starts with an empty master WI library, no planned orders, an empty stamp register and an empty standard rework library. The demo seeds carry their own; when a demo workspace is reset it starts again with the sample released WIs, the sample planned orders, the numbered stamp placeholders and generic role credentials, and the starter rework drafts, as earlier builds did. Source: tools/demo/sample-data.mjs.',
    find: emptyOf(['STAMP_HOLDERS', 'seedMasterWIs', 'STD_REWORK_SEED', 'PLANNED_ORDER_SEED']), count: 4,
    replace: (ctx, m, id) => sampleFor(m, id) },
];

export const DEVIATIONS = LIST.map((d, i) => Object.freeze({ ...d, id: `D-${i + 1}` }));
