// Sample reference data for the demo build only. The production index.html ships these declarations empty
// (issue #247: a production workspace starts clean); tools/build-demo.mjs puts these sample versions back into
// demo.html and the demo fixtures through the deviations named below. Each value is the exact source of the
// declaration as earlier production builds shipped it, so the demo behaves as it did. The sample Calibrated Tool
// Log snapshot is in cal-snapshot.json (D-37). Nothing here is a real inventory position, tool, stamp or person.

// Sample NetSuite stock, default kit lines and MRP forecast tables (D-38).
export const NETSUITE_STOCK = "  const NETSUITE_STOCK = Object.freeze({\n    'SR-2401': Object.freeze([\n      Object.freeze({ lot: 'LOT-2401-0088', onHand: 12, bin: 'A-04-2', location: 'HHR', buildClass: 'Production' }),\n      Object.freeze({ lot: 'LOT-2401-0091', onHand: 5, bin: 'A-04-3', location: 'HHR', buildClass: 'Production' }),\n      Object.freeze({ lot: 'LOT-2401-0093', onHand: 8, bin: 'C-11-1', location: 'CMA', buildClass: 'Production' })\n    ]),\n    'SR-2402': Object.freeze([\n      Object.freeze({ lot: 'LOT-2402-0412', onHand: 3, bin: 'B-02-1', location: 'HHR', buildClass: 'Production' }),\n      Object.freeze({ lot: 'LOT-2402-0418', onHand: 21, bin: 'B-02-4', location: 'NASH', buildClass: 'Production' })\n    ]),\n    'SR-2403': Object.freeze([\n      Object.freeze({ lot: 'LOT-2403-1007', onHand: 40, bin: 'D-07-2', location: 'HHR', buildClass: 'Production' }),\n      Object.freeze({ lot: 'LOT-2403-1011', onHand: 16, bin: 'D-07-5', location: 'MAPLE', buildClass: 'Production' }),\n      Object.freeze({ lot: 'LOT-2403-1014', onHand: 2, bin: 'E-01-1', location: 'CMA', buildClass: 'Production' })\n    ])\n  });\n";
export const DEFAULT_KIT = "  function materials(ready = false) {\n    return [\n      { id: 'kit-1', name: 'Interface module', partNumber: 'SR-2401', required: 1, ready },\n      { id: 'kit-2', name: 'Harness set', partNumber: 'SR-2402', required: 1, ready },\n      { id: 'kit-3', name: 'Mounting pack', partNumber: 'SR-2403', required: 1, ready }\n    ];\n  }\n";
export const DEMO_PARTS = "  const DEMO_PARTS = Object.freeze(['SR-FC-200', 'SR-HC-050', 'SR-CI-110']);\n";
export const DEMO_FINISHED_STOCK = "  const DEMO_FINISHED_STOCK = Object.freeze({ 'SR-FC-200': 1, 'SR-HC-050': 6, 'SR-CI-110': 3 });\n";
export const DEMO_MBOM = "  const DEMO_MBOM = Object.freeze({\n    'SR-FC-200|C': [{ part: 'DEMO-MTR-011', rev: 'A', title: 'DEMO drive motor', qtyPer: 1, leadDays: 45, interchangeable: true }, { part: 'DEMO-PCB-204', rev: 'C', title: 'DEMO controller board', qtyPer: 1, leadDays: 60, interchangeable: false, supersedes: 'B' }, { part: 'DEMO-SEAL-090', rev: 'A', title: 'DEMO shaft seal', qtyPer: 2, leadDays: 20, interchangeable: true, shelfLifeDays: 365 }],\n    'SR-HC-050|A': [{ part: 'DEMO-WIRE-22', rev: 'A', title: 'DEMO 22 AWG wire (ft)', qtyPer: 40, leadDays: 14, interchangeable: true }, { part: 'DEMO-CONN-38', rev: 'A', title: 'DEMO 38-pin connector', qtyPer: 2, leadDays: 30, interchangeable: true }, { part: 'DEMO-ADH-7', rev: 'A', title: 'DEMO potting adhesive', qtyPer: 1, leadDays: 21, interchangeable: true, shelfLifeDays: 180 }]\n  });\n";
export const DEMO_COMPONENT_LOTS = "  const DEMO_COMPONENT_LOTS = Object.freeze([\n    { part: 'DEMO-MTR-011', rev: 'A', lot: 'LOT-DEMO-M1', onHand: 3, expires: null }, { part: 'DEMO-PCB-204', rev: 'B', lot: 'LOT-DEMO-P1', onHand: 6, expires: null }, { part: 'DEMO-PCB-204', rev: 'C', lot: 'LOT-DEMO-P2', onHand: 1, expires: null },\n    { part: 'DEMO-SEAL-090', rev: 'A', lot: 'LOT-DEMO-S1', onHand: 10, expires: '2026-10-05' }, { part: 'DEMO-SEAL-090', rev: 'A', lot: 'LOT-DEMO-S2', onHand: 8, expires: '2027-03-01' }, { part: 'DEMO-WIRE-22', rev: 'A', lot: 'LOT-DEMO-W1', onHand: 500, expires: null },\n    { part: 'DEMO-CONN-38', rev: 'A', lot: 'LOT-DEMO-C1', onHand: 12, expires: null }, { part: 'DEMO-ADH-7', rev: 'A', lot: 'LOT-DEMO-A1', onHand: 4, expires: '2026-09-28' }\n  ]);\n";
export const DEMO_LEAD_ACTUALS = "  const DEMO_LEAD_ACTUALS = Object.freeze([\n    { part: 'SR-FC-200', order: 'WO-DEMO-0901', issued: '2026-06-02', closed: '2026-06-19' }, { part: 'SR-FC-200', order: 'WO-DEMO-0917', issued: '2026-07-07', closed: '2026-07-28' }, { part: 'SR-FC-200', order: 'WO-DEMO-0933', issued: '2026-08-04', closed: '2026-08-22' },\n    { part: 'SR-HC-050', order: 'WO-DEMO-0905', issued: '2026-06-09', closed: '2026-06-16' }, { part: 'SR-HC-050', order: 'WO-DEMO-0921', issued: '2026-07-14', closed: '2026-07-23' }\n  ]);\n";

// Sample master WIs, planned orders, stamp register placeholders and starter rework drafts for a new demo workspace (D-39).
export const STAMP_HOLDERS = "  const STAMP_HOLDERS = Object.freeze([['Quality', 'Quality'], ['Production', 'Production'], ['Quality', 'Quality'], ['Quality', 'Quality'], ['Production', 'Production'], ['Quality', 'Quality'], ['Quality', 'Quality']].map(([department, type], n) => Object.freeze({ name: placeholderName(stampNumber(n)), department, type, number: stampNumber(n), since: '2026-01-01', buyoffType: type === 'Production' ? 'Technician' : type, roleOnly: false, placeholder: true })).concat([['Technician', 'Production', 'Technician', 'Technician'], ['Quality inspector', 'Quality', 'Quality', 'Quality'], ['A&P mechanic', 'Maintenance', 'A&P', 'A&P'], ['Design engineer', 'Engineering', 'Engineering', 'Engineering'], ['Authorized inspector', 'Quality', '8130-9 AI', '8130-9 Authorized Inspector'], ['Conformity inspector', 'Quality', 'Conformity', 'Conformity Inspector']].map(([name, department, type, buyoffType], n) => Object.freeze({ name, department, type, number: stampNumber(7 + n), since: '2026-01-01', buyoffType, roleOnly: true }))));\n";
export const seedMasterWIs = "  function seedMasterWIs() {\n    const base = operations().map(op => ({ id: op.id, title: op.title, description: op.description, requiresRecording: false, buyoffType: defaultBuyoffType(op.id), inspectionPoint: op.id === 'op-040', requiresTooling: ['op-030', 'op-040'].includes(op.id), steps: defaultSteps(op.id, op.title) }));\n    const list = PART_CATALOG.map((part, index) => {\n      const ops = JSON.parse(JSON.stringify(base));\n      if (part.partNumber === 'SR-IN-030') ops[2].requiresRecording = true;\n      return { id: `MWI-${String(index + 1).padStart(4, '0')}`, revision: 'A', status: 'Released', partNumber: part.partNumber, partRevision: part.revisions[0], title: `${part.title} master work order`, operations: ops, releasedAt: '2026-09-01T16:00:00.000Z', history: [{ at: '2026-09-01T16:00:00.000Z', action: 'Released by QA.', actor: 'QA reviewer · SR-QA-001' }] };\n    });\n    const draft = { ...JSON.parse(JSON.stringify(list[0])), revision: 'B', status: 'Draft', history: [{ at: '2026-09-14T17:00:00.000Z', action: 'Revision B started from Rev A.', actor: 'Engineer · SR-ME-001' }] };\n    delete draft.releasedAt;\n    return [draft, ...list];\n  }\n";
export const STD_REWORK_SEED = "  const STD_REWORK_SEED = [\n    ['Re-torque fastener(s) to drawing value', 'Rework', 'Technician', true, [['Remove torque stripe', 'Remove the existing torque stripe from the affected fastener(s) with an approved solvent.'], ['Loosen and clean', 'Back off the fastener, inspect threads for damage, clean as required.'], ['Re-torque', 'Torque to the drawing or WI value with a calibrated tool. Record the value and tool.'], ['Apply torque stripe', 'Apply a new torque stripe across fastener and substrate.']]],\n    ['Replace connector backshell and re-terminate', 'Rework', 'Technician', true, [['De-mate and remove backshell', 'De-mate the connector, remove the backshell and strain relief. Protect the pins.'], ['Inspect contacts', 'Inspect contacts and wires for damage. Replace any damaged contact per the harness drawing.'], ['Install backshell', 'Install the backshell and strain relief. Torque to the drawing value.'], ['Continuity check', 'Perform a continuity check on affected circuits and record the result.']]],\n    ['Solder joint rework per J-STD-001', 'Rework', 'Technician', false, [['Remove defective joint', 'Remove solder from the defective joint with wick or vacuum. Protect adjacent parts.'], ['Clean', 'Clean the area and inspect the pad and lead for damage.'], ['Re-solder', 'Re-solder per J-STD-001 at the class called out on the drawing.'], ['Inspect', 'Inspect the joint under magnification and record the result.']]],\n    ['Touch-up finish or coating per spec', 'Repair', 'Technician', false, [['Prepare surface', 'Mask the area. Clean and abrade the damaged coating per the finish spec.'], ['Apply touch-up', 'Apply the touch-up material called out on the drawing within its shelf life. Record the material lot.'], ['Cure and inspect', 'Cure per the material data sheet and inspect coverage and color code.']]],\n    ['Remove and replace component', 'Rework', 'Technician', true, [['Remove component', 'Remove the nonconforming component. Quarantine it with the NC tag.'], ['Install replacement', 'Install a conforming replacement from stock. Record its part number and lot or serial.'], ['Torque and verify', 'Torque fasteners to the drawing value and verify the installation.']]],\n    ['Clean and re-inspect for FOD', 'Rework', 'Technician', false, [['Clean', 'Clean the affected area and remove all foreign objects. Account for all tools.'], ['Re-inspect', 'Re-inspect the area and adjacent areas for FOD and damage.']]]\n  ];\n";
export const PLANNED_ORDER_SEED = "    const seed = [\n      ['SR-FC-200', 'Production', 'Mfg.', 'HHR', 'C3', 4, '2026-10-09', null],\n      ['SR-HC-050', 'Production', 'Mfg.', 'CMA', 'C2', 10, '2026-09-30', 'firm'],\n      ['SR-CI-110', 'Production', 'Mfg.', 'HHR', 'C4', 2, '2026-10-02', 'firm'],\n      ['SR-FC-200', 'Development', 'Installation', 'HHR', 'C4', 1, '2026-09-12', null],\n      ['SR-HC-050', 'Production', 'FAI', 'NASH', 'C5', 2, '2026-10-20', 'Demand withdrawn (DEMO).']\n    ];\n";
