#!/usr/bin/env node
// Builds the demo from the production file. Nothing about the demo is edited by hand.
//
//   node tools/build-demo.mjs          rebuild demo.html, the four test fixtures and docs/DEMO_DEVIATIONS.md
//   node tools/build-demo.mjs --check  rebuild in memory and fail (exit 1) if any output on disk differs,
//                                      if any replacement target is missing or matches a different number
//                                      of times, or if the production engine compares a username to "demo"
//
// Node built-ins only. See docs/DEMO_DEVIATIONS.md for what each deviation does and why.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { DEVIATIONS, PILOT_SEATS } from './demo/deviations.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const at = p => path.join(ROOT, p);
const read = p => fs.readFileSync(at(p), 'utf8');

// Each demo output: which sample dataset it carries and the mark that makes the overlay load it once.
export const OUTPUTS = [
  { file: 'demo.html', dataset: 'curated' },
  { file: 'tests/fixtures/demo_publish.html', dataset: 'curated' },
  { file: 'tests/fixtures/demo_qa150.html', dataset: 'qa150' },
  { file: 'tests/fixtures/demo_qa150_publish.html', dataset: 'qa150' },
];
export const PRODUCTION_FIXTURE = 'tests/fixtures/publish.html';
const DOC = 'docs/DEMO_DEVIATIONS.md';

// The only production code allowed to name the demo username is the one-time notice that records the
// removal of the old bypass for an existing account called demo.
const DEMO_LITERAL_ALLOWED = 'function noteDemoAccount';

function countMatches(src, find) {
  if (typeof find === 'string') { let n = 0, i = 0; while ((i = src.indexOf(find, i)) !== -1) { n++; i += find.length; } return n; }
  const re = new RegExp(find.source, find.flags.includes('g') ? find.flags : find.flags + 'g');
  return [...src.matchAll(re)].length;
}

function applyOne(src, dev, ctx) {
  const found = countMatches(src, dev.find);
  if (found !== dev.count) {
    const what = typeof dev.find === 'string' ? JSON.stringify(dev.find.slice(0, 80)) : String(dev.find);
    throw new Error(`${dev.id} (${dev.title}): expected ${dev.count} match${dev.count === 1 ? '' : 'es'} of ${what} in index.html, found ${found}. Update tools/demo/deviations.mjs to the new production code, then rebuild.`);
  }
  if (typeof dev.find === 'string') return src.split(dev.find).join(dev.replace(ctx, dev.find, dev.id));
  const re = new RegExp(dev.find.source, dev.find.flags.includes('g') ? dev.find.flags : dev.find.flags + 'g');
  return src.replace(re, m => dev.replace(ctx, m, dev.id));
}

export function buildDemo(production, dataset) {
  const seedMark = `skyryse-mes-demo-seed-${dataset}`;
  const ctx = {
    seed: JSON.stringify(JSON.parse(read(`tools/demo/seed-${dataset}.json`))),
    accounts: JSON.stringify(JSON.parse(read('tools/demo/accounts.json'))),
    seedMark,
    overlay: read('tools/demo/overlay.js').replace('__SEED_MARK__', seedMark),
  };
  if (ctx.seed.includes('</script')) throw new Error(`tools/demo/seed-${dataset}.json contains "</script" and would break the page.`);
  let out = production;
  for (const dev of DEVIATIONS) out = applyOne(out, dev, ctx);
  return out;
}

export function demoLiteralLines(production) {
  return production.split('\n').map((line, i) => ({ line: i + 1, text: line }))
    .filter(l => /['"`]demo['"`]/.test(l.text) && !l.text.includes(DEMO_LITERAL_ALLOWED));
}

export function deviationsDoc() {
  const ids = area => { const l = DEVIATIONS.filter(d => d.area === area).map(d => d.id); return l.length > 1 ? `${l[0]} to ${l[l.length - 1]}` : l[0]; };
  const rows = DEVIATIONS.map(d => `| ${d.id} | ${d.area} | ${d.title} | ${d.why.replace(/\|/g, '\\|')} | ${d.count} |`).join('\n');
  return `# Demo deviations

Generated by \`node tools/build-demo.mjs\` from \`tools/demo/deviations.mjs\`. Do not edit by hand.

\`demo.html\` and the demo test fixtures are built from \`index.html\` by applying exactly the
deviations below, in order, and nothing else. Each deviation is one replacement rule with an exact
expected match count; the build stops if a target is missing or matches a different number of
times, so a change to the production code can never silently drop or double a relaxation. Where the
syntax allows it, the replaced code carries a \`DEMO D-n\` marker so the deviation can be found in the
built file.

\`node tools/build-demo.mjs --check\` rebuilds everything in memory and fails if any built file on disk
differs byte for byte, if any target is missing, or if the production engine compares a username to
\`demo\`. CI runs it on every pull request.

## Pilot seats

The accounts ${PILOT_SEATS.map(s => `\`${s}\``).join(', ')} are pilot seats. They keep the capabilities of
their real role (Technician, Quality, Manufacturing Engineering, Operations, Engineering) so a pilot
can rehearse the real hand-offs. Every other demo account (\`demo\`, \`master\`, \`safety\`,
\`certification\` and any account a person creates) has full access (${ids('Roles')}). The stamp,
PIN and separation-of-duties relaxations (${ids('Stamps')}; ${ids('Separation of duties')}) apply to every
demo account so no scenario stalls. Sign in with any account and the password \`demo1234\`.

Every demo page and every print and download shows DEMO, NOT FOR ACCEPTANCE (${ids('Marking')}).

## Outputs

| File | Sample data |
| --- | --- |
${OUTPUTS.map(o => `| \`${o.file}\` | ${o.dataset === 'curated' ? 'curated set (9 work orders, LRU conformity package, FAIR, NC with MRB, CAR)' : '150 work orders, 55 planned orders, 54 Flight Maneuver records'} |`).join('\n')}
| \`${PRODUCTION_FIXTURE}\` | none: a byte copy of \`index.html\` for the production suites |

## Deviations

| Id | Area | Deviation | Why | Matches |
| --- | --- | --- | --- | --- |
${rows}
`;
}

function main() {
  const check = process.argv.includes('--check');
  const production = read('index.html');
  const problems = [];
  const literal = demoLiteralLines(production);
  if (literal.length) problems.push(`index.html compares a username to "demo" outside ${DEMO_LITERAL_ALLOWED}: ${literal.map(l => `line ${l.line}`).join(', ')}. Move the relaxation into tools/demo/deviations.mjs.`);
  let built;
  try {
    const byDataset = {};
    built = OUTPUTS.map(o => {
      let text = byDataset[o.dataset] ??= buildDemo(production, o.dataset);
      if (o.file.startsWith('tests/fixtures/')) text = text.replace(/((?:src|href)=")assets\//g, '$1../../assets/');
      return { file: o.file, text };
    });
  } catch (error) { problems.push(error.message); built = []; }
  built.push({ file: PRODUCTION_FIXTURE, text: production.replace(/((?:src|href)=")assets\//g, '$1../../assets/') }, { file: DOC, text: deviationsDoc() });
  const sha = t => crypto.createHash('sha256').update(t).digest('hex');
  for (const { file, text } of built) {
    if (check) {
      const disk = fs.existsSync(at(file)) ? fs.readFileSync(at(file), 'utf8') : null;
      if (disk !== text) problems.push(`${file} is not current: it does not rebuild byte for byte from index.html. Run node tools/build-demo.mjs and commit the result.`);
    } else if (!problems.length) {
      fs.writeFileSync(at(file), text);
      console.log(`wrote ${file}  sha256 ${sha(text).slice(0, 16)}`);
    }
  }
  if (problems.length) { problems.forEach(p => console.error('FAIL ' + p)); process.exit(1); }
  console.log(check ? `demo build is current: ${DEVIATIONS.length} deviations, ${built.length} files checked` : `built ${built.length} files from index.html with ${DEVIATIONS.length} deviations`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
