#!/usr/bin/env node
// Writes the release record into VERSION.md: the build id, the SHA-256 of index.html and demo.html, the
// suite results with the mirror off and on, and every skip with its reason.
//
//   node tools/release-report.mjs            write the record from tests/suite_results.json and
//                                            tests/suite_results_mirror.json (run tools/run-suites.mjs
//                                            with and without --mirror first)
//   node tools/release-report.mjs --check    exit 1 unless the record in VERSION.md names the build and
//                                            the hashes of the index.html and demo.html in the tree
//
// It refuses to write a record from results that failed, carry an unexplained skip, or were produced
// against different files than the ones in the tree. Node built-ins only.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const VERSION = path.join(ROOT, 'VERSION.md');
const START = '<!-- release-record:start. Generated by tools/release-report.mjs; do not edit by hand. -->';
const END = '<!-- release-record:end -->';

const fileSha = f => crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT, f))).digest('hex');
const stampOf = (html, name) => (html.match(new RegExp(`<meta name="${name}" content="([^"]*)">`)) || [])[1] || 'unstamped';

export function current() {
  const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  return { build: stampOf(html, 'fs-build'), indexStamp: stampOf(html, 'fs-build-sha256'), indexFileSha256: fileSha('index.html'), demoFileSha256: fileSha('demo.html') };
}

function readResults(name) {
  const f = path.join(ROOT, 'tests', name);
  if (!fs.existsSync(f)) throw new Error(`tests/${name} is missing. Run node tools/run-suites.mjs${name.includes('mirror') ? ' --mirror' : ''} first.`);
  return JSON.parse(fs.readFileSync(f, 'utf8'));
}

function assertUsable(r, label, now) {
  const failed = r.suites.filter(s => s.status !== 'pass');
  if (failed.length) throw new Error(`${label}: ${failed.length} suite(s) failed (${failed.map(s => s.name).join(', ')}). A release record is written only from a clean run.`);
  const unexplained = r.skips.filter(s => !s.reason);
  if (unexplained.length) throw new Error(`${label}: unexplained skip ${unexplained.map(s => s.check).join('; ')}.`);
  const t = r.tested || {};
  for (const k of Object.keys(now)) if (t[k] !== now[k]) throw new Error(`${label}: the results were produced against a different ${k} (${t[k] || 'not recorded'}) than the tree (${now[k]}). Run the suites again.`);
}

export function record(now, off, on) {
  const byName = new Map();
  for (const s of off.suites) byName.set(s.name, { name: s.name, checks: s.checks, off: s.status, on: null });
  for (const s of on.suites) { const e = byName.get(s.name) || { name: s.name, checks: s.checks, off: null, on: null }; e.on = s.status; byName.set(s.name, e); }
  const rows = [...byName.values()].sort((a, b) => a.name.localeCompare(b.name));
  const count = r => `${r.suites.filter(s => s.status === 'pass').length} of ${r.suites.length} pass`;
  const skips = [...off.skips.map(s => ({ ...s, run: 'mirror off' })), ...on.skips.map(s => ({ ...s, run: 'mirror on' }))];
  const cell = v => v === 'pass' ? 'pass' : v === null ? 'not run' : v;
  return [
    START,
    '## Release record',
    '',
    '| Item | Value |',
    '| --- | --- |',
    `| Build | ${now.build} |`,
    `| index.html SHA-256, as stamped in the file | \`${now.indexStamp}\` |`,
    `| index.html file SHA-256 | \`${now.indexFileSha256}\` |`,
    `| demo.html file SHA-256 | \`${now.demoFileSha256}\` |`,
    `| Suites run | ${off.startedAt.slice(0, 10)} |`,
    `| Mirror off | ${count(off)} |`,
    `| Mirror on | ${count(on)}${on.mirror ? `; the mirror received ${on.mirror.records} records, chain ${on.mirror.chainIntact ? 'intact' : 'broken'}` : ''} |`,
    `| Skips | ${skips.length}, every one explained below |`,
    '',
    'The stamped SHA-256 is the hash of `index.html` with its own `fs-build-sha256` field set to',
    '`unstamped`; recompute it with `node tools/stamp-build.mjs --verify index.html`. The file SHA-256',
    'values are plain hashes of the files as committed.',
    '',
    '| Suite | Checks | Mirror off | Mirror on |',
    '| --- | --- | --- | --- |',
    ...rows.map(r => `| ${r.name} | ${r.checks ?? ''} | ${cell(r.off)} | ${cell(r.on)} |`),
    '',
    ...(skips.length ? ['Skips:', '', ...skips.map(s => `- ${s.suite}, ${s.run}: ${s.check}. ${s.reason}`)] : ['No skips.']),
    END,
  ].join('\n');
}

export function readRecord(text) {
  const a = text.indexOf(START), b = text.indexOf(END);
  if (a < 0 || b < a) return null;
  const block = text.slice(a, b);
  const val = label => { const m = block.match(new RegExp(`\\| ${label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')} \\| \`?([^|\`]+)\`? \\|`)); return m ? m[1].trim() : null; };
  return { build: val('Build'), indexStamp: val('index.html SHA-256, as stamped in the file'), indexFileSha256: val('index.html file SHA-256'), demoFileSha256: val('demo.html file SHA-256') };
}

function main() {
  const now = current();
  const text = fs.readFileSync(VERSION, 'utf8');
  if (process.argv.includes('--check')) {
    const r = readRecord(text);
    if (!r) { console.error('FAIL VERSION.md has no release record. Run the suites, then node tools/release-report.mjs.'); process.exit(1); }
    const wrong = Object.keys(now).filter(k => r[k] !== now[k]);
    if (wrong.length) { console.error(`FAIL the VERSION.md release record is out of date: ${wrong.map(k => `${k} is ${r[k]}, the tree has ${now[k]}`).join('; ')}. Run the suites, then node tools/release-report.mjs.`); process.exit(1); }
    console.log(`VERSION.md release record matches the tree: build ${now.build}, index.html ${now.indexFileSha256}, demo.html ${now.demoFileSha256}`);
    return;
  }
  const off = readResults('suite_results.json'), on = readResults('suite_results_mirror.json');
  assertUsable(off, 'mirror off', now); assertUsable(on, 'mirror on', now);
  const block = record(now, off, on);
  const a = text.indexOf(START), b = text.indexOf(END);
  const next = a >= 0 && b > a ? text.slice(0, a) + block + text.slice(b + END.length) : text.replace(/\s*$/, '\n\n') + block + '\n';
  fs.writeFileSync(VERSION, next);
  console.log(`VERSION.md release record written: build ${now.build}, ${off.suites.length} suites, ${off.skips.length + on.skips.length} explained skips`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { main(); } catch (error) { console.error('FAIL ' + error.message); process.exit(1); }
}
