#!/usr/bin/env node
// Generates docs/ROLE_MATRIX.md from the role table in index.html (ROLES, ROLE_CAPS and the capability
// labels in the sign-in block). The matrix is never written by hand.
//
//   node tools/role-matrix.mjs          write docs/ROLE_MATRIX.md
//   node tools/role-matrix.mjs --check  fail (exit 1) if docs/ROLE_MATRIX.md is not what index.html produces
//
// Node built-ins only.
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = 'docs/ROLE_MATRIX.md';

// Pull the role table out of index.html and evaluate just that code, so the matrix is exactly what runs.
export function roleTable(html) {
  const start = html.indexOf(' var ROLES=[');
  const end = html.indexOf(' var ALL_CAPS=ROLE_CAPS.admin;');
  if (start < 0 || end < 0 || end < start) throw new Error('Could not find the role table (var ROLES=[ ... var ALL_CAPS) in index.html.');
  const labels = html.match(/label:function\(cap\)\{return \((\{[^}]*\})\)\[cap\]/);
  if (!labels) throw new Error('Could not find the capability labels (skAuth.label) in index.html.');
  const sandbox = {};
  vm.runInNewContext(`${html.slice(start, end)}\n;this.ROLES=ROLES;this.ROLE_CAPS=ROLE_CAPS;this.EVERYONE=EVERYONE;this.LABELS=${labels[1]};`, sandbox);
  return sandbox;
}

export function matrixDoc(html) {
  const { ROLES, ROLE_CAPS, EVERYONE, LABELS } = roleTable(html);
  const roles = ROLES.map(r => r.key);
  const caps = [...new Set(roles.flatMap(k => ROLE_CAPS[k] || []))];
  const order = Object.keys(LABELS);
  caps.sort((a, b) => (order.indexOf(a) + 1 || 999) - (order.indexOf(b) + 1 || 999) || a.localeCompare(b));
  const head = `| Capability | ${ROLES.map(r => r.label).join(' | ')} |\n| --- | ${ROLES.map(() => ':---:').join(' | ')} |`;
  const rows = caps.map(c => `| \`${c}\` ${LABELS[c] ? `(${LABELS[c]})` : ''} | ${roles.map(k => ((ROLE_CAPS[k] || []).includes(c) ? 'yes' : '')).join(' | ')} |`).join('\n');
  const seats = [['Quality', 'mrb-quality'], ['Manufacturing Engineering', 'mrb-me'], ['Engineering', 'mrb-eng'], ['Certification', 'mrb-cert']];
  const seatRows = seats.map(([seat, cap]) => `| ${seat} | \`${cap}\` | ${ROLES.filter(r => (ROLE_CAPS[r.key] || []).includes(cap)).map(r => r.label).join(', ') || 'none'} |`).join('\n');
  return `# Role matrix

Generated by \`node tools/role-matrix.mjs\` from the role table in \`index.html\` (\`ROLES\` and
\`ROLE_CAPS\` in the sign-in block). Do not edit by hand. \`node tools/role-matrix.mjs --check\` fails
if this file does not match the code, and CI runs it.

Every role starts from the base set (${EVERYONE.map(c => `\`${c}\``).join(', ')}). Master Access holds the
union of every role's capabilities. A capability lets a person act; separation of duties still
applies on top of it (the person who does a thing cannot approve it), and nobody inspects their own
work, whatever their role. Support Access is not a role: it is an account flag granted only by
Master Access, and it lifts two gates for one action with a logged reason (see \`docs/HANDOVER.md\`).

## Roles

| Key | Role | Profile shown on records | What it is for |
| --- | --- | --- | --- |
${ROLES.map(r => `| \`${r.key}\` | ${r.label} | ${r.profileRole} | ${r.hint} |`).join('\n')}

## Capabilities by role

${head}
${rows}

## MRB seats

A vote in a seat needs the seat's capability. One person holds one seat on a board.

| Seat | Capability | Roles that hold it |
| --- | --- | --- |
${seatRows}
`;
}

function main() {
  const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  const doc = matrixDoc(html);
  const file = path.join(ROOT, OUT);
  if (process.argv.includes('--check')) {
    const disk = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (disk !== doc) { console.error(`FAIL ${OUT} does not match the role table in index.html. Run node tools/role-matrix.mjs and commit the result.`); process.exit(1); }
    console.log(`${OUT} matches the role table`);
    return;
  }
  fs.writeFileSync(file, doc);
  console.log(`wrote ${OUT}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
